
////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class TwoStoryGrandfatherClockSouthAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {19548, -4, 2, 19}, {19548, 3, 2, 19}// 106	107	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new TwoStoryGrandfatherClockSouthAddonDeed();
			}
		}

		[ Constructable ]
		public TwoStoryGrandfatherClockSouthAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 1848, -3, -1, 57, 2418, -1, "", 1);// 1
			AddComplexComponent( (BaseAddon) this, 465, -3, -1, 7, 2418, -1, "", 1);// 2
			AddComplexComponent( (BaseAddon) this, 465, -3, 0, 7, 2418, -1, "", 1);// 3
			AddComplexComponent( (BaseAddon) this, 463, 2, 0, 7, 2418, -1, "", 1);// 4
			AddComplexComponent( (BaseAddon) this, 1972, 3, 0, 52, 2418, -1, "", 1);// 5
			AddComplexComponent( (BaseAddon) this, 1848, 3, -1, 0, 2418, -1, "", 1);// 6
			AddComplexComponent( (BaseAddon) this, 466, -3, -2, 7, 2418, -1, "", 1);// 7
			AddComplexComponent( (BaseAddon) this, 16675, 2, 0, 29, 2418, -1, "", 1);// 8
			AddComplexComponent( (BaseAddon) this, 41208, 0, -1, 28, 2418, -1, "", 1);// 9
			AddComplexComponent( (BaseAddon) this, 1339, -4, 0, 0, 2418, -1, "", 1);// 10
			AddComplexComponent( (BaseAddon) this, 16678, -4, 1, 6, 2418, -1, "", 1);// 11
			AddComplexComponent( (BaseAddon) this, 1848, 3, -1, 57, 2418, -1, "", 1);// 12
			AddComplexComponent( (BaseAddon) this, 1339, -3, 0, 0, 2418, -1, "", 1);// 13
			AddComplexComponent( (BaseAddon) this, 1339, -1, 0, 0, 2418, -1, "", 1);// 14
			AddComplexComponent( (BaseAddon) this, 1339, -4, 1, 0, 2418, -1, "", 1);// 15
			AddComplexComponent( (BaseAddon) this, 1339, -3, 1, 0, 2418, -1, "", 1);// 16
			AddComplexComponent( (BaseAddon) this, 1339, -2, 1, 0, 2418, -1, "", 1);// 17
			AddComplexComponent( (BaseAddon) this, 464, 1, -2, 7, 2418, -1, "", 1);// 18
			AddComplexComponent( (BaseAddon) this, 464, -2, -2, 7, 2418, -1, "", 1);// 19
			AddComplexComponent( (BaseAddon) this, 2170, -2, 0, 57, 2418, -1, "", 1);// 20
			AddComplexComponent( (BaseAddon) this, 1848, 1, 1, 0, 2418, -1, "", 1);// 21
			AddComplexComponent( (BaseAddon) this, 1339, -1, 1, 0, 2418, -1, "", 1);// 22
			AddComplexComponent( (BaseAddon) this, 16677, 2, -2, 29, 2418, -1, "", 1);// 23
			AddComplexComponent( (BaseAddon) this, 16660, -2, -2, 29, 2418, -1, "", 1);// 24
			AddComplexComponent( (BaseAddon) this, 1339, 0, 0, 0, 2418, -1, "", 1);// 25
			AddComplexComponent( (BaseAddon) this, 16660, 1, 0, 29, 2418, -1, "", 1);// 26
			AddComplexComponent( (BaseAddon) this, 19514, -1, 1, 22, 2418, -1, "", 1);// 27
			AddComplexComponent( (BaseAddon) this, 1848, -4, 1, 0, 2418, -1, "", 1);// 28
			AddComplexComponent( (BaseAddon) this, 1848, 3, 1, 0, 2418, -1, "", 1);// 29
			AddComplexComponent( (BaseAddon) this, 19514, -2, 1, 22, 2418, -1, "", 1);// 30
			AddComplexComponent( (BaseAddon) this, 464, -2, 0, 7, 2418, -1, "", 1);// 31
			AddComplexComponent( (BaseAddon) this, 16676, -3, 0, 29, 2418, -1, "", 1);// 32
			AddComplexComponent( (BaseAddon) this, 466, -3, 1, 5, 2418, -1, "", 1);// 33
			AddComplexComponent( (BaseAddon) this, 466, 2, 1, 5, 2418, -1, "", 1);// 34
			AddComplexComponent( (BaseAddon) this, 479, -3, 1, 25, 2418, -1, "", 1);// 35
			AddComplexComponent( (BaseAddon) this, 479, 2, 1, 25, 2418, -1, "", 1);// 36
			AddComplexComponent( (BaseAddon) this, 16666, 2, -1, 29, 2418, -1, "", 1);// 37
			AddComplexComponent( (BaseAddon) this, 464, 1, 0, 7, 2418, -1, "", 1);// 38
			AddComplexComponent( (BaseAddon) this, 1848, -2, -1, 0, 2418, -1, "", 1);// 39
			AddComplexComponent( (BaseAddon) this, 11632, -2, 1, 6, 0, -1, "The Great Grandfather Clock [2024]", 1);// 40
			AddComplexComponent( (BaseAddon) this, 464, 0, 0, 7, 2418, -1, "", 1);// 41
			AddComplexComponent( (BaseAddon) this, 1848, -3, -1, 0, 2418, -1, "", 1);// 42
			AddComplexComponent( (BaseAddon) this, 1339, -2, 0, 0, 2418, -1, "", 1);// 43
			AddComplexComponent( (BaseAddon) this, 19514, 0, 1, 22, 2418, -1, "", 1);// 44
			AddComplexComponent( (BaseAddon) this, 1339, 0, 1, 0, 2418, -1, "", 1);// 45
			AddComplexComponent( (BaseAddon) this, 16678, 3, 1, 6, 2418, -1, "", 1);// 46
			AddComplexComponent( (BaseAddon) this, 1339, -4, 2, 0, 2418, -1, "", 1);// 47
			AddComplexComponent( (BaseAddon) this, 11632, 0, 1, 6, 0, -1, "Made By doug111973@gmail.com or Olorin on ServUO.com", 1);// 48
			AddComplexComponent( (BaseAddon) this, 1848, -2, -1, 52, 2418, -1, "", 1);// 49
			AddComplexComponent( (BaseAddon) this, 1339, -3, 2, 0, 2418, -1, "", 1);// 50
			AddComplexComponent( (BaseAddon) this, 1848, 1, -1, 0, 2418, -1, "", 1);// 51
			AddComplexComponent( (BaseAddon) this, 1339, -2, 2, 0, 2418, -1, "", 1);// 52
			AddComplexComponent( (BaseAddon) this, 1848, 3, 0, 57, 2418, -1, "", 1);// 53
			AddComplexComponent( (BaseAddon) this, 16660, -2, 0, 29, 2418, -1, "", 1);// 54
			AddComplexComponent( (BaseAddon) this, 2172, 2, -1, 57, 2418, -1, "", 1);// 55
			AddComplexComponent( (BaseAddon) this, 2172, -1, -1, 57, 2418, -1, "", 1);// 56
			AddComplexComponent( (BaseAddon) this, 2170, -2, -1, 57, 2418, -1, "", 1);// 57
			AddComplexComponent( (BaseAddon) this, 2170, 1, -1, 57, 2418, -1, "", 1);// 58
			AddComplexComponent( (BaseAddon) this, 16666, -3, -1, 29, 2418, -1, "", 1);// 59
			AddComplexComponent( (BaseAddon) this, 465, 2, -1, 7, 2418, -1, "", 1);// 60
			AddComplexComponent( (BaseAddon) this, 42370, 3, 1, 33, 2418, -1, "", 1);// 61
			AddComplexComponent( (BaseAddon) this, 42370, -4, 1, 33, 2418, -1, "", 1);// 62
			AddComplexComponent( (BaseAddon) this, 16660, -1, 0, 29, 2418, -1, "", 1);// 63
			AddComplexComponent( (BaseAddon) this, 16663, -3, -2, 29, 2418, -1, "", 1);// 64
			AddComplexComponent( (BaseAddon) this, 1339, -1, 2, 0, 2418, -1, "", 1);// 65
			AddComplexComponent( (BaseAddon) this, 1339, 0, 2, 0, 2418, -1, "", 1);// 66
			AddComplexComponent( (BaseAddon) this, 1848, -4, 0, 0, 2418, -1, "", 1);// 67
			AddComplexComponent( (BaseAddon) this, 19514, 1, 1, 22, 2418, -1, "", 1);// 68
			AddComplexComponent( (BaseAddon) this, 16660, 0, -2, 29, 2418, -1, "", 1);// 69
			AddComplexComponent( (BaseAddon) this, 16667, -4, 1, 13, 2418, -1, "", 1);// 70
			AddComplexComponent( (BaseAddon) this, 1849, 2, 2, 0, 2418, -1, "", 1);// 71
			AddComplexComponent( (BaseAddon) this, 1848, 2, 0, 0, 2418, -1, "", 1);// 72
			AddComplexComponent( (BaseAddon) this, 1848, 2, 1, 0, 2418, -1, "", 1);// 73
			AddComplexComponent( (BaseAddon) this, 1849, 1, 2, 0, 2418, -1, "", 1);// 74
			AddComplexComponent( (BaseAddon) this, 464, 2, -2, 7, 2418, -1, "", 1);// 75
			AddComplexComponent( (BaseAddon) this, 35728, 3, -1, 25, 2418, -1, "Clock Controls", 1);// 76
			AddComplexComponent( (BaseAddon) this, 481, -3, 1, 45, 2418, -1, "", 1);// 77
			AddComplexComponent( (BaseAddon) this, 19550, 0, 0, 57, 0, -1, "Clock Bell", 1);// 78
			AddComplexComponent( (BaseAddon) this, 481, 2, 1, 45, 2418, -1, "", 1);// 79
			AddComplexComponent( (BaseAddon) this, 18174, -1, 1, 35, 1177, -1, "", 1);// 80
			AddComplexComponent( (BaseAddon) this, 1856, -4, 2, 0, 2418, -1, "", 1);// 81
			AddComplexComponent( (BaseAddon) this, 1848, -3, 0, 0, 2418, -1, "", 1);// 82
			AddComplexComponent( (BaseAddon) this, 1848, -3, 1, 0, 2418, -1, "", 1);// 83
			AddComplexComponent( (BaseAddon) this, 1849, -3, 2, 0, 2418, -1, "", 1);// 84
			AddComplexComponent( (BaseAddon) this, 1848, -2, 0, 0, 2418, -1, "", 1);// 85
			AddComplexComponent( (BaseAddon) this, 1848, -2, 1, 0, 2418, -1, "", 1);// 86
			AddComplexComponent( (BaseAddon) this, 1849, -2, 2, 0, 2418, -1, "", 1);// 87
			AddComplexComponent( (BaseAddon) this, 1848, -2, 0, 52, 2418, -1, "", 1);// 88
			AddComplexComponent( (BaseAddon) this, 1848, 1, 0, 0, 2418, -1, "", 1);// 89
			AddComplexComponent( (BaseAddon) this, 1849, 0, 2, 0, 2418, -1, "", 1);// 90
			AddComplexComponent( (BaseAddon) this, 1973, -3, 0, 52, 2418, -1, "", 1);// 91
			AddComplexComponent( (BaseAddon) this, 1848, -1, 0, 52, 2418, -1, "", 1);// 92
			AddComplexComponent( (BaseAddon) this, 1973, -3, -1, 52, 2418, -1, "", 1);// 93
			AddComplexComponent( (BaseAddon) this, 1972, 3, -1, 52, 2418, -1, "", 1);// 94
			AddComplexComponent( (BaseAddon) this, 1848, 0, -1, 52, 2418, -1, "", 1);// 95
			AddComplexComponent( (BaseAddon) this, 1848, 0, 0, 52, 2418, -1, "", 1);// 96
			AddComplexComponent( (BaseAddon) this, 1848, 3, 0, 0, 2418, -1, "", 1);// 97
			AddComplexComponent( (BaseAddon) this, 1848, -1, 1, 0, 2418, -1, "", 1);// 98
			AddComplexComponent( (BaseAddon) this, 1848, 0, 1, 0, 2418, -1, "", 1);// 99
			AddComplexComponent( (BaseAddon) this, 1848, -1, 0, 0, 2418, -1, "", 1);// 100
			AddComplexComponent( (BaseAddon) this, 2172, 2, 0, 57, 2418, -1, "", 1);// 101
			AddComplexComponent( (BaseAddon) this, 1848, 1, -1, 52, 2418, -1, "", 1);// 102
			AddComplexComponent( (BaseAddon) this, 2170, 1, 0, 57, 2418, -1, "", 1);// 103
			AddComplexComponent( (BaseAddon) this, 1848, 1, 0, 52, 2418, -1, "", 1);// 104
			AddComplexComponent( (BaseAddon) this, 2172, -1, 0, 57, 2418, -1, "", 1);// 105
			AddComplexComponent( (BaseAddon) this, 1849, -1, 2, 0, 2418, -1, "", 1);// 108
			AddComplexComponent( (BaseAddon) this, 1849, 0, 2, 0, 2418, -1, "", 1);// 109
			AddComplexComponent( (BaseAddon) this, 464, 0, -2, 7, 2418, -1, "", 1);// 110
			AddComplexComponent( (BaseAddon) this, 13854, 0, -1, 63, 2418, -1, "", 1);// 111
			AddComplexComponent( (BaseAddon) this, 1202, 3, 0, 62, 2418, -1, "", 1);// 112
			AddComplexComponent( (BaseAddon) this, 1201, 4, 0, 62, 2418, -1, "", 1);// 113
			AddComplexComponent( (BaseAddon) this, 1848, 2, -1, 52, 2418, -1, "", 1);// 114
			AddComplexComponent( (BaseAddon) this, 1201, -3, 0, 62, 2418, -1, "", 1);// 115
			AddComplexComponent( (BaseAddon) this, 1202, -4, 0, 62, 2418, -1, "", 1);// 116
			AddComplexComponent( (BaseAddon) this, 18174, 0, 1, 30, 1177, -1, "", 1);// 117
			AddComplexComponent( (BaseAddon) this, 1203, 4, -1, 62, 2418, -1, "", 1);// 118
			AddComplexComponent( (BaseAddon) this, 1204, -4, -1, 62, 2418, -1, "", 1);// 119
			AddComplexComponent( (BaseAddon) this, 1204, 3, -1, 62, 2418, -1, "", 1);// 120
			AddComplexComponent( (BaseAddon) this, 1203, -3, -1, 62, 2418, -1, "", 1);// 121
			AddComplexComponent( (BaseAddon) this, 1848, 2, -1, 0, 2418, -1, "", 1);// 122
			AddComplexComponent( (BaseAddon) this, 16660, 1, -2, 29, 2418, -1, "", 1);// 123
			AddComplexComponent( (BaseAddon) this, 1848, -4, -1, 0, 2418, -1, "", 1);// 124
			AddComplexComponent( (BaseAddon) this, 1848, 2, 0, 52, 2418, -1, "", 1);// 125
			AddComplexComponent( (BaseAddon) this, 464, -1, -2, 7, 2418, -1, "", 1);// 126
			AddComplexComponent( (BaseAddon) this, 1848, -1, -1, 52, 2418, -1, "", 1);// 127
			AddComplexComponent( (BaseAddon) this, 16660, -1, -2, 29, 2418, -1, "", 1);// 128
			AddComplexComponent( (BaseAddon) this, 42331, 3, -1, 6, 2418, -1, "", 1);// 129
			AddComplexComponent( (BaseAddon) this, 1973, -4, 0, 57, 2418, -1, "", 1);// 130
			AddComplexComponent( (BaseAddon) this, 1973, -4, -1, 57, 2418, -1, "", 1);// 131
			AddComplexComponent( (BaseAddon) this, 1848, -3, 0, 57, 2418, -1, "", 1);// 132
			AddComplexComponent( (BaseAddon) this, 1848, 0, -1, 58, 2418, -1, "", 1);// 133
			AddComplexComponent( (BaseAddon) this, 1972, 4, 0, 57, 2418, -1, "", 1);// 134
			AddComplexComponent( (BaseAddon) this, 1972, 4, -1, 57, 2418, -1, "", 1);// 135
			AddComplexComponent( (BaseAddon) this, 16667, 3, 1, 13, 2418, -1, "", 1);// 136
			AddComplexComponent( (BaseAddon) this, 16660, 0, 0, 29, 2418, -1, "", 1);// 137
			AddComplexComponent( (BaseAddon) this, 1848, -1, -1, 0, 2418, -1, "", 1);// 138
			AddComplexComponent( (BaseAddon) this, 1848, 0, 0, 0, 2418, -1, "", 1);// 139
			AddComplexComponent( (BaseAddon) this, 25520, 0, 1, 32, 1923, -1, "Clock Face", 1);// 140
			AddComplexComponent( (BaseAddon) this, 1854, 3, 2, 0, 2418, -1, "", 1);// 141
			AddComplexComponent( (BaseAddon) this, 1848, 0, -1, 0, 2418, -1, "", 1);// 142

		}

		public TwoStoryGrandfatherClockSouthAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class TwoStoryGrandfatherClockSouthAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new TwoStoryGrandfatherClockSouthAddon();
			}
		}

		[Constructable]
		public TwoStoryGrandfatherClockSouthAddonDeed()
		{
			Name = "TwoStoryGrandfatherClockSouth";
		}

		public TwoStoryGrandfatherClockSouthAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}