
////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class MarbleGazeboAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {11534, 0, 0, 70}, {6023, -1, -1, 70}, {3245, 0, -1, 68}// 1	2	3	
			, {3244, -1, 2, 67}, {3244, -1, -1, 68}, {6946, 1, -1, 68}// 4	5	6	
			, {6943, 1, -2, 6}, {6943, 1, 1, 68}, {6944, 2, -1, 62}// 7	8	9	
			, {6944, -1, 1, 68}, {6944, -2, 3, 3}, {6947, 3, -2, 3}// 10	11	12	
			, {3144, 2, -2, 70}, {3144, -1, -2, 69}, {3144, -2, -1, 69}// 13	14	15	
			, {3144, -2, 1, 69}, {3144, -1, 3, 69}, {3144, 1, 3, 70}// 16	17	18	
			, {3144, 3, 3, 69}, {3144, 3, 1, 69}, {3144, 3, -1, 70}// 19	20	21	
			, {3144, 4, 3, 60}, {3144, 4, 2, 60}, {3144, 4, 1, 60}// 22	23	24	
			, {3144, 4, 0, 60}, {3144, 4, -1, 60}, {3144, 3, 4, 60}// 25	26	27	
			, {3144, 2, 4, 60}, {3144, 1, 4, 60}, {3144, 0, 4, 60}// 28	29	30	
			, {3144, -1, 4, 60}, {3312, 4, 3, 35}, {3308, 3, 4, 35}// 31	32	33	
			, {3312, 4, 3, 50}, {3312, 4, 2, 50}, {3311, 4, 1, 50}// 34	35	36	
			, {3311, 4, 0, 50}, {3312, 4, -1, 50}, {3311, 4, -2, 50}// 37	38	39	
			, {3311, 4, -2, 35}, {3307, 3, 4, 50}, {3308, 2, 4, 50}// 40	42	43	
			, {3308, 1, 4, 50}, {3308, 0, 4, 50}, {3307, -1, 4, 50}// 44	45	46	
			, {3308, -2, 4, 50}, {3307, -2, 4, 35}, {19242, 2, -2, 64}// 47	48	74	
			, {19242, 1, -2, 64}, {19242, 0, -2, 64}, {19242, -1, -2, 64}// 75	76	77	
			, {19242, -2, -2, 64}, {19237, -2, -1, 65}, {19237, -2, 0, 64}// 78	79	80	
			, {19237, -2, 1, 64}, {19237, -2, 2, 64}, {19238, -2, 3, 64}// 81	82	83	
			, {19242, -1, 3, 64}, {19242, 0, 3, 64}, {19242, 1, 3, 64}// 84	85	86	
			, {19242, 2, 3, 64}, {19235, 3, -2, 64}, {19237, 3, -1, 64}// 87	88	89	
			, {19237, 3, 0, 64}, {19237, 3, 1, 64}, {19237, 3, 2, 64}// 90	91	92	
			, {19239, 3, 3, 64}, {16828, 2, 2, 6}, {16825, 2, 1, 6}// 93	95	96	
			, {16825, 2, 0, 6}, {16825, 2, -1, 6}, {16823, 2, -2, 6}// 97	98	99	
			, {16827, 1, 2, 6}, {16818, 1, 1, 6}, {16818, 1, 0, 6}// 100	101	102	
			, {16818, 1, -1, 6}, {16822, 1, -2, 6}, {16827, 0, 2, 6}// 103	104	105	
			, {16818, 0, 1, 6}, {16818, 0, 0, 6}, {16818, 0, -1, 6}// 106	107	108	
			, {16822, 0, -2, 6}, {16827, -1, 2, 6}, {16818, -1, 1, 6}// 109	110	111	
			, {16818, -1, 0, 6}, {16818, -1, -1, 6}, {16822, -1, -2, 6}// 112	113	114	
			, {16826, -2, 2, 6}, {16824, -2, 1, 6}, {16824, -2, 0, 6}// 115	116	117	
			, {16824, -2, -1, 6}, {16821, -2, -2, 6}, {1801, -2, -2, 50}// 118	119	129	
			, {1801, 1, 0, 60}, {1801, 0, 1, 60}, {1801, 0, 0, 60}// 139	142	143	
			, {1801, 0, -1, 60}, {1801, -1, 0, 60}, {1801, 1, 1, 55}// 144	149	159	
			, {1801, 0, 1, 55}, {1801, 0, 0, 55}, {1801, 1, 0, 55}// 160	161	162	
			, {1801, 1, -1, 55}, {1801, 0, -1, 55}, {1801, 1, -2, 55}// 165	166	168	
			, {1801, 0, -2, 55}, {1801, -1, -2, 55}, {1801, -1, 0, 55}// 169	170	171	
			, {1801, -1, 1, 55}, {1801, -2, 1, 55}, {1801, -2, 0, 55}// 172	175	176	
			, {1801, -2, -1, 55}, {1801, 0, 0, 50}, {1801, 1, 0, 50}// 177	178	179	
			, {1801, 1, 1, 50}, {1801, 0, 1, 50}, {1801, 0, 2, 50}// 180	181	182	
			, {1801, 1, 2, 50}, {1801, 2, 1, 50}, {1801, 2, 2, 50}// 183	184	185	
			, {1801, 2, 0, 50}, {1801, 2, -1, 50}, {1801, 0, -1, 50}// 186	187	188	
			, {1801, 1, -1, 50}, {1801, 2, -2, 50}, {1801, 1, -2, 50}// 189	190	191	
			, {1801, 0, -2, 50}, {1801, -1, -1, 50}, {1801, -1, -1, 55}// 192	193	194	
			, {1801, -1, -2, 50}, {1801, -1, 0, 50}, {1801, -1, 1, 50}// 195	196	197	
			, {1801, -1, 2, 50}, {1801, -2, 2, 50}, {1801, -2, 1, 50}// 198	199	200	
			, {1801, -2, 0, 50}, {1801, -2, -1, 50}, {1801, -2, -2, 50}// 201	202	203	
					};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new MarbleGazeboAddonDeed();
			}
		}

		[ Constructable ]
		public MarbleGazeboAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 1803, 3, -2, 0, 1150, -1, "", 1);// 41
			AddComplexComponent( (BaseAddon) this, 41252, -2, 2, 69, 341, -1, "", 1);// 49
			AddComplexComponent( (BaseAddon) this, 41186, -2, 1, 69, 341, -1, "", 1);// 50
			AddComplexComponent( (BaseAddon) this, 41186, -2, 0, 70, 341, -1, "", 1);// 51
			AddComplexComponent( (BaseAddon) this, 41185, -2, -1, 69, 341, -1, "", 1);// 52
			AddComplexComponent( (BaseAddon) this, 41186, 3, 2, 70, 341, -1, "", 1);// 53
			AddComplexComponent( (BaseAddon) this, 41185, 3, 1, 69, 341, -1, "", 1);// 54
			AddComplexComponent( (BaseAddon) this, 41186, 3, 0, 70, 341, -1, "", 1);// 55
			AddComplexComponent( (BaseAddon) this, 41252, 3, -1, 69, 341, -1, "", 1);// 56
			AddComplexComponent( (BaseAddon) this, 41186, 3, -2, 70, 341, -1, "", 1);// 57
			AddComplexComponent( (BaseAddon) this, 41185, 2, -2, 69, 341, -1, "", 1);// 58
			AddComplexComponent( (BaseAddon) this, 41186, 1, -2, 70, 341, -1, "", 1);// 59
			AddComplexComponent( (BaseAddon) this, 41252, 0, -2, 69, 341, -1, "", 1);// 60
			AddComplexComponent( (BaseAddon) this, 41186, -1, -2, 70, 341, -1, "", 1);// 61
			AddComplexComponent( (BaseAddon) this, 41186, -2, -2, 70, 341, -1, "", 1);// 62
			AddComplexComponent( (BaseAddon) this, 41186, 3, 3, 70, 341, -1, "", 1);// 63
			AddComplexComponent( (BaseAddon) this, 41185, 2, 3, 69, 341, -1, "", 1);// 64
			AddComplexComponent( (BaseAddon) this, 41252, 1, 3, 69, 341, -1, "", 1);// 65
			AddComplexComponent( (BaseAddon) this, 41185, 0, 3, 69, 341, -1, "", 1);// 66
			AddComplexComponent( (BaseAddon) this, 41185, -1, 3, 69, 341, -1, "", 1);// 67
			AddComplexComponent( (BaseAddon) this, 41186, -2, 3, 70, 341, -1, "", 1);// 68
			AddComplexComponent( (BaseAddon) this, 40611, 0, -1, 15, 341, -1, "", 1);// 69
			AddComplexComponent( (BaseAddon) this, 40611, 0, 2, 15, 341, -1, "", 1);// 70
			AddComplexComponent( (BaseAddon) this, 40612, 2, -2, 8, 341, -1, "", 1);// 71
			AddComplexComponent( (BaseAddon) this, 40612, -2, -2, 8, 341, -1, "", 1);// 72
			AddComplexComponent( (BaseAddon) this, 40612, -2, 2, 8, 341, -1, "", 1);// 73
			AddComplexComponent( (BaseAddon) this, 7619, 0, 1, 8, 1154, -1, "", 1);// 94
			AddComplexComponent( (BaseAddon) this, 1801, 0, 0, 65, 1150, -1, "", 1);// 120
			AddComplexComponent( (BaseAddon) this, 1802, 0, 1, 65, 1150, -1, "", 1);// 121
			AddComplexComponent( (BaseAddon) this, 1804, 0, -1, 65, 1150, -1, "", 1);// 122
			AddComplexComponent( (BaseAddon) this, 1805, -1, 0, 65, 1150, -1, "", 1);// 123
			AddComplexComponent( (BaseAddon) this, 1803, 1, 0, 65, 1150, -1, "", 1);// 124
			AddComplexComponent( (BaseAddon) this, 1812, -1, 1, 65, 1150, -1, "", 1);// 125
			AddComplexComponent( (BaseAddon) this, 1811, 1, 1, 65, 1150, -1, "", 1);// 126
			AddComplexComponent( (BaseAddon) this, 1813, 1, -1, 65, 1150, -1, "", 1);// 127
			AddComplexComponent( (BaseAddon) this, 1810, -1, -1, 65, 1150, -1, "", 1);// 128
			AddComplexComponent( (BaseAddon) this, 1810, -2, -2, 60, 1150, -1, "", 1);// 130
			AddComplexComponent( (BaseAddon) this, 1813, 2, -2, 60, 1150, -1, "", 1);// 131
			AddComplexComponent( (BaseAddon) this, 1812, -2, 2, 60, 1150, -1, "", 1);// 132
			AddComplexComponent( (BaseAddon) this, 1811, 2, 2, 60, 1150, -1, "", 1);// 133
			AddComplexComponent( (BaseAddon) this, 1803, 2, 1, 60, 1150, -1, "", 1);// 134
			AddComplexComponent( (BaseAddon) this, 1803, 2, 0, 60, 1150, -1, "", 1);// 135
			AddComplexComponent( (BaseAddon) this, 1803, 2, -1, 60, 1150, -1, "", 1);// 136
			AddComplexComponent( (BaseAddon) this, 1802, 1, 2, 60, 1150, -1, "", 1);// 137
			AddComplexComponent( (BaseAddon) this, 1801, 1, 1, 60, 1150, -1, "", 1);// 138
			AddComplexComponent( (BaseAddon) this, 1801, 1, -1, 60, 1150, -1, "", 1);// 140
			AddComplexComponent( (BaseAddon) this, 1804, 1, -2, 60, 1150, -1, "", 1);// 141
			AddComplexComponent( (BaseAddon) this, 1804, 0, -2, 60, 1150, -1, "", 1);// 145
			AddComplexComponent( (BaseAddon) this, 1802, 0, 2, 60, 1150, -1, "", 1);// 146
			AddComplexComponent( (BaseAddon) this, 1802, -1, 2, 60, 1150, -1, "", 1);// 147
			AddComplexComponent( (BaseAddon) this, 1801, -1, 1, 60, 1150, -1, "", 1);// 148
			AddComplexComponent( (BaseAddon) this, 1801, -1, -1, 60, 1150, -1, "", 1);// 150
			AddComplexComponent( (BaseAddon) this, 1804, -1, -2, 60, 1150, -1, "", 1);// 151
			AddComplexComponent( (BaseAddon) this, 1805, -2, 1, 60, 1150, -1, "", 1);// 152
			AddComplexComponent( (BaseAddon) this, 1805, -2, 0, 60, 1150, -1, "", 1);// 153
			AddComplexComponent( (BaseAddon) this, 1805, -2, -1, 60, 1150, -1, "", 1);// 154
			AddComplexComponent( (BaseAddon) this, 1801, 2, 2, 55, 1150, -1, "", 1);// 155
			AddComplexComponent( (BaseAddon) this, 1801, 1, 2, 55, 1150, -1, "", 1);// 156
			AddComplexComponent( (BaseAddon) this, 1801, 0, 2, 55, 1150, -1, "", 1);// 157
			AddComplexComponent( (BaseAddon) this, 1801, 2, 1, 55, 1150, -1, "", 1);// 158
			AddComplexComponent( (BaseAddon) this, 1801, 2, 0, 55, 1150, -1, "", 1);// 163
			AddComplexComponent( (BaseAddon) this, 1801, 2, -1, 55, 1150, -1, "", 1);// 164
			AddComplexComponent( (BaseAddon) this, 1801, 2, -2, 55, 1150, -1, "", 1);// 167
			AddComplexComponent( (BaseAddon) this, 1801, -1, 2, 55, 1150, -1, "", 1);// 173
			AddComplexComponent( (BaseAddon) this, 1801, -2, 2, 55, 1150, -1, "", 1);// 174
			AddComplexComponent( (BaseAddon) this, 16765, -3, 0, 50, 1150, -1, "", 1);// 204
			AddComplexComponent( (BaseAddon) this, 16768, 0, -3, 50, 1150, -1, "", 1);// 205
			AddComplexComponent( (BaseAddon) this, 16772, -1, -3, 50, 1150, -1, "", 1);// 206
			AddComplexComponent( (BaseAddon) this, 16772, 2, -3, 50, 1150, -1, "", 1);// 207
			AddComplexComponent( (BaseAddon) this, 16770, 1, -3, 50, 1150, -1, "", 1);// 208
			AddComplexComponent( (BaseAddon) this, 16770, -2, -3, 50, 1150, -1, "", 1);// 209
			AddComplexComponent( (BaseAddon) this, 16764, -3, -3, 50, 1150, -1, "", 1);// 210
			AddComplexComponent( (BaseAddon) this, 16771, -3, -1, 50, 1150, -1, "", 1);// 211
			AddComplexComponent( (BaseAddon) this, 16771, -3, 2, 50, 1150, -1, "", 1);// 212
			AddComplexComponent( (BaseAddon) this, 16773, -3, -2, 50, 1150, -1, "", 1);// 213
			AddComplexComponent( (BaseAddon) this, 16773, -3, 1, 50, 1150, -1, "", 1);// 214
			AddComplexComponent( (BaseAddon) this, 16765, 3, 0, 50, 1150, -1, "", 1);// 215
			AddComplexComponent( (BaseAddon) this, 16772, 0, 3, 50, 1150, -1, "", 1);// 216
			AddComplexComponent( (BaseAddon) this, 16769, 3, -3, 50, 1150, -1, "", 1);// 217
			AddComplexComponent( (BaseAddon) this, 16767, -3, 3, 50, 1150, -1, "", 1);// 218
			AddComplexComponent( (BaseAddon) this, 16770, 1, 3, 50, 1150, -1, "", 1);// 219
			AddComplexComponent( (BaseAddon) this, 16770, -2, 3, 50, 1150, -1, "", 1);// 220
			AddComplexComponent( (BaseAddon) this, 16772, -1, 3, 50, 1150, -1, "", 1);// 221
			AddComplexComponent( (BaseAddon) this, 16772, 2, 3, 50, 1150, -1, "", 1);// 222
			AddComplexComponent( (BaseAddon) this, 16773, 3, 1, 50, 1150, -1, "", 1);// 223
			AddComplexComponent( (BaseAddon) this, 16773, 3, -2, 50, 1150, -1, "", 1);// 224
			AddComplexComponent( (BaseAddon) this, 16771, 3, -1, 50, 1150, -1, "", 1);// 225
			AddComplexComponent( (BaseAddon) this, 16771, 3, 2, 50, 1150, -1, "", 1);// 226
			AddComplexComponent( (BaseAddon) this, 16766, 3, 3, 50, 1150, -1, "", 1);// 227
			AddComplexComponent( (BaseAddon) this, 7618, 0, -1, 8, 1154, -1, "", 1);// 228
			AddComplexComponent( (BaseAddon) this, 7619, 0, 0, 8, 1154, -1, "", 1);// 229
			AddComplexComponent( (BaseAddon) this, 7617, 0, 2, 8, 1154, -1, "", 1);// 230
			AddComplexComponent( (BaseAddon) this, 7630, 1, -1, 6, 1154, -1, "", 1);// 231
			AddComplexComponent( (BaseAddon) this, 7630, -2, -1, 6, 1154, -1, "", 1);// 232
			AddComplexComponent( (BaseAddon) this, 7631, 1, 0, 6, 1154, -1, "", 1);// 233
			AddComplexComponent( (BaseAddon) this, 7631, -2, 0, 6, 1154, -1, "", 1);// 234
			AddComplexComponent( (BaseAddon) this, 7629, 1, 1, 6, 1154, -1, "", 1);// 235
			AddComplexComponent( (BaseAddon) this, 7629, -2, 1, 6, 1154, -1, "", 1);// 236
			AddComplexComponent( (BaseAddon) this, 1300, 3, 3, 50, 1150, -1, "", 1);// 237
			AddComplexComponent( (BaseAddon) this, 1300, 3, 2, 50, 1150, -1, "", 1);// 238
			AddComplexComponent( (BaseAddon) this, 1300, 3, 1, 50, 1150, -1, "", 1);// 239
			AddComplexComponent( (BaseAddon) this, 1300, 3, 0, 50, 1150, -1, "", 1);// 240
			AddComplexComponent( (BaseAddon) this, 1300, 3, -1, 50, 1150, -1, "", 1);// 241
			AddComplexComponent( (BaseAddon) this, 1300, 3, -2, 50, 1150, -1, "", 1);// 242
			AddComplexComponent( (BaseAddon) this, 1300, 2, 3, 50, 1150, -1, "", 1);// 243
			AddComplexComponent( (BaseAddon) this, 1300, 2, 2, 50, 1150, -1, "", 1);// 244
			AddComplexComponent( (BaseAddon) this, 1300, 2, 1, 50, 1150, -1, "", 1);// 245
			AddComplexComponent( (BaseAddon) this, 1300, 2, 0, 50, 1150, -1, "", 1);// 246
			AddComplexComponent( (BaseAddon) this, 1300, 2, -1, 50, 1150, -1, "", 1);// 247
			AddComplexComponent( (BaseAddon) this, 1300, 2, -2, 50, 1150, -1, "", 1);// 248
			AddComplexComponent( (BaseAddon) this, 1300, 1, 3, 50, 1150, -1, "", 1);// 249
			AddComplexComponent( (BaseAddon) this, 1300, 1, 2, 50, 1150, -1, "", 1);// 250
			AddComplexComponent( (BaseAddon) this, 1300, 1, 1, 50, 1150, -1, "", 1);// 251
			AddComplexComponent( (BaseAddon) this, 1300, 1, 0, 50, 1150, -1, "", 1);// 252
			AddComplexComponent( (BaseAddon) this, 1300, 1, -1, 50, 1150, -1, "", 1);// 253
			AddComplexComponent( (BaseAddon) this, 1300, 1, -2, 50, 1150, -1, "", 1);// 254
			AddComplexComponent( (BaseAddon) this, 1300, 0, 3, 50, 1150, -1, "", 1);// 255
			AddComplexComponent( (BaseAddon) this, 1300, 0, 2, 50, 1150, -1, "", 1);// 256
			AddComplexComponent( (BaseAddon) this, 1300, 0, 1, 50, 1150, -1, "", 1);// 257
			AddComplexComponent( (BaseAddon) this, 1300, 0, 0, 50, 1150, -1, "", 1);// 258
			AddComplexComponent( (BaseAddon) this, 1300, 0, -1, 50, 1150, -1, "", 1);// 259
			AddComplexComponent( (BaseAddon) this, 1300, 0, -2, 50, 1150, -1, "", 1);// 260
			AddComplexComponent( (BaseAddon) this, 1300, -1, 3, 50, 1150, -1, "", 1);// 261
			AddComplexComponent( (BaseAddon) this, 1300, -1, 2, 50, 1150, -1, "", 1);// 262
			AddComplexComponent( (BaseAddon) this, 1300, -1, 1, 50, 1150, -1, "", 1);// 263
			AddComplexComponent( (BaseAddon) this, 1300, -1, 0, 50, 1150, -1, "", 1);// 264
			AddComplexComponent( (BaseAddon) this, 1300, -1, -1, 50, 1150, -1, "", 1);// 265
			AddComplexComponent( (BaseAddon) this, 1300, -1, -2, 50, 1150, -1, "", 1);// 266
			AddComplexComponent( (BaseAddon) this, 1300, -2, 3, 50, 1150, -1, "", 1);// 267
			AddComplexComponent( (BaseAddon) this, 1300, -2, 2, 50, 1150, -1, "", 1);// 268
			AddComplexComponent( (BaseAddon) this, 1300, -2, 1, 50, 1150, -1, "", 1);// 269
			AddComplexComponent( (BaseAddon) this, 1300, -2, 0, 50, 1150, -1, "", 1);// 270
			AddComplexComponent( (BaseAddon) this, 1300, -2, -1, 50, 1150, -1, "", 1);// 271
			AddComplexComponent( (BaseAddon) this, 1300, -2, -2, 50, 1150, -1, "", 1);// 272
			AddComplexComponent( (BaseAddon) this, 278, 3, -2, 30, 1150, -1, "", 1);// 273
			AddComplexComponent( (BaseAddon) this, 278, -3, -2, 30, 1150, -1, "", 1);// 274
			AddComplexComponent( (BaseAddon) this, 276, -2, -3, 30, 1150, -1, "", 1);// 275
			AddComplexComponent( (BaseAddon) this, 257, -3, -3, 30, 1150, -1, "", 1);// 276
			AddComplexComponent( (BaseAddon) this, 276, -2, 3, 30, 1150, -1, "", 1);// 277
			AddComplexComponent( (BaseAddon) this, 277, -3, 3, 30, 1150, -1, "", 1);// 278
			AddComplexComponent( (BaseAddon) this, 275, 3, -3, 30, 1150, -1, "", 1);// 279
			AddComplexComponent( (BaseAddon) this, 274, 3, 3, 30, 1150, -1, "", 1);// 280
			AddComplexComponent( (BaseAddon) this, 283, 3, -3, 8, 1150, -1, "", 1);// 281
			AddComplexComponent( (BaseAddon) this, 283, 3, 3, 8, 1150, -1, "", 1);// 282
			AddComplexComponent( (BaseAddon) this, 283, -3, 3, 8, 1150, -1, "", 1);// 283
			AddComplexComponent( (BaseAddon) this, 283, -3, -3, 8, 1150, -1, "", 1);// 284
			AddComplexComponent( (BaseAddon) this, 1801, 3, -3, 0, 1150, -1, "", 1);// 285
			AddComplexComponent( (BaseAddon) this, 1801, -3, -3, 0, 1150, -1, "", 1);// 286
			AddComplexComponent( (BaseAddon) this, 1801, -3, 3, 0, 1150, -1, "", 1);// 287
			AddComplexComponent( (BaseAddon) this, 1801, 3, 3, 0, 1150, -1, "", 1);// 288
			AddComplexComponent( (BaseAddon) this, 1802, 2, 3, 0, 1150, -1, "", 1);// 289
			AddComplexComponent( (BaseAddon) this, 1802, 1, 3, 0, 1150, -1, "", 1);// 290
			AddComplexComponent( (BaseAddon) this, 1802, 0, 3, 0, 1150, -1, "", 1);// 291
			AddComplexComponent( (BaseAddon) this, 1802, -1, 3, 0, 1150, -1, "", 1);// 292
			AddComplexComponent( (BaseAddon) this, 1802, -2, 3, 0, 1150, -1, "", 1);// 293
			AddComplexComponent( (BaseAddon) this, 1804, 2, -3, 0, 1150, -1, "", 1);// 294
			AddComplexComponent( (BaseAddon) this, 1805, -3, 2, 0, 1150, -1, "", 1);// 295
			AddComplexComponent( (BaseAddon) this, 1805, -3, 1, 0, 1150, -1, "", 1);// 296
			AddComplexComponent( (BaseAddon) this, 1805, -3, 0, 0, 1150, -1, "", 1);// 297
			AddComplexComponent( (BaseAddon) this, 1805, -3, -1, 0, 1150, -1, "", 1);// 298
			AddComplexComponent( (BaseAddon) this, 1805, -3, -2, 0, 1150, -1, "", 1);// 299
			AddComplexComponent( (BaseAddon) this, 1804, -2, -3, 0, 1150, -1, "", 1);// 300
			AddComplexComponent( (BaseAddon) this, 1804, -1, -3, 0, 1150, -1, "", 1);// 301
			AddComplexComponent( (BaseAddon) this, 1804, 0, -3, 0, 1150, -1, "", 1);// 302
			AddComplexComponent( (BaseAddon) this, 1804, 1, -3, 0, 1150, -1, "", 1);// 303
			AddComplexComponent( (BaseAddon) this, 1803, 3, 2, 0, 1150, -1, "", 1);// 304
			AddComplexComponent( (BaseAddon) this, 1803, 3, 1, 0, 1150, -1, "", 1);// 305
			AddComplexComponent( (BaseAddon) this, 1803, 3, 0, 0, 1150, -1, "", 1);// 306
			AddComplexComponent( (BaseAddon) this, 1803, 3, -1, 0, 1150, -1, "", 1);// 307
			AddComplexComponent( (BaseAddon) this, 1801, 1, 1, 0, 1150, -1, "", 1);// 308
			AddComplexComponent( (BaseAddon) this, 1801, 0, 1, 0, 1150, -1, "", 1);// 309
			AddComplexComponent( (BaseAddon) this, 1801, -1, 1, 0, 1150, -1, "", 1);// 310
			AddComplexComponent( (BaseAddon) this, 1801, 1, 0, 0, 1150, -1, "", 1);// 311
			AddComplexComponent( (BaseAddon) this, 1801, 1, -1, 0, 1150, -1, "", 1);// 312
			AddComplexComponent( (BaseAddon) this, 1801, 0, 0, 0, 1150, -1, "", 1);// 313
			AddComplexComponent( (BaseAddon) this, 1801, 0, -1, 0, 1150, -1, "", 1);// 314
			AddComplexComponent( (BaseAddon) this, 1801, -1, 0, 0, 1150, -1, "", 1);// 315
			AddComplexComponent( (BaseAddon) this, 1801, -1, -1, 0, 1150, -1, "", 1);// 316
			AddComplexComponent( (BaseAddon) this, 1801, 1, 2, 0, 1150, -1, "", 1);// 317
			AddComplexComponent( (BaseAddon) this, 1801, 0, 2, 0, 1150, -1, "", 1);// 318
			AddComplexComponent( (BaseAddon) this, 1801, -1, 2, 0, 1150, -1, "", 1);// 319
			AddComplexComponent( (BaseAddon) this, 1801, 2, 2, 0, 1150, -1, "", 1);// 320
			AddComplexComponent( (BaseAddon) this, 1801, 2, 1, 0, 1150, -1, "", 1);// 321
			AddComplexComponent( (BaseAddon) this, 1801, 2, 0, 0, 1150, -1, "", 1);// 322
			AddComplexComponent( (BaseAddon) this, 1801, 2, -1, 0, 1150, -1, "", 1);// 323
			AddComplexComponent( (BaseAddon) this, 1801, 2, -2, 0, 1150, -1, "", 1);// 324
			AddComplexComponent( (BaseAddon) this, 1801, 1, -2, 0, 1150, -1, "", 1);// 325
			AddComplexComponent( (BaseAddon) this, 1801, 0, -2, 0, 1150, -1, "", 1);// 326
			AddComplexComponent( (BaseAddon) this, 1801, -1, -2, 0, 1150, -1, "", 1);// 327
			AddComplexComponent( (BaseAddon) this, 1801, -2, -2, 0, 1150, -1, "", 1);// 328
			AddComplexComponent( (BaseAddon) this, 1801, -2, -1, 0, 1150, -1, "", 1);// 329
			AddComplexComponent( (BaseAddon) this, 1801, -2, 0, 0, 1150, -1, "", 1);// 330
			AddComplexComponent( (BaseAddon) this, 1801, -2, 1, 0, 1150, -1, "", 1);// 331
			AddComplexComponent( (BaseAddon) this, 1801, -2, 2, 0, 1150, -1, "", 1);// 332

		}

		public MarbleGazeboAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class MarbleGazeboAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new MarbleGazeboAddon();
			}
		}

		[Constructable]
		public MarbleGazeboAddonDeed()
		{
			Name = "MarbleGazebo";
		}

		public MarbleGazeboAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}