
////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class LargeCheeryWoodTreeAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {9337, 4, -2, 40}, {9340, 3, -3, 36}, {9338, 2, -2, 52}// 1	2	3	
			, {9339, 2, -1, 36}, {9340, 2, -1, 48}, {9337, -3, 3, 29}// 4	5	8	
			, {9337, 0, 1, 36}, {9339, -2, 2, 29}, {9339, 1, 0, 49}// 9	10	11	
			, {9339, 0, 2, 56}, {9339, -2, 3, 51}, {9340, 1, -1, 61}// 12	13	14	
			, {9340, 0, 2, 70}// 15	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new LargeCheeryWoodTreeAddonDeed();
			}
		}

		[ Constructable ]
		public LargeCheeryWoodTreeAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 3388, -1, 1, 32, 2418, -1, "", 1);// 6
			AddComplexComponent( (BaseAddon) this, 3387, 1, 0, 35, 2418, -1, "", 1);// 7
			AddComplexComponent( (BaseAddon) this, 3418, 1, -1, 0, 2418, -1, "", 1);// 16
			AddComplexComponent( (BaseAddon) this, 3416, -1, 1, 0, 2418, -1, "", 1);// 17
			AddComplexComponent( (BaseAddon) this, 3417, 0, 0, 0, 2418, -1, "", 1);// 18

		}

		public LargeCheeryWoodTreeAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class LargeCheeryWoodTreeAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new LargeCheeryWoodTreeAddon();
			}
		}

		[Constructable]
		public LargeCheeryWoodTreeAddonDeed()
		{
			Name = "LargeCheeryWoodTree";
		}

		public LargeCheeryWoodTreeAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}