
////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class LOTRMallornTreeAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {3264, -1, 0, 0}, {3349, -3, 0, 0}, {42590, -2, -2, 9}// 1	2	5	
			, {42596, -3, 0, 14}, {42592, -3, -1, 31}, {42595, -3, 3, 37}// 6	7	8	
			, {42596, 3, -2, 63}, {42596, -2, 3, 63}, {42596, 3, 0, 84}// 9	10	11	
			, {42596, 0, 3, 85}, {42596, 1, 1, 82}, {3205, 0, -3, 0}// 12	13	17	
			, {42596, 0, -3, 19}, {42592, -1, -3, 41}, {42595, 3, -3, 41}// 18	19	20	
					};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new LOTRMallornTreeAddonDeed();
			}
		}

		[ Constructable ]
		public LOTRMallornTreeAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 3387, 0, -1, 37, 1150, -1, "", 1);// 3
			AddComplexComponent( (BaseAddon) this, 3388, -2, 0, 34, 1150, -1, "", 1);// 4
			AddComplexComponent( (BaseAddon) this, 3439, -2, 0, 0, 1150, -1, "", 1);// 14
			AddComplexComponent( (BaseAddon) this, 3441, 0, -2, 0, 1150, -1, "", 1);// 15
			AddComplexComponent( (BaseAddon) this, 3440, -1, -1, 0, 1150, -1, "", 1);// 16

		}

		public LOTRMallornTreeAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class LOTRMallornTreeAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new LOTRMallornTreeAddon();
			}
		}

		[Constructable]
		public LOTRMallornTreeAddonDeed()
		{
			Name = "LOTRMallornTree";
		}

		public LOTRMallornTreeAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}