
////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class MarketTentEastMagentaAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {43885, 4, 7, 22}, {1313, 4, 7, 0}, {1403, 4, 6, 0}// 1	4	5	
			, {22, 3, 7, 22}, {22, 2, 7, 22}, {22, 1, 7, 22}// 9	10	11	
			, {22, 0, 7, 22}, {22, -1, 7, 22}, {22, -2, 7, 22}// 12	13	14	
			, {2879, 2, 7, 0}, {2879, 1, 7, 0}, {2879, 0, 7, 0}// 39	40	41	
			, {2879, -1, 7, 0}, {2879, -2, 7, 0}, {2879, -3, 6, 0}// 42	43	44	
			, {16667, 3, 7, 0}, {16667, -3, 7, 0}, {1313, 2, 7, 0}// 45	46	47	
			, {1403, 2, 6, 0}, {1403, 1, 7, 0}, {1313, 1, 6, 0}// 48	49	50	
			, {1313, 0, 7, 0}, {1403, 0, 6, 0}, {1403, -1, 7, 0}// 51	52	53	
			, {1313, -1, 6, 0}, {1313, -2, 7, 0}, {1403, -2, 6, 0}// 54	55	56	
			, {1403, -3, 7, 0}, {1313, -3, 6, 0}, {1403, 3, 7, 0}// 57	58	59	
			, {1313, 3, 6, 0}, {43885, 4, -6, 22}, {1313, 4, 5, 0}// 60	61	64	
			, {1403, 4, 4, 0}, {1313, 4, 3, 0}, {1403, 4, 2, 0}// 65	66	67	
			, {1313, 4, 1, 0}, {1403, 4, 0, 0}, {1313, 4, -1, 0}// 68	69	70	
			, {1403, 4, -2, 0}, {1313, 4, -3, 0}, {1403, 4, -4, 0}// 71	72	73	
			, {1313, 4, -5, 0}, {1313, 4, -6, 0}, {1403, 2, -6, 0}// 74	75	151	
			, {1313, 1, -6, 0}, {1403, 0, -6, 0}, {1313, -1, -6, 0}// 152	153	154	
			, {1403, -2, -6, 0}, {2879, 3, -2, 0}, {2879, -3, -4, 0}// 155	156	157	
			, {2879, 0, -3, 0}, {2879, 1, -3, 0}, {2879, 2, -3, 0}// 182	183	184	
			, {2879, 3, -3, 0}, {2879, 3, -1, 0}, {2879, 3, 0, 0}// 185	186	187	
			, {2879, 3, 1, 0}, {2879, 3, 2, 0}, {2879, 3, 3, 0}// 188	189	190	
			, {2879, 0, 4, 0}, {2879, 1, 4, 0}, {2879, 2, 4, 0}// 191	192	193	
			, {2879, 3, 4, 0}, {2879, 2, -6, 0}, {2879, 1, -6, 0}// 194	195	196	
			, {2879, 0, -6, 0}, {2879, -1, -6, 0}, {2879, -2, -6, 0}// 197	198	199	
			, {2879, -3, 5, 0}, {2879, -3, 4, 0}, {2879, -3, -3, 0}// 200	201	202	
			, {2879, -3, -5, 0}, {16667, 3, -6, 0}, {16667, -3, -6, 0}// 203	204	205	
			, {1313, 2, 5, 0}, {1403, 2, 4, 0}, {1313, 2, 3, 0}// 206	207	208	
			, {1403, 2, 2, 0}, {1313, 2, 1, 0}, {1403, 2, 0, 0}// 209	210	211	
			, {1313, 2, -1, 0}, {1403, 2, -2, 0}, {1313, 2, -3, 0}// 212	213	214	
			, {1403, 2, -4, 0}, {1403, 1, 5, 0}, {1313, 1, 4, 0}// 215	216	217	
			, {1403, 1, 3, 0}, {1313, 1, 2, 0}, {1403, 1, 1, 0}// 218	219	220	
			, {1313, 1, 0, 0}, {1403, 1, -1, 0}, {1313, 1, -2, 0}// 221	222	223	
			, {1403, 1, -3, 0}, {1313, 1, -4, 0}, {1313, 0, 5, 0}// 224	225	226	
			, {1403, 0, 4, 0}, {1313, 0, 3, 0}, {1403, 0, 2, 0}// 227	228	229	
			, {1313, 0, 1, 0}, {1403, 0, 0, 0}, {1313, 0, -1, 0}// 230	231	232	
			, {1403, 0, -2, 0}, {1313, 0, -3, 0}, {1403, 0, -4, 0}// 233	234	235	
			, {1403, -1, 5, 0}, {1313, -1, 4, 0}, {1403, -1, 3, 0}// 236	237	238	
			, {1313, -1, 2, 0}, {1403, -1, 1, 0}, {1313, -1, 0, 0}// 239	240	241	
			, {1403, -1, -1, 0}, {1313, -1, -2, 0}, {1403, -1, -3, 0}// 242	243	244	
			, {1313, -1, -4, 0}, {1313, -2, 5, 0}, {1403, -2, 4, 0}// 245	246	247	
			, {1313, -2, 3, 0}, {1403, -2, 2, 0}, {1313, -2, 1, 0}// 248	249	250	
			, {1403, -2, 0, 0}, {1313, -2, -1, 0}, {1403, -2, -2, 0}// 251	252	253	
			, {1313, -2, -3, 0}, {1403, -2, -4, 0}, {1403, -3, 5, 0}// 254	255	256	
			, {1313, -3, 4, 0}, {1403, -3, 3, 0}, {1313, -3, 2, 0}// 257	258	259	
			, {1403, -3, 1, 0}, {1313, -3, 0, 0}, {1403, -3, -1, 0}// 260	261	262	
			, {1313, -3, -2, 0}, {1403, -3, -3, 0}, {1313, -3, -4, 0}// 263	264	265	
			, {1403, 3, 5, 0}, {1313, 3, 4, 0}, {1403, 3, 3, 0}// 266	267	268	
			, {1313, 3, 2, 0}, {1403, 3, 1, 0}, {1313, 3, 0, 0}// 269	270	271	
			, {1403, 3, -1, 0}, {1313, 3, -2, 0}, {1403, 3, -3, 0}// 272	273	274	
			, {1313, 3, -4, 0}, {1403, 3, -5, 0}, {1313, 2, -5, 0}// 275	276	277	
			, {1403, 1, -5, 0}, {1313, 0, -5, 0}, {1403, -1, -5, 0}// 278	279	280	
			, {1313, -2, -5, 0}, {1403, -3, -5, 0}, {13, -4, 7, 3}// 281	282	283	
			, {8, -4, 6, 3}, {9, -4, -7, 3}, {25, -4, 5, 0}// 284	285	286	
			, {25, -4, 4, 0}, {25, -4, 3, 0}, {25, -4, 2, 0}// 287	288	289	
			, {25, -4, 1, 0}, {25, -4, 0, 0}, {25, -4, -1, 0}// 290	291	292	
			, {25, -4, -2, 0}, {25, -4, -3, 0}, {25, -4, -4, 0}// 293	294	295	
			, {25, -4, -5, 0}, {8, -4, 5, 3}, {13, -4, 4, 3}// 296	297	298	
			, {13, -4, 3, 3}, {8, -4, 2, 3}, {8, -4, 1, 3}// 299	300	301	
			, {8, -4, 0, 3}, {8, -4, -1, 3}, {13, -4, -2, 3}// 302	303	304	
			, {13, -4, -3, 3}, {8, -4, -4, 3}, {8, -4, -5, 3}// 305	306	307	
			, {8, -4, -6, 3}// 308	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new MarketTentEastMagentaAddonDeed();
			}
		}

		[ Constructable ]
		public MarketTentEastMagentaAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 419, 4, 7, 12, 2418, -1, "", 1);// 2
			AddComplexComponent( (BaseAddon) this, 419, 4, 7, 4, 2418, -1, "", 1);// 3
			AddComplexComponent( (BaseAddon) this, 43294, 2, 8, 4, 0, 1, "", 1);// 6
			AddComplexComponent( (BaseAddon) this, 43294, 0, 8, 4, 0, 1, "", 1);// 7
			AddComplexComponent( (BaseAddon) this, 43294, -2, 8, 3, 0, 1, "", 1);// 8
			AddComplexComponent( (BaseAddon) this, 1562, 1, 8, 31, 1163, -1, "", 1);// 15
			AddComplexComponent( (BaseAddon) this, 1562, 1, 7, 31, 1163, -1, "", 1);// 16
			AddComplexComponent( (BaseAddon) this, 1562, 1, 6, 31, 1163, -1, "", 1);// 17
			AddComplexComponent( (BaseAddon) this, 1559, 0, 8, 31, 1163, -1, "", 1);// 18
			AddComplexComponent( (BaseAddon) this, 1559, 0, 7, 31, 1163, -1, "", 1);// 19
			AddComplexComponent( (BaseAddon) this, 1559, 0, 6, 31, 1163, -1, "", 1);// 20
			AddComplexComponent( (BaseAddon) this, 1559, -1, 8, 28, 1163, -1, "", 1);// 21
			AddComplexComponent( (BaseAddon) this, 1559, -1, 7, 28, 1163, -1, "", 1);// 22
			AddComplexComponent( (BaseAddon) this, 1559, -1, 6, 28, 1163, -1, "", 1);// 23
			AddComplexComponent( (BaseAddon) this, 1559, -2, 8, 25, 1163, -1, "", 1);// 24
			AddComplexComponent( (BaseAddon) this, 1559, -2, 7, 25, 1163, -1, "", 1);// 25
			AddComplexComponent( (BaseAddon) this, 1559, -2, 6, 25, 1163, -1, "", 1);// 26
			AddComplexComponent( (BaseAddon) this, 1571, -3, 7, 22, 1163, -1, "", 1);// 27
			AddComplexComponent( (BaseAddon) this, 1571, -3, 8, 22, 1163, -1, "", 1);// 28
			AddComplexComponent( (BaseAddon) this, 1571, -3, 6, 22, 1163, -1, "", 1);// 29
			AddComplexComponent( (BaseAddon) this, 1562, 2, 8, 28, 1163, -1, "", 1);// 30
			AddComplexComponent( (BaseAddon) this, 1562, 2, 7, 28, 1163, -1, "", 1);// 31
			AddComplexComponent( (BaseAddon) this, 1562, 2, 6, 28, 1163, -1, "", 1);// 32
			AddComplexComponent( (BaseAddon) this, 1562, 3, 8, 25, 1163, -1, "", 1);// 33
			AddComplexComponent( (BaseAddon) this, 1573, 4, 8, 22, 1163, -1, "", 1);// 34
			AddComplexComponent( (BaseAddon) this, 1562, 3, 7, 25, 1163, -1, "", 1);// 35
			AddComplexComponent( (BaseAddon) this, 1562, 3, 6, 25, 1163, -1, "", 1);// 36
			AddComplexComponent( (BaseAddon) this, 1573, 4, 7, 22, 1163, -1, "", 1);// 37
			AddComplexComponent( (BaseAddon) this, 1573, 4, 6, 22, 1163, -1, "", 1);// 38
			AddComplexComponent( (BaseAddon) this, 419, 4, -6, 12, 2418, -1, "", 1);// 62
			AddComplexComponent( (BaseAddon) this, 419, 4, -6, 4, 2418, -1, "", 1);// 63
			AddComplexComponent( (BaseAddon) this, 43294, 2, -6, 2, 0, 1, "", 1);// 76
			AddComplexComponent( (BaseAddon) this, 43294, 0, -6, 2, 0, 1, "", 1);// 77
			AddComplexComponent( (BaseAddon) this, 43294, -2, -6, 1, 0, 1, "", 1);// 78
			AddComplexComponent( (BaseAddon) this, 1562, 1, 5, 31, 1153, -1, "", 1);// 79
			AddComplexComponent( (BaseAddon) this, 1562, 1, 4, 31, 1153, -1, "", 1);// 80
			AddComplexComponent( (BaseAddon) this, 1562, 1, 3, 31, 1153, -1, "", 1);// 81
			AddComplexComponent( (BaseAddon) this, 1562, 1, 2, 31, 1163, -1, "", 1);// 82
			AddComplexComponent( (BaseAddon) this, 1562, 1, 1, 31, 1163, -1, "", 1);// 83
			AddComplexComponent( (BaseAddon) this, 1562, 1, 0, 31, 1163, -1, "", 1);// 84
			AddComplexComponent( (BaseAddon) this, 1562, 1, -1, 31, 1153, -1, "", 1);// 85
			AddComplexComponent( (BaseAddon) this, 1562, 1, -2, 31, 1153, -1, "", 1);// 86
			AddComplexComponent( (BaseAddon) this, 1562, 1, -3, 31, 1153, -1, "", 1);// 87
			AddComplexComponent( (BaseAddon) this, 1562, 1, -4, 31, 1163, -1, "", 1);// 88
			AddComplexComponent( (BaseAddon) this, 1562, 1, -5, 31, 1163, -1, "", 1);// 89
			AddComplexComponent( (BaseAddon) this, 1562, 1, -6, 31, 1163, -1, "", 1);// 90
			AddComplexComponent( (BaseAddon) this, 1559, 0, 5, 31, 1153, -1, "", 1);// 91
			AddComplexComponent( (BaseAddon) this, 1559, 0, 4, 31, 1153, -1, "", 1);// 92
			AddComplexComponent( (BaseAddon) this, 1559, 0, 3, 31, 1153, -1, "", 1);// 93
			AddComplexComponent( (BaseAddon) this, 1559, 0, 2, 31, 1163, -1, "", 1);// 94
			AddComplexComponent( (BaseAddon) this, 1559, 0, 1, 31, 1163, -1, "", 1);// 95
			AddComplexComponent( (BaseAddon) this, 1559, 0, 0, 31, 1163, -1, "", 1);// 96
			AddComplexComponent( (BaseAddon) this, 1559, 0, -1, 31, 1153, -1, "", 1);// 97
			AddComplexComponent( (BaseAddon) this, 1559, 0, -2, 31, 1153, -1, "", 1);// 98
			AddComplexComponent( (BaseAddon) this, 1559, 0, -3, 31, 1153, -1, "", 1);// 99
			AddComplexComponent( (BaseAddon) this, 1559, 0, -4, 31, 1163, -1, "", 1);// 100
			AddComplexComponent( (BaseAddon) this, 1559, 0, -5, 31, 1163, -1, "", 1);// 101
			AddComplexComponent( (BaseAddon) this, 1559, 0, -6, 31, 1163, -1, "", 1);// 102
			AddComplexComponent( (BaseAddon) this, 1559, -1, 5, 28, 1153, -1, "", 1);// 103
			AddComplexComponent( (BaseAddon) this, 1559, -1, 4, 28, 1153, -1, "", 1);// 104
			AddComplexComponent( (BaseAddon) this, 1559, -1, 3, 28, 1153, -1, "", 1);// 105
			AddComplexComponent( (BaseAddon) this, 1559, -1, 2, 28, 1163, -1, "", 1);// 106
			AddComplexComponent( (BaseAddon) this, 1559, -1, 1, 28, 1163, -1, "", 1);// 107
			AddComplexComponent( (BaseAddon) this, 1559, -1, 0, 28, 1163, -1, "", 1);// 108
			AddComplexComponent( (BaseAddon) this, 1559, -1, -1, 28, 1153, -1, "", 1);// 109
			AddComplexComponent( (BaseAddon) this, 1559, -1, -2, 28, 1153, -1, "", 1);// 110
			AddComplexComponent( (BaseAddon) this, 1559, -1, -3, 28, 1153, -1, "", 1);// 111
			AddComplexComponent( (BaseAddon) this, 1559, -1, -4, 28, 1163, -1, "", 1);// 112
			AddComplexComponent( (BaseAddon) this, 1559, -1, -5, 28, 1163, -1, "", 1);// 113
			AddComplexComponent( (BaseAddon) this, 1559, -1, -6, 28, 1163, -1, "", 1);// 114
			AddComplexComponent( (BaseAddon) this, 1559, -2, 5, 25, 1153, -1, "", 1);// 115
			AddComplexComponent( (BaseAddon) this, 1559, -2, 4, 25, 1153, -1, "", 1);// 116
			AddComplexComponent( (BaseAddon) this, 1559, -2, 3, 25, 1153, -1, "", 1);// 117
			AddComplexComponent( (BaseAddon) this, 1559, -2, 2, 25, 1163, -1, "", 1);// 118
			AddComplexComponent( (BaseAddon) this, 1559, -2, 1, 25, 1163, -1, "", 1);// 119
			AddComplexComponent( (BaseAddon) this, 1559, -2, 0, 25, 1163, -1, "", 1);// 120
			AddComplexComponent( (BaseAddon) this, 1559, -2, -1, 25, 1153, -1, "", 1);// 121
			AddComplexComponent( (BaseAddon) this, 1559, -2, -2, 25, 1153, -1, "", 1);// 122
			AddComplexComponent( (BaseAddon) this, 1559, -2, -3, 25, 1153, -1, "", 1);// 123
			AddComplexComponent( (BaseAddon) this, 1559, -2, -4, 25, 1163, -1, "", 1);// 124
			AddComplexComponent( (BaseAddon) this, 1559, -2, -5, 25, 1163, -1, "", 1);// 125
			AddComplexComponent( (BaseAddon) this, 1559, -2, -6, 25, 1163, -1, "", 1);// 126
			AddComplexComponent( (BaseAddon) this, 1571, -3, -6, 22, 1163, -1, "", 1);// 127
			AddComplexComponent( (BaseAddon) this, 1571, -3, 5, 22, 1153, -1, "", 1);// 128
			AddComplexComponent( (BaseAddon) this, 1571, -3, 4, 22, 1153, -1, "", 1);// 129
			AddComplexComponent( (BaseAddon) this, 1571, -3, 3, 22, 1153, -1, "", 1);// 130
			AddComplexComponent( (BaseAddon) this, 1571, -3, 2, 22, 1163, -1, "", 1);// 131
			AddComplexComponent( (BaseAddon) this, 1571, -3, 1, 22, 1163, -1, "", 1);// 132
			AddComplexComponent( (BaseAddon) this, 1571, -3, 0, 22, 1163, -1, "", 1);// 133
			AddComplexComponent( (BaseAddon) this, 1571, -3, -1, 22, 1153, -1, "", 1);// 134
			AddComplexComponent( (BaseAddon) this, 1571, -3, -2, 22, 1153, -1, "", 1);// 135
			AddComplexComponent( (BaseAddon) this, 1571, -3, -3, 22, 1153, -1, "", 1);// 136
			AddComplexComponent( (BaseAddon) this, 1571, -3, -4, 22, 1163, -1, "", 1);// 137
			AddComplexComponent( (BaseAddon) this, 1571, -3, -5, 22, 1163, -1, "", 1);// 138
			AddComplexComponent( (BaseAddon) this, 1562, 2, 5, 28, 1153, -1, "", 1);// 139
			AddComplexComponent( (BaseAddon) this, 1562, 2, 4, 28, 1153, -1, "", 1);// 140
			AddComplexComponent( (BaseAddon) this, 1562, 2, 3, 28, 1153, -1, "", 1);// 141
			AddComplexComponent( (BaseAddon) this, 1562, 2, 2, 28, 1163, -1, "", 1);// 142
			AddComplexComponent( (BaseAddon) this, 1562, 2, 1, 28, 1163, -1, "", 1);// 143
			AddComplexComponent( (BaseAddon) this, 1562, 2, 0, 28, 1163, -1, "", 1);// 144
			AddComplexComponent( (BaseAddon) this, 1562, 2, -1, 28, 1153, -1, "", 1);// 145
			AddComplexComponent( (BaseAddon) this, 1562, 2, -2, 28, 1153, -1, "", 1);// 146
			AddComplexComponent( (BaseAddon) this, 1562, 2, -3, 28, 1153, -1, "", 1);// 147
			AddComplexComponent( (BaseAddon) this, 1562, 2, -4, 28, 1163, -1, "", 1);// 148
			AddComplexComponent( (BaseAddon) this, 1562, 2, -5, 28, 1163, -1, "", 1);// 149
			AddComplexComponent( (BaseAddon) this, 1562, 2, -6, 28, 1163, -1, "", 1);// 150
			AddComplexComponent( (BaseAddon) this, 1562, 3, -6, 25, 1163, -1, "", 1);// 158
			AddComplexComponent( (BaseAddon) this, 1573, 4, -6, 22, 1163, -1, "", 1);// 159
			AddComplexComponent( (BaseAddon) this, 1562, 3, 5, 25, 1153, -1, "", 1);// 160
			AddComplexComponent( (BaseAddon) this, 1562, 3, 4, 25, 1153, -1, "", 1);// 161
			AddComplexComponent( (BaseAddon) this, 1562, 3, 3, 25, 1153, -1, "", 1);// 162
			AddComplexComponent( (BaseAddon) this, 1562, 3, 2, 25, 1163, -1, "", 1);// 163
			AddComplexComponent( (BaseAddon) this, 1562, 3, 1, 25, 1163, -1, "", 1);// 164
			AddComplexComponent( (BaseAddon) this, 1562, 3, 0, 25, 1163, -1, "", 1);// 165
			AddComplexComponent( (BaseAddon) this, 1562, 3, -1, 25, 1153, -1, "", 1);// 166
			AddComplexComponent( (BaseAddon) this, 1562, 3, -2, 25, 1153, -1, "", 1);// 167
			AddComplexComponent( (BaseAddon) this, 1562, 3, -3, 25, 1153, -1, "", 1);// 168
			AddComplexComponent( (BaseAddon) this, 1562, 3, -4, 25, 1163, -1, "", 1);// 169
			AddComplexComponent( (BaseAddon) this, 1562, 3, -5, 25, 1163, -1, "", 1);// 170
			AddComplexComponent( (BaseAddon) this, 1573, 4, 5, 22, 1153, -1, "", 1);// 171
			AddComplexComponent( (BaseAddon) this, 1573, 4, 4, 22, 1153, -1, "", 1);// 172
			AddComplexComponent( (BaseAddon) this, 1573, 4, 3, 22, 1153, -1, "", 1);// 173
			AddComplexComponent( (BaseAddon) this, 1573, 4, 2, 22, 1163, -1, "", 1);// 174
			AddComplexComponent( (BaseAddon) this, 1573, 4, 1, 22, 1163, -1, "", 1);// 175
			AddComplexComponent( (BaseAddon) this, 1573, 4, 0, 22, 1163, -1, "", 1);// 176
			AddComplexComponent( (BaseAddon) this, 1573, 4, -1, 22, 1153, -1, "", 1);// 177
			AddComplexComponent( (BaseAddon) this, 1573, 4, -2, 22, 1153, -1, "", 1);// 178
			AddComplexComponent( (BaseAddon) this, 1573, 4, -3, 22, 1153, -1, "", 1);// 179
			AddComplexComponent( (BaseAddon) this, 1573, 4, -4, 22, 1163, -1, "", 1);// 180
			AddComplexComponent( (BaseAddon) this, 1573, 4, -5, 22, 1163, -1, "", 1);// 181

		}

		public MarketTentEastMagentaAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class MarketTentEastMagentaAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new MarketTentEastMagentaAddon();
			}
		}

		[Constructable]
		public MarketTentEastMagentaAddonDeed()
		{
			Name = "MarketTentEastMagenta";
		}

		public MarketTentEastMagentaAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}