
////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class LargeOrangeAutumnTree2Addon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {42592, 1, 1, 33}, {42600, 1, 1, 0}, {42590, 0, 0, 21}// 1	2	3	
			, {42595, 0, 2, 62}, {42592, 0, 0, 68}, {3417, 0, 0, 1}// 4	5	6	
			, {42596, 2, -1, 25}, {42598, 2, -1, 0}, {42600, 0, -2, 0}// 7	8	9	
			, {42590, 1, -1, 20}, {42596, 1, -1, 42}, {42595, 1, -1, 50}// 10	11	12	
			, {3418, 1, -1, 0}, {42596, -1, 3, 28}, {42599, -1, 2, 0}// 13	14	15	
			, {42600, -2, 0, 0}, {42590, -2, 1, 14}, {42596, -1, 2, 41}// 16	17	18	
			, {3416, -1, 1, 0}// 19	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new LargeOrangeAutumnTree2AddonDeed();
			}
		}

		[ Constructable ]
		public LargeOrangeAutumnTree2Addon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


		}

		public LargeOrangeAutumnTree2Addon( Serial serial ) : base( serial )
		{
		}


		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class LargeOrangeAutumnTree2AddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new LargeOrangeAutumnTree2Addon();
			}
		}

		[Constructable]
		public LargeOrangeAutumnTree2AddonDeed()
		{
			Name = "LargeOrangeAutumnTree2";
		}

		public LargeOrangeAutumnTree2AddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}