
////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class BankWallEAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {40935, 0, -2, 12}, {40935, 0, -2, 8}, {40935, 0, -2, 4}// 1	2	3	
			, {40935, 0, -2, 0}, {39961, 0, 1, 8}, {39961, 0, 1, 0}// 4	5	6	
			, {39961, 0, -1, 8}, {39961, 0, 0, 8}, {39961, 0, 0, 0}// 7	8	9	
			, {4110, 0, -1, 18}, {39737, 0, -2, 16}, {40935, 0, 2, 4}// 10	11	12	
			, {39737, 0, -1, 16}, {40935, 0, 2, 12}, {40935, 0, 2, 0}// 13	14	15	
			, {39737, 0, 0, 16}, {40935, 0, 2, 8}, {39737, 0, 1, 16}// 16	17	18	
			, {39737, 0, 2, 16}, {39961, 0, -1, 0}// 19	20	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new BankWallEAddonDeed();
			}
		}

		[ Constructable ]
		public BankWallEAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


		}

		public BankWallEAddon( Serial serial ) : base( serial )
		{
		}


		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class BankWallEAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new BankWallEAddon();
			}
		}

		[Constructable]
		public BankWallEAddonDeed()
		{
			Name = "BankWallE";
		}

		public BankWallEAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}