
////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class TavernWallEAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {2451, 0, 2, 5}, {2488, 0, 2, 11}, {2449, 0, 2, 11}// 1	2	8	
			, {6467, 0, 2, 15}, {6467, 0, -2, 15}, {6467, 0, -2, 4}// 9	28	29	
			, {2466, 0, -2, 11}// 30	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new TavernWallEAddonDeed();
			}
		}

		[ Constructable ]
		public TavernWallEAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 2860, 0, -1, 21, 2418, -1, "", 1);// 3
			AddComplexComponent( (BaseAddon) this, 2860, 0, 0, 21, 2418, -1, "", 1);// 4
			AddComplexComponent( (BaseAddon) this, 2860, 0, 1, 21, 2418, -1, "", 1);// 5
			AddComplexComponent( (BaseAddon) this, 2860, 0, -1, 5, 2418, -1, "", 1);// 6
			AddComplexComponent( (BaseAddon) this, 2879, 0, 2, 12, 2418, -1, "", 1);// 7
			AddComplexComponent( (BaseAddon) this, 2879, 0, 2, 6, 2418, -1, "", 1);// 10
			AddComplexComponent( (BaseAddon) this, 2860, 0, 1, 5, 2418, -1, "", 1);// 11
			AddComplexComponent( (BaseAddon) this, 2860, 0, -1, 13, 2418, -1, "", 1);// 12
			AddComplexComponent( (BaseAddon) this, 2879, 0, 2, 18, 2418, -1, "", 1);// 13
			AddComplexComponent( (BaseAddon) this, 2860, 0, 0, 13, 2418, -1, "", 1);// 14
			AddComplexComponent( (BaseAddon) this, 2860, 0, 1, 13, 2418, -1, "", 1);// 15
			AddComplexComponent( (BaseAddon) this, 2877, 0, 2, 0, 2418, -1, "", 1);// 16
			AddComplexComponent( (BaseAddon) this, 2860, 0, 0, 5, 2418, -1, "", 1);// 17
			AddComplexComponent( (BaseAddon) this, 40503, 0, 1, 18, 0, -1, "Ale Keg", 1);// 18
			AddComplexComponent( (BaseAddon) this, 40503, 0, 1, 10, 0, -1, "Ale Keg", 1);// 19
			AddComplexComponent( (BaseAddon) this, 40503, 0, 0, 18, 0, -1, "Ale Keg", 1);// 20
			AddComplexComponent( (BaseAddon) this, 40503, 0, 0, 10, 0, -1, "Ale Keg", 1);// 21
			AddComplexComponent( (BaseAddon) this, 40503, 0, -1, 18, 0, -1, "Ale Keg", 1);// 22
			AddComplexComponent( (BaseAddon) this, 40503, 0, -1, 10, 0, -1, "Ale Keg", 1);// 23
			AddComplexComponent( (BaseAddon) this, 40503, 0, -1, 2, 0, -1, "Ale Keg", 1);// 24
			AddComplexComponent( (BaseAddon) this, 40503, 0, 0, 2, 0, -1, "Ale Keg", 1);// 25
			AddComplexComponent( (BaseAddon) this, 40503, 0, 1, 2, 0, -1, "Ale Keg", 1);// 26
			AddComplexComponent( (BaseAddon) this, 2879, 0, -2, 6, 2418, -1, "", 1);// 27
			AddComplexComponent( (BaseAddon) this, 2879, 0, -2, 12, 2418, -1, "", 1);// 31
			AddComplexComponent( (BaseAddon) this, 2879, 0, -2, 18, 2418, -1, "", 1);// 32
			AddComplexComponent( (BaseAddon) this, 2877, 0, -2, 0, 2418, -1, "", 1);// 33

		}

		public TavernWallEAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class TavernWallEAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new TavernWallEAddon();
			}
		}

		[Constructable]
		public TavernWallEAddonDeed()
		{
			Name = "TavernWallE";
		}

		public TavernWallEAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}