
////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class CHOOCHOOTenderAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {2519, -1, -3, 34}, {2519, -1, -3, 33}, {17225, 1, 1, 24}// 2	3	54	
			, {17225, -1, 1, 24}, {17225, 2, 0, 24}, {17225, 0, 1, 24}// 130	135	137	
					};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new CHOOCHOOTenderAddonDeed();
			}
		}

		[ Constructable ]
		public CHOOCHOOTenderAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 17087, -1, -2, 34, 0, -1, "Log Book", 1);// 1
			AddComplexComponent( (BaseAddon) this, 11576, 0, -3, 24, 1175, -1, "", 1);// 4
			AddComplexComponent( (BaseAddon) this, 487, 3, -4, 24, 2724, -1, "", 1);// 5
			AddComplexComponent( (BaseAddon) this, 487, 3, -1, 24, 2724, -1, "", 1);// 6
			AddComplexComponent( (BaseAddon) this, 487, 3, 2, 25, 2724, -1, "", 1);// 7
			AddComplexComponent( (BaseAddon) this, 487, 3, 5, 25, 2724, -1, "", 1);// 8
			AddComplexComponent( (BaseAddon) this, 1986, 1, 7, 22, 2724, -1, "", 1);// 9
			AddComplexComponent( (BaseAddon) this, 1981, 0, 7, 22, 2724, -1, "", 1);// 10
			AddComplexComponent( (BaseAddon) this, 1985, -1, 7, 22, 2724, -1, "", 1);// 11
			AddComplexComponent( (BaseAddon) this, 19513, 3, -4, 17, 2724, -1, "", 1);// 12
			AddComplexComponent( (BaseAddon) this, 17225, 1, 1, 31, 1175, -1, "", 1);// 13
			AddComplexComponent( (BaseAddon) this, 19513, 3, 1, 17, 2724, -1, "", 1);// 14
			AddComplexComponent( (BaseAddon) this, 19513, 3, 2, 17, 2724, -1, "", 1);// 15
			AddComplexComponent( (BaseAddon) this, 19513, 3, 3, 17, 2724, -1, "", 1);// 16
			AddComplexComponent( (BaseAddon) this, 19513, 3, 5, 17, 2724, -1, "", 1);// 17
			AddComplexComponent( (BaseAddon) this, 19513, 3, 6, 17, 2724, -1, "", 1);// 18
			AddComplexComponent( (BaseAddon) this, 19513, 3, 4, 17, 2724, -1, "", 1);// 19
			AddComplexComponent( (BaseAddon) this, 9269, 2, 1, 43, 1175, -1, "", 1);// 20
			AddComplexComponent( (BaseAddon) this, 9269, 2, 0, 43, 1175, -1, "", 1);// 21
			AddComplexComponent( (BaseAddon) this, 9269, 2, -1, 43, 1175, -1, "", 1);// 22
			AddComplexComponent( (BaseAddon) this, 9269, 2, -2, 43, 1175, -1, "", 1);// 23
			AddComplexComponent( (BaseAddon) this, 9269, 2, -3, 43, 1175, -1, "", 1);// 24
			AddComplexComponent( (BaseAddon) this, 9269, 2, -4, 43, 1175, -1, "", 1);// 25
			AddComplexComponent( (BaseAddon) this, 11576, 1, 1, 43, 1175, -1, "", 1);// 26
			AddComplexComponent( (BaseAddon) this, 11576, 1, 0, 43, 1175, -1, "", 1);// 27
			AddComplexComponent( (BaseAddon) this, 11576, 1, -1, 43, 1175, -1, "", 1);// 28
			AddComplexComponent( (BaseAddon) this, 11576, 1, -2, 43, 1175, -1, "", 1);// 29
			AddComplexComponent( (BaseAddon) this, 11576, 1, -3, 43, 1175, -1, "", 1);// 30
			AddComplexComponent( (BaseAddon) this, 11576, 1, -4, 43, 1175, -1, "", 1);// 31
			AddComplexComponent( (BaseAddon) this, 11576, 0, 1, 43, 1175, -1, "", 1);// 32
			AddComplexComponent( (BaseAddon) this, 11576, 0, 0, 43, 1175, -1, "", 1);// 33
			AddComplexComponent( (BaseAddon) this, 11576, 0, -1, 43, 1175, -1, "", 1);// 34
			AddComplexComponent( (BaseAddon) this, 11576, 0, -2, 43, 1175, -1, "", 1);// 35
			AddComplexComponent( (BaseAddon) this, 11576, 0, -3, 43, 1175, -1, "", 1);// 36
			AddComplexComponent( (BaseAddon) this, 11576, 0, -4, 43, 1175, -1, "", 1);// 37
			AddComplexComponent( (BaseAddon) this, 9269, -1, 1, 43, 1175, -1, "", 1);// 38
			AddComplexComponent( (BaseAddon) this, 9269, -1, 0, 43, 1175, -1, "", 1);// 39
			AddComplexComponent( (BaseAddon) this, 9269, -1, -1, 43, 1175, -1, "", 1);// 40
			AddComplexComponent( (BaseAddon) this, 9269, -1, -2, 43, 1175, -1, "", 1);// 41
			AddComplexComponent( (BaseAddon) this, 9269, -1, -3, 43, 1175, -1, "", 1);// 42
			AddComplexComponent( (BaseAddon) this, 9269, -1, -4, 43, 1175, -1, "", 1);// 43
			AddComplexComponent( (BaseAddon) this, 19513, 3, -2, 17, 2724, -1, "", 1);// 44
			AddComplexComponent( (BaseAddon) this, 17165, 1, 5, 7, 1175, -1, "", 1);// 45
			AddComplexComponent( (BaseAddon) this, 19513, 3, 0, 17, 2724, -1, "", 1);// 46
			AddComplexComponent( (BaseAddon) this, 2719, 3, -3, 49, 2724, -1, "", 1);// 47
			AddComplexComponent( (BaseAddon) this, 2719, 3, -1, 49, 2724, -1, "", 1);// 48
			AddComplexComponent( (BaseAddon) this, 2719, 3, 1, 49, 2724, -1, "", 1);// 49
			AddComplexComponent( (BaseAddon) this, 2719, 3, 6, 52, 2724, -1, "", 1);// 50
			AddComplexComponent( (BaseAddon) this, 9269, 2, 6, 46, 1175, -1, "", 1);// 51
			AddComplexComponent( (BaseAddon) this, 9269, 2, 3, 46, 1175, -1, "", 1);// 52
			AddComplexComponent( (BaseAddon) this, 17224, 2, -4, 24, 1175, -1, "", 1);// 53
			AddComplexComponent( (BaseAddon) this, 9269, 2, 5, 46, 1175, -1, "", 1);// 55
			AddComplexComponent( (BaseAddon) this, 17225, 0, 6, 25, 1175, -1, "", 1);// 56
			AddComplexComponent( (BaseAddon) this, 6585, 1, 3, 40, 2101, -1, "", 1);// 57
			AddComplexComponent( (BaseAddon) this, 1402, -1, 5, 41, 1175, -1, "", 1);// 58
			AddComplexComponent( (BaseAddon) this, 9269, 2, 2, 46, 1175, -1, "", 1);// 59
			AddComplexComponent( (BaseAddon) this, 9269, -1, 3, 46, 1175, -1, "", 1);// 60
			AddComplexComponent( (BaseAddon) this, 17224, 2, 6, 35, 1175, -1, "", 1);// 61
			AddComplexComponent( (BaseAddon) this, 11576, 1, 6, 46, 1175, -1, "", 1);// 62
			AddComplexComponent( (BaseAddon) this, 9269, -1, 2, 46, 1175, -1, "", 1);// 63
			AddComplexComponent( (BaseAddon) this, 1402, 0, 4, 41, 2101, -1, "", 1);// 64
			AddComplexComponent( (BaseAddon) this, 1403, 0, 5, 41, 2101, -1, "", 1);// 65
			AddComplexComponent( (BaseAddon) this, 6583, 1, 4, 41, 2101, -1, "", 1);// 66
			AddComplexComponent( (BaseAddon) this, 1403, 1, 2, 41, 1175, -1, "", 1);// 67
			AddComplexComponent( (BaseAddon) this, 1404, 1, 3, 41, 2101, -1, "", 1);// 68
			AddComplexComponent( (BaseAddon) this, 1403, 1, 4, 41, 2101, -1, "", 1);// 69
			AddComplexComponent( (BaseAddon) this, 1402, 1, 5, 41, 2101, -1, "", 1);// 70
			AddComplexComponent( (BaseAddon) this, 6585, 0, 3, 40, 2101, -1, "", 1);// 71
			AddComplexComponent( (BaseAddon) this, 9269, -1, 4, 46, 1175, -1, "", 1);// 72
			AddComplexComponent( (BaseAddon) this, 67, -1, 4, 41, 2101, -1, "", 1);// 73
			AddComplexComponent( (BaseAddon) this, 67, -1, 5, 41, 2101, -1, "", 1);// 74
			AddComplexComponent( (BaseAddon) this, 11576, 1, 2, 46, 1175, -1, "", 1);// 75
			AddComplexComponent( (BaseAddon) this, 11576, 0, 6, 46, 1175, -1, "", 1);// 76
			AddComplexComponent( (BaseAddon) this, 3693, 1, 4, 4, 1175, -1, "", 1);// 77
			AddComplexComponent( (BaseAddon) this, 17225, -1, 6, 25, 1175, -1, "", 1);// 78
			AddComplexComponent( (BaseAddon) this, 17225, 1, 6, 25, 1175, -1, "", 1);// 79
			AddComplexComponent( (BaseAddon) this, 17225, 2, 6, 24, 1175, -1, "", 1);// 80
			AddComplexComponent( (BaseAddon) this, 66, 0, 2, 41, 2101, -1, "", 1);// 81
			AddComplexComponent( (BaseAddon) this, 66, 1, 2, 41, 2101, -1, "", 1);// 82
			AddComplexComponent( (BaseAddon) this, 11576, 0, 2, 46, 1175, -1, "", 1);// 83
			AddComplexComponent( (BaseAddon) this, 25490, 2, 2, 0, 1175, -1, "", 1);// 84
			AddComplexComponent( (BaseAddon) this, 3693, 1, 2, 4, 1175, -1, "", 1);// 85
			AddComplexComponent( (BaseAddon) this, 25490, 2, -2, 0, 1175, -1, "", 1);// 86
			AddComplexComponent( (BaseAddon) this, 6583, 0, 4, 41, 1175, -1, "", 1);// 87
			AddComplexComponent( (BaseAddon) this, 1978, 1, 3, 19, 1175, -1, "", 1);// 88
			AddComplexComponent( (BaseAddon) this, 1978, 1, 1, 19, 1175, -1, "", 1);// 89
			AddComplexComponent( (BaseAddon) this, 3693, 1, -2, 4, 1175, -1, "", 1);// 90
			AddComplexComponent( (BaseAddon) this, 1978, 1, -1, 19, 1175, -1, "", 1);// 91
			AddComplexComponent( (BaseAddon) this, 1978, 1, -2, 19, 1175, -1, "", 1);// 92
			AddComplexComponent( (BaseAddon) this, 17224, 2, -3, 25, 1175, -1, "", 1);// 93
			AddComplexComponent( (BaseAddon) this, 25490, 2, -4, 0, 1175, -1, "", 1);// 94
			AddComplexComponent( (BaseAddon) this, 1978, 1, -3, 19, 1175, -1, "", 1);// 95
			AddComplexComponent( (BaseAddon) this, 1978, 1, -4, 19, 1175, -1, "", 1);// 96
			AddComplexComponent( (BaseAddon) this, 1978, -1, -3, 19, 1175, -1, "", 1);// 97
			AddComplexComponent( (BaseAddon) this, 1978, -1, -4, 19, 1175, -1, "", 1);// 98
			AddComplexComponent( (BaseAddon) this, 1978, 1, 5, 19, 1175, -1, "", 1);// 99
			AddComplexComponent( (BaseAddon) this, 17224, 2, 0, 32, 1175, -1, "", 1);// 100
			AddComplexComponent( (BaseAddon) this, 17224, 2, 1, 32, 1175, -1, "", 1);// 101
			AddComplexComponent( (BaseAddon) this, 19513, 3, -3, 17, 2724, -1, "", 1);// 102
			AddComplexComponent( (BaseAddon) this, 17224, 2, 2, 35, 1175, -1, "", 1);// 103
			AddComplexComponent( (BaseAddon) this, 17224, 2, -2, 25, 1175, -1, "", 1);// 104
			AddComplexComponent( (BaseAddon) this, 4667, 2, 4, 25, 2724, -1, "", 1);// 105
			AddComplexComponent( (BaseAddon) this, 17224, 2, -1, 25, 1175, -1, "", 1);// 106
			AddComplexComponent( (BaseAddon) this, 17224, 2, 6, 25, 1175, -1, "", 1);// 107
			AddComplexComponent( (BaseAddon) this, 1978, -1, 1, 19, 1175, -1, "", 1);// 108
			AddComplexComponent( (BaseAddon) this, 1978, -1, 3, 19, 1175, -1, "", 1);// 109
			AddComplexComponent( (BaseAddon) this, 1978, -1, 6, 19, 1175, -1, "", 1);// 110
			AddComplexComponent( (BaseAddon) this, 1978, -1, 5, 19, 1175, -1, "", 1);// 111
			AddComplexComponent( (BaseAddon) this, 1978, -1, -2, 19, 1175, -1, "", 1);// 112
			AddComplexComponent( (BaseAddon) this, 1978, -1, -1, 19, 1175, -1, "", 1);// 113
			AddComplexComponent( (BaseAddon) this, 1403, 0, 3, 41, 2101, -1, "", 1);// 114
			AddComplexComponent( (BaseAddon) this, 1402, 0, 2, 41, 1175, -1, "", 1);// 115
			AddComplexComponent( (BaseAddon) this, 6585, 0, 5, 41, 2101, -1, "", 1);// 116
			AddComplexComponent( (BaseAddon) this, 17225, 0, 6, 35, 1175, -1, "", 1);// 117
			AddComplexComponent( (BaseAddon) this, 1978, -1, 0, 19, 1175, -1, "", 1);// 118
			AddComplexComponent( (BaseAddon) this, 4668, 2, 3, 25, 2724, -1, "", 1);// 119
			AddComplexComponent( (BaseAddon) this, 9269, 2, 4, 46, 1175, -1, "", 1);// 120
			AddComplexComponent( (BaseAddon) this, 4666, 2, 5, 25, 2724, -1, "", 1);// 121
			AddComplexComponent( (BaseAddon) this, 1978, 1, 6, 19, 1175, -1, "", 1);// 122
			AddComplexComponent( (BaseAddon) this, 1402, -1, 3, 41, 1175, -1, "", 1);// 123
			AddComplexComponent( (BaseAddon) this, 1978, -1, 2, 19, 1175, -1, "", 1);// 124
			AddComplexComponent( (BaseAddon) this, 1403, -1, 4, 41, 1175, -1, "", 1);// 125
			AddComplexComponent( (BaseAddon) this, 1403, -1, 2, 41, 1175, -1, "", 1);// 126
			AddComplexComponent( (BaseAddon) this, 9269, -1, 6, 46, 1175, -1, "", 1);// 127
			AddComplexComponent( (BaseAddon) this, 17223, 2, 5, 12, 2724, -1, "", 1);// 128
			AddComplexComponent( (BaseAddon) this, 1978, 0, -3, 19, 1175, -1, "", 1);// 129
			AddComplexComponent( (BaseAddon) this, 1978, 1, 4, 19, 1175, -1, "", 1);// 131
			AddComplexComponent( (BaseAddon) this, 1978, 1, 2, 19, 1175, -1, "", 1);// 132
			AddComplexComponent( (BaseAddon) this, 1978, 1, 0, 19, 1175, -1, "", 1);// 133
			AddComplexComponent( (BaseAddon) this, 17225, -1, 1, 31, 1175, -1, "", 1);// 134
			AddComplexComponent( (BaseAddon) this, 17240, 2, 7, 25, 1175, 255, "", 1);// 136
			AddComplexComponent( (BaseAddon) this, 2879, -1, -3, 24, 2101, -1, "", 1);// 138
			AddComplexComponent( (BaseAddon) this, 2719, 3, 3, 52, 2724, -1, "", 1);// 139
			AddComplexComponent( (BaseAddon) this, 1978, 0, -2, 19, 1175, -1, "", 1);// 140
			AddComplexComponent( (BaseAddon) this, 17225, 0, 1, 31, 1175, -1, "", 1);// 141
			AddComplexComponent( (BaseAddon) this, 1978, 0, -1, 19, 1175, -1, "", 1);// 142
			AddComplexComponent( (BaseAddon) this, 25490, 2, 4, 0, 1175, -1, "", 1);// 143
			AddComplexComponent( (BaseAddon) this, 17224, 2, -1, 32, 1175, -1, "", 1);// 144
			AddComplexComponent( (BaseAddon) this, 17225, -1, 6, 35, 1175, -1, "", 1);// 145
			AddComplexComponent( (BaseAddon) this, 1978, 0, 0, 19, 1175, -1, "", 1);// 146
			AddComplexComponent( (BaseAddon) this, 17225, 1, 6, 35, 1175, -1, "", 1);// 147
			AddComplexComponent( (BaseAddon) this, 2719, 3, 4, 52, 2724, -1, "", 1);// 148
			AddComplexComponent( (BaseAddon) this, 3693, 1, -4, 7, 1175, -1, "", 1);// 149
			AddComplexComponent( (BaseAddon) this, 1978, 0, 1, 19, 1175, -1, "", 1);// 150
			AddComplexComponent( (BaseAddon) this, 2719, 3, 0, 49, 2724, -1, "", 1);// 151
			AddComplexComponent( (BaseAddon) this, 2719, 3, 5, 52, 2724, -1, "", 1);// 152
			AddComplexComponent( (BaseAddon) this, 17224, 2, -2, 32, 1175, -1, "", 1);// 153
			AddComplexComponent( (BaseAddon) this, 11576, 0, -4, 24, 1175, -1, "", 1);// 154
			AddComplexComponent( (BaseAddon) this, 17225, 2, 1, 31, 1175, -1, "", 1);// 155
			AddComplexComponent( (BaseAddon) this, 2879, -1, -2, 24, 2101, -1, "", 1);// 156
			AddComplexComponent( (BaseAddon) this, 2594, -1, 7, 25, 0, 29, "", 1);// 157
			AddComplexComponent( (BaseAddon) this, 1978, 0, 2, 19, 1175, -1, "", 1);// 158
			AddComplexComponent( (BaseAddon) this, 17224, 2, 1, 24, 1175, -1, "", 1);// 159
			AddComplexComponent( (BaseAddon) this, 1978, 0, 3, 19, 1175, -1, "", 1);// 160
			AddComplexComponent( (BaseAddon) this, 17224, 2, 2, 25, 1175, -1, "", 1);// 161
			AddComplexComponent( (BaseAddon) this, 17224, 2, 0, 25, 1175, -1, "", 1);// 162
			AddComplexComponent( (BaseAddon) this, 9269, -1, 5, 46, 1175, -1, "", 1);// 163
			AddComplexComponent( (BaseAddon) this, 67, -1, 3, 41, 2101, -1, "", 1);// 164
			AddComplexComponent( (BaseAddon) this, 2213, 1, 7, 25, 1128, -1, "", 1);// 165
			AddComplexComponent( (BaseAddon) this, 17224, 2, -4, 32, 1175, -1, "", 1);// 166
			AddComplexComponent( (BaseAddon) this, 17224, 2, -3, 32, 1175, -1, "", 1);// 167
			AddComplexComponent( (BaseAddon) this, 1978, 0, 4, 19, 1175, -1, "", 1);// 168
			AddComplexComponent( (BaseAddon) this, 19513, 3, -1, 17, 2724, -1, "", 1);// 169
			AddComplexComponent( (BaseAddon) this, 2719, 3, -2, 49, 2724, -1, "", 1);// 170
			AddComplexComponent( (BaseAddon) this, 2719, 3, 7, 52, 2724, -1, "", 1);// 171
			AddComplexComponent( (BaseAddon) this, 17225, 2, 6, 35, 1175, -1, "", 1);// 172
			AddComplexComponent( (BaseAddon) this, 1978, 0, 5, 19, 1175, -1, "", 1);// 173
			AddComplexComponent( (BaseAddon) this, 1978, -1, 4, 19, 1175, -1, "", 1);// 174
			AddComplexComponent( (BaseAddon) this, 1978, 0, 6, 19, 1175, -1, "", 1);// 175
			AddComplexComponent( (BaseAddon) this, 11576, 0, -6, 24, 1175, -1, "", 1);// 176
			AddComplexComponent( (BaseAddon) this, 11576, 0, -7, 24, 1175, -1, "", 1);// 177
			AddComplexComponent( (BaseAddon) this, 17223, 2, -5, 12, 2724, -1, "", 1);// 178
			AddComplexComponent( (BaseAddon) this, 11576, 0, -5, 24, 1175, -1, "", 1);// 179
			AddComplexComponent( (BaseAddon) this, 17225, 2, -5, 24, 1175, -1, "", 1);// 180
			AddComplexComponent( (BaseAddon) this, 17225, 2, -5, 32, 1175, -1, "", 1);// 181
			AddComplexComponent( (BaseAddon) this, 17225, -1, -5, 32, 1175, -1, "", 1);// 182
			AddComplexComponent( (BaseAddon) this, 17225, -1, -5, 24, 1175, -1, "", 1);// 183
			AddComplexComponent( (BaseAddon) this, 2719, -2, 0, 40, 2724, -1, "", 1);// 184
			AddComplexComponent( (BaseAddon) this, 2719, -2, -1, 40, 2724, -1, "", 1);// 185
			AddComplexComponent( (BaseAddon) this, 2719, -2, -2, 40, 2724, -1, "", 1);// 186
			AddComplexComponent( (BaseAddon) this, 2719, -2, -3, 40, 2724, -1, "", 1);// 187
			AddComplexComponent( (BaseAddon) this, 2719, -2, -4, 40, 2724, -1, "", 1);// 188
			AddComplexComponent( (BaseAddon) this, 17165, -2, 6, 16, 1175, -1, "", 1);// 189
			AddComplexComponent( (BaseAddon) this, 2719, -2, 5, 44, 2724, -1, "", 1);// 190
			AddComplexComponent( (BaseAddon) this, 2719, -2, 6, 44, 2724, -1, "", 1);// 191
			AddComplexComponent( (BaseAddon) this, 2719, -2, 4, 44, 2724, -1, "", 1);// 192
			AddComplexComponent( (BaseAddon) this, 17224, -2, 3, 24, 1175, -1, "", 1);// 193
			AddComplexComponent( (BaseAddon) this, 17224, -2, -1, 32, 1175, -1, "", 1);// 194
			AddComplexComponent( (BaseAddon) this, 17224, -2, -2, 32, 1175, -1, "", 1);// 195
			AddComplexComponent( (BaseAddon) this, 17224, -2, -3, 32, 1175, -1, "", 1);// 196
			AddComplexComponent( (BaseAddon) this, 2719, -2, 3, 44, 2724, -1, "", 1);// 197
			AddComplexComponent( (BaseAddon) this, 17224, -2, 5, 35, 1175, -1, "", 1);// 198
			AddComplexComponent( (BaseAddon) this, 17224, -2, 6, 35, 1175, -1, "", 1);// 199
			AddComplexComponent( (BaseAddon) this, 17224, -2, 4, 35, 1175, -1, "", 1);// 200
			AddComplexComponent( (BaseAddon) this, 17224, -2, 0, 32, 1175, -1, "", 1);// 201
			AddComplexComponent( (BaseAddon) this, 17224, -2, 4, 24, 1175, -1, "", 1);// 202
			AddComplexComponent( (BaseAddon) this, 17224, -2, -2, 24, 1175, -1, "", 1);// 203
			AddComplexComponent( (BaseAddon) this, 17224, -2, 2, 35, 1175, -1, "", 1);// 204
			AddComplexComponent( (BaseAddon) this, 17224, -2, -4, 32, 1175, -1, "", 1);// 205
			AddComplexComponent( (BaseAddon) this, 17224, -2, 1, 32, 1175, -1, "", 1);// 206
			AddComplexComponent( (BaseAddon) this, 17224, -2, 6, 24, 1175, -1, "", 1);// 207
			AddComplexComponent( (BaseAddon) this, 17224, -2, -1, 25, 1175, -1, "", 1);// 208
			AddComplexComponent( (BaseAddon) this, 17224, -2, 3, 35, 1175, -1, "", 1);// 209
			AddComplexComponent( (BaseAddon) this, 17224, -2, 0, 24, 1175, -1, "", 1);// 210
			AddComplexComponent( (BaseAddon) this, 17224, -2, 1, 24, 1175, -1, "", 1);// 211
			AddComplexComponent( (BaseAddon) this, 17224, -2, 2, 24, 1175, -1, "", 1);// 212
			AddComplexComponent( (BaseAddon) this, 17224, -2, 5, 24, 1175, -1, "", 1);// 213
			AddComplexComponent( (BaseAddon) this, 17240, -2, 7, 25, 1175, 255, "", 1);// 214
			AddComplexComponent( (BaseAddon) this, 17224, -2, -4, 24, 1175, -1, "", 1);// 215
			AddComplexComponent( (BaseAddon) this, 17224, -2, -3, 24, 1175, -1, "", 1);// 216
			AddComplexComponent( (BaseAddon) this, 2719, -2, 7, 44, 2724, -1, "", 1);// 217
			AddComplexComponent( (BaseAddon) this, 2719, -2, 2, 44, 2724, -1, "", 1);// 218
			AddComplexComponent( (BaseAddon) this, 17190, -2, -5, 22, 1175, -1, "", 1);// 219

		}

		public CHOOCHOOTenderAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class CHOOCHOOTenderAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new CHOOCHOOTenderAddon();
			}
		}

		[Constructable]
		public CHOOCHOOTenderAddonDeed()
		{
			Name = "CHOOCHOOTender";
		}

		public CHOOCHOOTenderAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}