
////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class CHOOCHOOCabooseAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {2793, 1, 4, 26}, {2787, 1, 5, 26}, {1198, 1, 6, 25}// 8	9	35	
			, {1195, 1, 5, 25}, {1194, 1, 4, 25}, {1201, 2, 6, 25}// 36	37	39	
			, {1199, 2, 5, 25}, {1199, 2, 4, 25}, {1978, 1, 7, 19}// 40	41	43	
			, {1978, 1, 6, 19}, {1978, 1, 5, 19}, {1978, 1, 4, 19}// 44	45	46	
			, {2790, 1, 3, 26}, {19584, 1, 3, 26}, {16815, 2, 0, 45}// 62	63	108	
			, {16815, 2, 1, 45}, {16815, 1, 3, 45}, {16815, 1, -2, 45}// 109	112	113	
			, {16815, 2, 3, 45}, {16815, 2, 2, 45}, {16815, 2, -1, 45}// 117	118	119	
			, {1196, 1, 3, 25}, {1194, 1, 2, 25}, {1196, 1, 1, 25}// 151	152	153	
			, {1194, 1, 0, 25}, {1195, 1, -1, 25}, {1199, 2, 3, 25}// 154	155	156	
			, {1199, 2, 2, 25}, {1199, 2, 1, 25}, {1199, 2, 0, 25}// 157	158	159	
			, {1199, 2, -1, 25}, {1196, 1, -2, 25}, {1195, 1, -3, 25}// 160	161	162	
			, {1200, 1, -4, 25}, {1199, 2, -2, 25}, {1203, 2, -4, 25}// 163	167	168	
			, {1199, 2, -3, 25}, {1978, 1, 3, 19}, {1978, 1, 2, 19}// 169	170	171	
			, {1978, 1, 1, 19}, {1978, 1, 0, 19}, {1978, 1, -1, 19}// 172	173	174	
			, {1978, 1, -2, 19}, {1978, 1, -3, 19}, {1978, 1, -4, 19}// 175	176	177	
			, {1978, 1, -5, 19}, {2795, 0, 4, 26}, {2794, 0, 5, 26}// 179	187	188	
			, {2791, -1, 4, 26}, {2789, -1, 5, 26}, {19589, -1, 5, 26}// 189	190	191	
			, {19588, -1, 4, 26}, {1198, 0, 6, 25}, {1202, -1, 6, 25}// 192	221	222	
			, {1196, 0, 5, 25}, {1197, -1, 5, 25}, {1195, 0, 4, 25}// 223	224	225	
			, {1197, -1, 4, 25}, {1978, 0, 7, 19}, {1978, 0, 6, 19}// 226	228	229	
			, {1978, 0, 5, 19}, {1978, 0, 4, 19}, {1978, -1, 5, 19}// 230	231	233	
			, {1978, -1, 4, 19}, {2792, 0, 3, 26}, {2788, -1, 3, 26}// 234	239	240	
			, {11739, -1, 3, 26}, {3650, -1, 2, 34}, {3650, -1, 2, 30}// 241	242	243	
			, {3650, -1, 2, 26}, {1825, -1, -2, 40}, {1825, -1, -2, 35}// 244	262	263	
			, {1825, -1, -2, 30}, {1825, -1, -2, 25}, {16815, -1, 3, 45}// 264	265	277	
			, {16815, 0, 3, 45}, {16815, -1, -2, 45}, {1197, -1, 3, 25}// 281	293	305	
			, {1197, -1, 2, 25}, {1197, -1, 1, 25}, {1197, -1, 0, 25}// 306	307	308	
			, {1197, -1, -1, 25}, {1194, 0, 3, 25}, {1196, 0, 2, 25}// 309	311	313	
			, {1194, 0, 1, 25}, {1197, -1, -3, 25}, {1200, 0, -4, 25}// 314	315	318	
			, {1196, 0, -3, 25}, {1197, -1, -2, 25}, {1195, 0, -2, 25}// 319	320	321	
			, {1194, 0, -1, 25}, {1196, 0, 0, 25}, {1978, 0, 3, 19}// 322	323	324	
			, {1978, 0, 2, 19}, {1978, 0, 1, 19}, {1978, 0, 0, 19}// 325	326	327	
			, {1978, 0, -1, 19}, {1978, 0, -2, 19}, {1978, 0, -3, 19}// 328	329	330	
			, {1978, 0, -4, 19}, {1978, -1, 3, 19}, {1978, -1, 2, 19}// 331	332	333	
			, {1978, -1, 1, 19}, {1978, 0, -5, 19}, {12255, -1, -1, 25}// 334	336	338	
			, {1978, -1, -4, 19}, {1978, -1, -3, 19}, {1978, -1, -2, 19}// 339	346	347	
			, {1978, -1, -1, 19}, {16815, 0, -2, 45}, {1978, -1, 0, 19}// 348	358	359	
			, {1204, -1, -4, 25}// 361	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new CHOOCHOOCabooseAddonDeed();
			}
		}

		[ Constructable ]
		public CHOOCHOOCabooseAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 2143, 1, 8, 34, 1652, -1, "", 1);// 1
			AddComplexComponent( (BaseAddon) this, 487, 3, 6, 25, 1652, -1, "", 1);// 2
			AddComplexComponent( (BaseAddon) this, 2141, 2, 8, 25, 1652, -1, "", 1);// 3
			AddComplexComponent( (BaseAddon) this, 2143, 1, 8, 25, 1652, -1, "", 1);// 4
			AddComplexComponent( (BaseAddon) this, 19513, 3, 6, 17, 1652, -1, "", 1);// 5
			AddComplexComponent( (BaseAddon) this, 19513, 3, 4, 17, 1652, -1, "", 1);// 6
			AddComplexComponent( (BaseAddon) this, 19513, 3, 5, 17, 1652, -1, "", 1);// 7
			AddComplexComponent( (BaseAddon) this, 22, 1, 8, 45, 1652, -1, "", 1);// 10
			AddComplexComponent( (BaseAddon) this, 21, 2, 7, 45, 1652, -1, "", 1);// 11
			AddComplexComponent( (BaseAddon) this, 21, 2, 6, 45, 1652, -1, "", 1);// 12
			AddComplexComponent( (BaseAddon) this, 21, 2, 5, 45, 1652, -1, "", 1);// 13
			AddComplexComponent( (BaseAddon) this, 21, 2, 4, 45, 1652, -1, "", 1);// 14
			AddComplexComponent( (BaseAddon) this, 11330, 1, 4, 71, 1175, -1, "", 1);// 15
			AddComplexComponent( (BaseAddon) this, 11331, 2, 4, 68, 1175, -1, "", 1);// 16
			AddComplexComponent( (BaseAddon) this, 11331, 3, 4, 65, 1175, -1, "", 1);// 17
			AddComplexComponent( (BaseAddon) this, 16815, 2, 5, 45, 1175, -1, "", 1);// 18
			AddComplexComponent( (BaseAddon) this, 16815, 2, 4, 45, 1175, -1, "", 1);// 19
			AddComplexComponent( (BaseAddon) this, 16815, 1, 5, 45, 1175, -1, "", 1);// 20
			AddComplexComponent( (BaseAddon) this, 16815, 1, 4, 45, 1175, -1, "", 1);// 21
			AddComplexComponent( (BaseAddon) this, 7, 1, 6, 25, 1652, -1, "", 1);// 22
			AddComplexComponent( (BaseAddon) this, 16815, 2, 8, 45, 1175, -1, "", 1);// 23
			AddComplexComponent( (BaseAddon) this, 16815, 2, 7, 45, 1175, -1, "", 1);// 24
			AddComplexComponent( (BaseAddon) this, 16815, 2, 6, 45, 1175, -1, "", 1);// 25
			AddComplexComponent( (BaseAddon) this, 22, 1, 8, 20, 1652, -1, "", 1);// 26
			AddComplexComponent( (BaseAddon) this, 16815, 1, 8, 45, 1175, -1, "", 1);// 27
			AddComplexComponent( (BaseAddon) this, 16815, 1, 7, 45, 1175, -1, "", 1);// 28
			AddComplexComponent( (BaseAddon) this, 16815, 1, 6, 45, 1175, -1, "", 1);// 29
			AddComplexComponent( (BaseAddon) this, 25490, 2, 5, 0, 1175, -1, "", 1);// 30
			AddComplexComponent( (BaseAddon) this, 3693, 1, 5, 4, 1175, -1, "", 1);// 31
			AddComplexComponent( (BaseAddon) this, 6, 2, 6, 25, 1652, -1, "", 1);// 32
			AddComplexComponent( (BaseAddon) this, 15, 2, 5, 25, 1652, 40, "", 1);// 33
			AddComplexComponent( (BaseAddon) this, 16815, 2, 8, 25, 1175, -1, "", 1);// 34
			AddComplexComponent( (BaseAddon) this, 16815, 1, 8, 25, 1175, -1, "", 1);// 38
			AddComplexComponent( (BaseAddon) this, 16815, 1, 7, 25, 1175, -1, "", 1);// 42
			AddComplexComponent( (BaseAddon) this, 20, 2, 8, 45, 1652, -1, "", 1);// 47
			AddComplexComponent( (BaseAddon) this, 17223, 3, 8, 22, 2724, -1, "", 1);// 48
			AddComplexComponent( (BaseAddon) this, 15, 2, 4, 25, 1652, 40, "", 1);// 49
			AddComplexComponent( (BaseAddon) this, 1827, 2, 7, 20, 1175, -1, "", 1);// 50
			AddComplexComponent( (BaseAddon) this, 20, 2, 8, 20, 1652, -1, "", 1);// 51
			AddComplexComponent( (BaseAddon) this, 2143, 2, 8, 35, 1652, -1, "", 1);// 52
			AddComplexComponent( (BaseAddon) this, 2143, 1, -7, 31, 1652, -1, "", 1);// 53
			AddComplexComponent( (BaseAddon) this, 487, 3, -5, 25, 1652, -1, "", 1);// 54
			AddComplexComponent( (BaseAddon) this, 487, 3, -1, 25, 1652, -1, "", 1);// 55
			AddComplexComponent( (BaseAddon) this, 487, 3, 2, 25, 1652, -1, "", 1);// 56
			AddComplexComponent( (BaseAddon) this, 19513, 3, -4, 17, 1652, -1, "", 1);// 57
			AddComplexComponent( (BaseAddon) this, 19513, 3, -1, 17, 1652, -1, "", 1);// 58
			AddComplexComponent( (BaseAddon) this, 19513, 3, -2, 17, 1652, -1, "", 1);// 59
			AddComplexComponent( (BaseAddon) this, 19513, 3, 1, 17, 1652, -1, "", 1);// 60
			AddComplexComponent( (BaseAddon) this, 19513, 3, -3, 17, 1652, -1, "", 1);// 61
			AddComplexComponent( (BaseAddon) this, 41690, 1, -3, 25, 2101, -1, "", 1);// 64
			AddComplexComponent( (BaseAddon) this, 41690, 1, -2, 25, 2101, -1, "", 1);// 65
			AddComplexComponent( (BaseAddon) this, 41690, 1, -4, 25, 2101, -1, "", 1);// 66
			AddComplexComponent( (BaseAddon) this, 22, 2, -7, 45, 1652, -1, "", 1);// 67
			AddComplexComponent( (BaseAddon) this, 22, 1, -7, 45, 1652, -1, "", 1);// 68
			AddComplexComponent( (BaseAddon) this, 21, 2, -6, 45, 1652, -1, "", 1);// 69
			AddComplexComponent( (BaseAddon) this, 21, 2, -5, 45, 1652, -1, "", 1);// 70
			AddComplexComponent( (BaseAddon) this, 21, 2, -4, 45, 1652, -1, "", 1);// 71
			AddComplexComponent( (BaseAddon) this, 21, 2, -3, 45, 1652, -1, "", 1);// 72
			AddComplexComponent( (BaseAddon) this, 21, 2, -2, 45, 1652, -1, "", 1);// 73
			AddComplexComponent( (BaseAddon) this, 11330, 1, 2, 71, 1175, -1, "", 1);// 74
			AddComplexComponent( (BaseAddon) this, 11330, 1, 1, 71, 1175, -1, "", 1);// 75
			AddComplexComponent( (BaseAddon) this, 11330, 1, 0, 71, 1175, -1, "", 1);// 76
			AddComplexComponent( (BaseAddon) this, 11330, 1, -1, 71, 1175, -1, "", 1);// 77
			AddComplexComponent( (BaseAddon) this, 11330, 1, 3, 71, 1175, -1, "", 1);// 78
			AddComplexComponent( (BaseAddon) this, 11331, 2, 3, 68, 1175, -1, "", 1);// 79
			AddComplexComponent( (BaseAddon) this, 11331, 2, 2, 68, 1175, -1, "", 1);// 80
			AddComplexComponent( (BaseAddon) this, 11331, 2, 1, 68, 1175, -1, "", 1);// 81
			AddComplexComponent( (BaseAddon) this, 11331, 2, 0, 68, 1175, -1, "", 1);// 82
			AddComplexComponent( (BaseAddon) this, 11331, 2, -1, 68, 1175, -1, "", 1);// 83
			AddComplexComponent( (BaseAddon) this, 11331, 3, 3, 65, 1175, -1, "", 1);// 84
			AddComplexComponent( (BaseAddon) this, 11331, 3, 2, 65, 1175, -1, "", 1);// 85
			AddComplexComponent( (BaseAddon) this, 11331, 3, 1, 65, 1175, -1, "", 1);// 86
			AddComplexComponent( (BaseAddon) this, 11331, 3, 0, 65, 1175, -1, "", 1);// 87
			AddComplexComponent( (BaseAddon) this, 11331, 3, -1, 65, 1175, -1, "", 1);// 88
			AddComplexComponent( (BaseAddon) this, 16815, 2, 3, 65, 1175, -1, "", 1);// 89
			AddComplexComponent( (BaseAddon) this, 16815, 2, 2, 65, 1175, -1, "", 1);// 90
			AddComplexComponent( (BaseAddon) this, 16815, 2, 1, 65, 1175, -1, "", 1);// 91
			AddComplexComponent( (BaseAddon) this, 16815, 2, 0, 65, 1175, -1, "", 1);// 92
			AddComplexComponent( (BaseAddon) this, 16815, 2, -1, 65, 1175, -1, "", 1);// 93
			AddComplexComponent( (BaseAddon) this, 16815, 1, 3, 65, 1175, -1, "", 1);// 94
			AddComplexComponent( (BaseAddon) this, 16815, 1, 2, 65, 1175, -1, "", 1);// 95
			AddComplexComponent( (BaseAddon) this, 16815, 1, 1, 65, 1175, -1, "", 1);// 96
			AddComplexComponent( (BaseAddon) this, 16815, 1, 0, 65, 1175, -1, "", 1);// 97
			AddComplexComponent( (BaseAddon) this, 16815, 1, -1, 65, 1175, -1, "", 1);// 98
			AddComplexComponent( (BaseAddon) this, 9, 2, -2, 45, 1652, -1, "", 1);// 99
			AddComplexComponent( (BaseAddon) this, 9, 2, 3, 45, 1652, -1, "", 1);// 100
			AddComplexComponent( (BaseAddon) this, 19513, 3, 2, 17, 1652, -1, "", 1);// 101
			AddComplexComponent( (BaseAddon) this, 17, 2, 2, 45, 1652, -1, "", 1);// 102
			AddComplexComponent( (BaseAddon) this, 17, 2, 1, 45, 1652, -1, "", 1);// 103
			AddComplexComponent( (BaseAddon) this, 17, 2, -1, 45, 1652, -1, "", 1);// 104
			AddComplexComponent( (BaseAddon) this, 18, 2, -2, 45, 1652, -1, "", 1);// 105
			AddComplexComponent( (BaseAddon) this, 16815, 1, 1, 45, 1652, -1, "", 1);// 106
			AddComplexComponent( (BaseAddon) this, 16815, 1, 2, 45, 1652, -1, "", 1);// 107
			AddComplexComponent( (BaseAddon) this, 18, 1, 3, 45, 1652, -1, "", 1);// 110
			AddComplexComponent( (BaseAddon) this, 19513, 3, 3, 17, 1652, -1, "", 1);// 111
			AddComplexComponent( (BaseAddon) this, 19513, 3, 0, 17, 1652, -1, "", 1);// 114
			AddComplexComponent( (BaseAddon) this, 7, 1, -5, 25, 1652, -1, "", 1);// 115
			AddComplexComponent( (BaseAddon) this, 17, 2, 0, 45, 1652, -1, "", 1);// 116
			AddComplexComponent( (BaseAddon) this, 16, 2, 3, 45, 1652, -1, "", 1);// 120
			AddComplexComponent( (BaseAddon) this, 21, 1, 0, 8, 1652, -1, "", 1);// 121
			AddComplexComponent( (BaseAddon) this, 21, 1, 1, 8, 1652, -1, "", 1);// 122
			AddComplexComponent( (BaseAddon) this, 16815, 2, -5, 45, 1175, -1, "", 1);// 123
			AddComplexComponent( (BaseAddon) this, 16815, 2, -6, 45, 1175, -1, "", 1);// 124
			AddComplexComponent( (BaseAddon) this, 21, 1, -1, 8, 1652, -1, "", 1);// 125
			AddComplexComponent( (BaseAddon) this, 1827, 2, -5, 20, 1175, -1, "", 1);// 126
			AddComplexComponent( (BaseAddon) this, 16815, 1, -5, 45, 1175, -1, "", 1);// 127
			AddComplexComponent( (BaseAddon) this, 16815, 1, -6, 45, 1175, -1, "", 1);// 128
			AddComplexComponent( (BaseAddon) this, 16815, 1, -2, 45, 1175, -1, "", 1);// 129
			AddComplexComponent( (BaseAddon) this, 25490, 2, 3, 0, 1175, -1, "", 1);// 130
			AddComplexComponent( (BaseAddon) this, 25490, 2, -4, 0, 1175, -1, "", 1);// 131
			AddComplexComponent( (BaseAddon) this, 25490, 2, -2, 0, 1175, -1, "", 1);// 132
			AddComplexComponent( (BaseAddon) this, 3693, 1, -2, 4, 1175, -1, "", 1);// 133
			AddComplexComponent( (BaseAddon) this, 3693, 1, -4, 4, 1175, -1, "", 1);// 134
			AddComplexComponent( (BaseAddon) this, 3693, 1, 3, 4, 1175, -1, "", 1);// 135
			AddComplexComponent( (BaseAddon) this, 8, 2, 1, 25, 1652, -1, "", 1);// 136
			AddComplexComponent( (BaseAddon) this, 8, 2, 2, 25, 1652, -1, "", 1);// 137
			AddComplexComponent( (BaseAddon) this, 8, 2, -4, 25, 1652, -1, "", 1);// 138
			AddComplexComponent( (BaseAddon) this, 16815, 2, -3, 45, 1175, -1, "", 1);// 139
			AddComplexComponent( (BaseAddon) this, 15, 2, -3, 25, 1652, 40, "", 1);// 140
			AddComplexComponent( (BaseAddon) this, 15, 2, -2, 25, 1652, 40, "", 1);// 141
			AddComplexComponent( (BaseAddon) this, 8, 2, 0, 25, 1652, -1, "", 1);// 142
			AddComplexComponent( (BaseAddon) this, 2143, 2, -7, 34, 1652, -1, "", 1);// 143
			AddComplexComponent( (BaseAddon) this, 16815, 1, -4, 45, 1175, -1, "", 1);// 144
			AddComplexComponent( (BaseAddon) this, 16815, 2, -2, 46, 1175, -1, "", 1);// 145
			AddComplexComponent( (BaseAddon) this, 12, 2, -5, 25, 1652, -1, "", 1);// 146
			AddComplexComponent( (BaseAddon) this, 8, 2, 3, 25, 1652, -1, "", 1);// 147
			AddComplexComponent( (BaseAddon) this, 17223, 2, -7, 10, 2724, -1, "", 1);// 148
			AddComplexComponent( (BaseAddon) this, 16815, 2, -4, 45, 1175, -1, "", 1);// 149
			AddComplexComponent( (BaseAddon) this, 16815, 1, -3, 45, 1175, -1, "", 1);// 150
			AddComplexComponent( (BaseAddon) this, 16815, 1, -6, 25, 1175, -1, "", 1);// 164
			AddComplexComponent( (BaseAddon) this, 2143, 1, -7, 25, 1652, -1, "", 1);// 165
			AddComplexComponent( (BaseAddon) this, 20, 1, -7, 9, 1652, -1, "", 1);// 166
			AddComplexComponent( (BaseAddon) this, 2141, 2, -7, 24, 1652, -1, "", 1);// 178
			AddComplexComponent( (BaseAddon) this, 18, 1, -2, 45, 1652, -1, "", 1);// 180
			AddComplexComponent( (BaseAddon) this, 16815, 1, -5, 25, 1175, -1, "", 1);// 181
			AddComplexComponent( (BaseAddon) this, 8, 2, -1, 25, 1652, -1, "", 1);// 182
			AddComplexComponent( (BaseAddon) this, 16815, 2, -6, 25, 1175, -1, "", 1);// 183
			AddComplexComponent( (BaseAddon) this, 16815, 1, -1, 45, 1652, -1, "", 1);// 184
			AddComplexComponent( (BaseAddon) this, 16815, 1, 0, 45, 1652, -1, "", 1);// 185
			AddComplexComponent( (BaseAddon) this, 2143, -1, 8, 34, 1652, -1, "", 1);// 186
			AddComplexComponent( (BaseAddon) this, 22, 0, 8, 45, 1652, -1, "", 1);// 193
			AddComplexComponent( (BaseAddon) this, 22, -1, 8, 45, 1652, -1, "", 1);// 194
			AddComplexComponent( (BaseAddon) this, 21, -2, 8, 45, 1652, -1, "", 1);// 195
			AddComplexComponent( (BaseAddon) this, 21, -2, 6, 45, 1652, -1, "", 1);// 196
			AddComplexComponent( (BaseAddon) this, 21, -2, 7, 45, 1652, -1, "", 1);// 197
			AddComplexComponent( (BaseAddon) this, 21, -2, 5, 45, 1652, -1, "", 1);// 198
			AddComplexComponent( (BaseAddon) this, 21, -2, 4, 45, 1652, -1, "", 1);// 199
			AddComplexComponent( (BaseAddon) this, 11332, 0, 4, 68, 1175, -1, "", 1);// 200
			AddComplexComponent( (BaseAddon) this, 11332, -1, 4, 65, 1175, -1, "", 1);// 201
			AddComplexComponent( (BaseAddon) this, 16815, -1, 5, 45, 1175, -1, "", 1);// 202
			AddComplexComponent( (BaseAddon) this, 16815, 0, 4, 45, 1175, -1, "", 1);// 203
			AddComplexComponent( (BaseAddon) this, 16815, 0, 5, 45, 1175, -1, "", 1);// 204
			AddComplexComponent( (BaseAddon) this, 16815, -1, 4, 45, 1175, -1, "", 1);// 205
			AddComplexComponent( (BaseAddon) this, 22, -2, 7, 9, 1652, -1, "", 1);// 206
			AddComplexComponent( (BaseAddon) this, 22, -1, 7, 9, 1652, -1, "", 1);// 207
			AddComplexComponent( (BaseAddon) this, 16815, 0, 8, 45, 1175, -1, "", 1);// 208
			AddComplexComponent( (BaseAddon) this, 16815, 0, 7, 45, 1175, -1, "", 1);// 209
			AddComplexComponent( (BaseAddon) this, 16815, 0, 6, 45, 1175, -1, "", 1);// 210
			AddComplexComponent( (BaseAddon) this, 7, -1, 6, 25, 1652, -1, "", 1);// 211
			AddComplexComponent( (BaseAddon) this, 9, -2, 8, 25, 1652, -1, "", 1);// 212
			AddComplexComponent( (BaseAddon) this, 16815, -1, 7, 45, 1175, -1, "", 1);// 213
			AddComplexComponent( (BaseAddon) this, 15, -2, 5, 25, 1652, 40, "", 1);// 214
			AddComplexComponent( (BaseAddon) this, 15, -2, 4, 25, 1652, 40, "", 1);// 215
			AddComplexComponent( (BaseAddon) this, 13, -2, 6, 25, 1652, -1, "", 1);// 216
			AddComplexComponent( (BaseAddon) this, 16815, -1, 6, 45, 1175, -1, "", 1);// 217
			AddComplexComponent( (BaseAddon) this, 16815, -1, 8, 45, 1175, -1, "", 1);// 218
			AddComplexComponent( (BaseAddon) this, 16815, 0, 8, 25, 1175, -1, "", 1);// 219
			AddComplexComponent( (BaseAddon) this, 16815, -1, 8, 25, 1175, -1, "", 1);// 220
			AddComplexComponent( (BaseAddon) this, 16815, 0, 7, 25, 1175, -1, "", 1);// 227
			AddComplexComponent( (BaseAddon) this, 1978, -1, 6, 19, 1175, -1, "", 1);// 232
			AddComplexComponent( (BaseAddon) this, 2141, -1, 8, 25, 1652, -1, "", 1);// 235
			AddComplexComponent( (BaseAddon) this, 1829, -1, 7, 20, 1175, -1, "", 1);// 236
			AddComplexComponent( (BaseAddon) this, 2143, -1, -7, 34, 1652, -1, "", 1);// 237
			AddComplexComponent( (BaseAddon) this, 1829, -1, -5, 19, 1175, -1, "", 1);// 238
			AddComplexComponent( (BaseAddon) this, 22, 0, -7, 45, 1652, -1, "", 1);// 245
			AddComplexComponent( (BaseAddon) this, 22, -1, -7, 45, 1652, -1, "", 1);// 246
			AddComplexComponent( (BaseAddon) this, 21, -2, -5, 45, 1652, -1, "", 1);// 247
			AddComplexComponent( (BaseAddon) this, 21, -2, -6, 45, 1652, -1, "", 1);// 248
			AddComplexComponent( (BaseAddon) this, 21, -2, -2, 45, 1652, -1, "", 1);// 249
			AddComplexComponent( (BaseAddon) this, 21, -2, -3, 45, 1652, -1, "", 1);// 250
			AddComplexComponent( (BaseAddon) this, 21, -2, -4, 45, 1652, -1, "", 1);// 251
			AddComplexComponent( (BaseAddon) this, 11332, 0, 3, 68, 1175, -1, "", 1);// 252
			AddComplexComponent( (BaseAddon) this, 11332, -1, -1, 65, 1175, -1, "", 1);// 253
			AddComplexComponent( (BaseAddon) this, 11332, -1, 0, 65, 1175, -1, "", 1);// 254
			AddComplexComponent( (BaseAddon) this, 16815, 0, 3, 65, 1175, -1, "", 1);// 255
			AddComplexComponent( (BaseAddon) this, 16815, 0, 2, 65, 1175, -1, "", 1);// 256
			AddComplexComponent( (BaseAddon) this, 16815, 0, 1, 65, 1175, -1, "", 1);// 257
			AddComplexComponent( (BaseAddon) this, 16815, 0, 0, 65, 1175, -1, "", 1);// 258
			AddComplexComponent( (BaseAddon) this, 16815, 0, -1, 65, 1175, -1, "", 1);// 259
			AddComplexComponent( (BaseAddon) this, 11332, -1, 1, 65, 1175, -1, "", 1);// 260
			AddComplexComponent( (BaseAddon) this, 16815, -1, 3, 65, 1175, -1, "", 1);// 261
			AddComplexComponent( (BaseAddon) this, 11332, 0, 0, 68, 1175, -1, "", 1);// 266
			AddComplexComponent( (BaseAddon) this, 11332, 0, 1, 68, 1175, -1, "", 1);// 267
			AddComplexComponent( (BaseAddon) this, 11332, 0, -1, 68, 1175, -1, "", 1);// 268
			AddComplexComponent( (BaseAddon) this, 9, -2, 3, 45, 1652, -1, "", 1);// 269
			AddComplexComponent( (BaseAddon) this, 17, -2, 3, 45, 1652, -1, "", 1);// 270
			AddComplexComponent( (BaseAddon) this, 17, -2, 2, 45, 1652, -1, "", 1);// 271
			AddComplexComponent( (BaseAddon) this, 17, -2, 1, 45, 1652, -1, "", 1);// 272
			AddComplexComponent( (BaseAddon) this, 18, -1, -2, 45, 1652, -1, "", 1);// 273
			AddComplexComponent( (BaseAddon) this, 16815, -1, 2, 45, 1652, -1, "", 1);// 274
			AddComplexComponent( (BaseAddon) this, 18, -1, 3, 45, 1652, -1, "", 1);// 275
			AddComplexComponent( (BaseAddon) this, 9, -2, -2, 45, 1652, -1, "", 1);// 276
			AddComplexComponent( (BaseAddon) this, 18, 0, -2, 45, 1652, -1, "", 1);// 278
			AddComplexComponent( (BaseAddon) this, 17, -2, -1, 45, 1652, -1, "", 1);// 279
			AddComplexComponent( (BaseAddon) this, 18, 0, 3, 45, 1652, -1, "", 1);// 280
			AddComplexComponent( (BaseAddon) this, 16815, -1, 1, 45, 1652, -1, "", 1);// 282
			AddComplexComponent( (BaseAddon) this, 2659, -1, -4, 25, 2724, -1, "", 1);// 283
			AddComplexComponent( (BaseAddon) this, 2659, -1, -4, 38, 2724, -1, "", 1);// 284
			AddComplexComponent( (BaseAddon) this, 2652, -1, -3, 38, 2724, -1, "", 1);// 285
			AddComplexComponent( (BaseAddon) this, 11332, -1, 2, 65, 1175, -1, "", 1);// 286
			AddComplexComponent( (BaseAddon) this, 16815, -1, -1, 65, 1175, -1, "", 1);// 287
			AddComplexComponent( (BaseAddon) this, 11332, 0, 2, 68, 1175, -1, "", 1);// 288
			AddComplexComponent( (BaseAddon) this, 16815, 0, 2, 45, 1652, -1, "", 1);// 289
			AddComplexComponent( (BaseAddon) this, 16815, 0, -4, 45, 1175, -1, "", 1);// 290
			AddComplexComponent( (BaseAddon) this, 16815, 0, -3, 45, 1175, -1, "", 1);// 291
			AddComplexComponent( (BaseAddon) this, 16815, 0, -2, 45, 1175, -1, "", 1);// 292
			AddComplexComponent( (BaseAddon) this, 9, -2, -7, 24, 1652, -1, "", 1);// 294
			AddComplexComponent( (BaseAddon) this, 2652, -1, -3, 25, 2724, -1, "", 1);// 295
			AddComplexComponent( (BaseAddon) this, 16815, 0, -6, 45, 1175, -1, "", 1);// 296
			AddComplexComponent( (BaseAddon) this, 8, -2, 0, 25, 1652, -1, "", 1);// 297
			AddComplexComponent( (BaseAddon) this, 7, -1, -5, 25, 1652, -1, "", 1);// 298
			AddComplexComponent( (BaseAddon) this, 8, -2, 1, 25, 1652, -1, "", 1);// 299
			AddComplexComponent( (BaseAddon) this, 8, -2, 3, 25, 1652, -1, "", 1);// 300
			AddComplexComponent( (BaseAddon) this, 8, -2, 2, 25, 1652, -1, "", 1);// 301
			AddComplexComponent( (BaseAddon) this, 8, -2, -2, 25, 1652, -1, "", 1);// 302
			AddComplexComponent( (BaseAddon) this, 16815, 0, 1, 45, 1652, -1, "", 1);// 303
			AddComplexComponent( (BaseAddon) this, 16815, 0, -5, 45, 1175, -1, "", 1);// 304
			AddComplexComponent( (BaseAddon) this, 20, -1, -6, 19, 1652, -1, "", 1);// 310
			AddComplexComponent( (BaseAddon) this, 16815, 0, -5, 25, 1175, -1, "", 1);// 312
			AddComplexComponent( (BaseAddon) this, 8, -2, -4, 25, 1652, -1, "", 1);// 316
			AddComplexComponent( (BaseAddon) this, 9, -2, -5, 25, 1652, -1, "", 1);// 317
			AddComplexComponent( (BaseAddon) this, 2141, -1, -7, 24, 1652, -1, "", 1);// 335
			AddComplexComponent( (BaseAddon) this, 16815, -1, -6, 45, 1175, -1, "", 1);// 337
			AddComplexComponent( (BaseAddon) this, 16815, 0, 0, 45, 1652, -1, "", 1);// 340
			AddComplexComponent( (BaseAddon) this, 16815, -1, -4, 45, 1175, -1, "", 1);// 341
			AddComplexComponent( (BaseAddon) this, 8, -2, -1, 25, 1652, -1, "", 1);// 342
			AddComplexComponent( (BaseAddon) this, 8, -2, -3, 25, 1652, -1, "", 1);// 343
			AddComplexComponent( (BaseAddon) this, 16815, -1, -3, 45, 1175, -1, "", 1);// 344
			AddComplexComponent( (BaseAddon) this, 17, -2, 0, 45, 1652, -1, "", 1);// 345
			AddComplexComponent( (BaseAddon) this, 16815, -1, -2, 45, 1175, -1, "", 1);// 349
			AddComplexComponent( (BaseAddon) this, 16815, 0, -1, 45, 1652, -1, "", 1);// 350
			AddComplexComponent( (BaseAddon) this, 16815, -1, -5, 45, 1175, -1, "", 1);// 351
			AddComplexComponent( (BaseAddon) this, 16815, -1, -2, 45, 1175, -1, "", 1);// 352
			AddComplexComponent( (BaseAddon) this, 16815, -1, 1, 65, 1175, -1, "", 1);// 353
			AddComplexComponent( (BaseAddon) this, 16815, -1, 0, 65, 1175, -1, "", 1);// 354
			AddComplexComponent( (BaseAddon) this, 16815, -1, 2, 65, 1175, -1, "", 1);// 355
			AddComplexComponent( (BaseAddon) this, 16815, -1, -6, 25, 1175, -1, "", 1);// 356
			AddComplexComponent( (BaseAddon) this, 16815, 0, -6, 25, 1175, -1, "", 1);// 357
			AddComplexComponent( (BaseAddon) this, 11332, -1, 3, 65, 1175, -1, "", 1);// 360

		}

		public CHOOCHOOCabooseAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class CHOOCHOOCabooseAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new CHOOCHOOCabooseAddon();
			}
		}

		[Constructable]
		public CHOOCHOOCabooseAddonDeed()
		{
			Name = "CHOOCHOOCaboose";
		}

		public CHOOCHOOCabooseAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}