
////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class AnimalCage_Wagon5Addon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {2861, 1, 4, 14}, {2861, 0, 4, 14}, {1848, 1, 4, 9}// 2	3	4	
			, {1848, 0, 4, 9}, {1996, 0, 3, 14}, {40278, 3, 3, 27}// 5	6	9	
			, {42314, 2, 1, 6}, {1201, 1, 4, 14}, {1202, 0, 4, 14}// 10	23	24	
			, {25, 2, -1, 12}, {25, 2, 0, 12}, {25, 2, 1, 12}// 25	26	27	
			, {25, 2, 2, 13}, {22, -1, 3, 12}, {20, 2, 3, 12}// 28	29	30	
			, {20788, -1, 3, 23}, {39716, -1, 3, 15}, {39717, -2, 3, 15}// 32	33	34	
			, {39717, -2, 2, 15}, {39717, -2, 1, 15}, {39717, -2, 0, 15}// 35	36	37	
			, {39717, -2, -1, 15}, {20793, -2, 0, 23}, {20793, -2, 2, 23}// 38	39	40	
			, {8173, 0, 3, 25}, {8175, 1, 3, 25}, {24, 1, 3, 47}// 43	44	45	
			, {24, 0, 3, 47}, {24, -1, 3, 47}, {17, -2, 0, 47}// 46	47	48	
			, {17, -2, -1, 47}, {17, -2, 1, 47}, {17, -2, 2, 47}// 49	50	51	
			, {25, -2, 3, 47}, {17, 2, -1, 47}, {17, 2, 0, 47}// 52	53	54	
			, {17, 2, 1, 47}, {17, 2, 2, 47}, {20, 2, 3, 47}// 55	56	57	
			, {20793, 2, 2, 23}, {20793, 2, 1, 23}, {20793, 2, 0, 23}// 58	59	60	
			, {20793, 2, -1, 23}, {20780, 2, 3, 23}, {1996, 0, 0, 14}// 61	62	63	
			, {1191, 2, 3, 47}, {1194, 2, 2, 47}, {1194, 2, 1, 47}// 64	65	66	
			, {1191, 2, 0, 47}, {1194, 2, -1, 47}, {1191, 1, 3, 47}// 67	68	69	
			, {1191, 1, 2, 47}, {1191, 1, 1, 47}, {1194, 1, 0, 47}// 70	71	72	
			, {1191, 1, -1, 47}, {1194, 0, 3, 47}, {1191, 0, 2, 47}// 73	74	75	
			, {1194, 0, 1, 47}, {1191, 0, 0, 47}, {1194, 0, -1, 47}// 76	77	78	
			, {1191, -1, 3, 47}, {1194, -1, 2, 47}, {1191, -1, 1, 47}// 79	80	81	
			, {1194, -1, 0, 47}, {1191, -1, -1, 47}, {20793, -2, -1, 23}// 82	83	84	
			, {20793, -2, 3, 23}, {20793, -2, 1, 23}, {39717, 2, -1, 15}// 85	86	87	
			, {39717, 2, 0, 15}, {39717, 2, 1, 15}, {39717, 2, 2, 15}// 88	89	90	
			, {39715, 2, 3, 15}, {1996, 1, 3, 14}, {1996, 1, 2, 14}// 91	92	93	
			, {1996, 1, 1, 14}, {1996, 1, 0, 14}, {1996, 1, -1, 14}// 94	95	96	
			, {1996, -1, 3, 14}, {1996, 2, 3, 14}, {1996, 0, -1, 14}// 97	98	99	
			, {1996, 0, 2, 14}, {1996, 0, 1, 14}, {1996, -1, -1, 14}// 100	101	102	
			, {1996, -1, 2, 14}, {1996, -1, 1, 14}, {1996, -1, 0, 14}// 103	104	105	
			, {1996, 2, -1, 14}, {1996, 2, 2, 14}, {1996, 2, 1, 14}// 106	107	108	
			, {1996, 2, 0, 14}, {40278, 3, -4, 27}, {42314, 2, -3, 7}// 109	113	114	
			, {8175, 1, -5, 25}, {8173, 0, -5, 25}, {42327, 0, -6, 3}// 115	116	117	
			, {1996, 0, -3, 14}, {1996, 2, -4, 14}, {1996, 0, -4, 14}// 118	119	120	
			, {1996, -1, -3, 14}, {25, 2, -4, 10}, {25, 2, -3, 13}// 121	124	125	
			, {25, 2, -2, 12}, {20779, -2, -5, 23}, {20793, -2, -2, 23}// 126	127	128	
			, {20793, -2, -3, 23}, {20793, -2, -4, 23}, {20788, -1, -5, 23}// 129	130	131	
			, {39716, -1, -5, 15}, {39717, -2, -2, 15}, {39717, -2, -3, 15}// 132	133	134	
			, {39717, -2, -4, 15}, {20788, 2, -5, 23}, {24, 2, -5, 47}// 135	136	137	
			, {24, 1, -5, 47}, {24, 0, -5, 47}, {24, -1, -5, 47}// 138	139	140	
			, {25, -2, -4, 47}, {17, -2, -3, 47}, {17, -2, -2, 47}// 141	142	143	
			, {25, 2, -4, 47}, {17, 2, -2, 47}, {17, 2, -3, 47}// 144	145	146	
			, {20793, 2, -2, 23}, {20793, 2, -3, 23}, {20793, 2, -4, 23}// 147	148	149	
			, {1191, 2, -2, 47}, {1194, 2, -3, 47}, {1191, 2, -4, 47}// 150	151	152	
			, {1194, 1, -2, 47}, {1191, 1, -3, 47}, {1194, 1, -4, 47}// 153	154	155	
			, {1191, 0, -2, 47}, {1194, 0, -3, 47}, {1191, 0, -4, 47}// 156	157	158	
			, {1194, -1, -2, 47}, {1191, -1, -3, 47}, {1194, -1, -4, 47}// 159	160	161	
			, {39716, 2, -5, 15}, {39717, 2, -4, 15}, {39717, 2, -3, 15}// 162	163	164	
			, {39717, 2, -2, 15}, {1996, 1, -2, 14}, {1996, 1, -5, 14}// 165	166	167	
			, {1996, 1, -3, 14}, {1996, 0, -2, 14}, {1996, -1, -2, 14}// 168	169	170	
			, {1996, 2, -2, 14}, {1996, 1, -4, 14}, {1996, -1, -4, 14}// 171	172	173	
			, {1996, 2, -3, 14}, {1996, 0, -5, 14}, {1996, -1, -5, 14}// 174	175	176	
			, {1996, 2, -5, 14}// 177	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new AnimalCage_Wagon5AddonDeed();
			}
		}

		[ Constructable ]
		public AnimalCage_Wagon5Addon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 25490, 3, 2, 0, 2312, -1, "Wagon Wheel", 1);// 1
			AddComplexComponent( (BaseAddon) this, 417, 1, 6, 8, 2418, -1, "", 1);// 7
			AddComplexComponent( (BaseAddon) this, 42328, -1, 4, 3, 551, -1, "", 1);// 8
			AddComplexComponent( (BaseAddon) this, 1217, -1, 4, 47, 2418, -1, "", 1);// 11
			AddComplexComponent( (BaseAddon) this, 1217, 2, 4, 47, 2418, -1, "", 1);// 12
			AddComplexComponent( (BaseAddon) this, 2188, 3, 4, 51, 0, 29, "", 1);// 13
			AddComplexComponent( (BaseAddon) this, 2188, -2, 3, 41, 0, 29, "", 1);// 14
			AddComplexComponent( (BaseAddon) this, 1217, 1, 4, 47, 2418, -1, "", 1);// 15
			AddComplexComponent( (BaseAddon) this, 1217, 0, 4, 47, 2418, -1, "", 1);// 16
			AddComplexComponent( (BaseAddon) this, 1218, 2, 5, 47, 2418, -1, "", 1);// 17
			AddComplexComponent( (BaseAddon) this, 1218, 1, 5, 47, 2418, -1, "", 1);// 18
			AddComplexComponent( (BaseAddon) this, 1218, 0, 5, 47, 2418, -1, "", 1);// 19
			AddComplexComponent( (BaseAddon) this, 1218, -1, 5, 47, 2418, -1, "", 1);// 20
			AddComplexComponent( (BaseAddon) this, 11541, 2, 4, 27, 2418, -1, "", 1);// 21
			AddComplexComponent( (BaseAddon) this, 11541, -2, 4, 26, 2418, -1, "", 1);// 22
			AddComplexComponent( (BaseAddon) this, 42330, 2, 4, 4, 551, -1, "", 1);// 31
			AddComplexComponent( (BaseAddon) this, 2152, 1, 3, 15, 551, -1, "", 1);// 41
			AddComplexComponent( (BaseAddon) this, 2150, 0, 3, 15, 551, -1, "", 1);// 42
			AddComplexComponent( (BaseAddon) this, 25490, 3, -3, 0, 2312, -1, "Wagon Wheel", 1);// 110
			AddComplexComponent( (BaseAddon) this, 2150, 0, -5, 15, 551, -1, "", 1);// 111
			AddComplexComponent( (BaseAddon) this, 2152, 1, -5, 15, 551, -1, "", 1);// 112
			AddComplexComponent( (BaseAddon) this, 2188, 2, -5, 40, 0, 29, "", 1);// 122
			AddComplexComponent( (BaseAddon) this, 2188, -2, -5, 40, 0, 29, "", 1);// 123

		}

		public AnimalCage_Wagon5Addon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class AnimalCage_Wagon5AddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new AnimalCage_Wagon5Addon();
			}
		}

		[Constructable]
		public AnimalCage_Wagon5AddonDeed()
		{
			Name = "AnimalCage_Wagon5";
		}

		public AnimalCage_Wagon5AddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}