
////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class ArchersCampAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {2883, -2, 5, 1}, {5453, -4, 5, 2}, {3672, 5, -4, 2}// 1	2	3	
			, {5463, -1, -1, 1}, {5463, -1, 0, 1}, {2778, -2, 0, 1}// 4	5	7	
			, {2778, -2, -1, 1}, {2778, -2, -2, 1}, {2778, -3, -2, 1}// 8	9	10	
			, {2778, -3, -1, 1}, {2778, -3, 0, 1}, {2778, -4, 0, 1}// 11	12	13	
			, {2778, -4, -1, 1}, {2778, -4, -2, 1}, {2780, -5, -3, 1}// 14	15	16	
			, {2785, -1, -2, 1}, {2784, -4, -3, 1}, {2784, -3, -3, 1}// 17	18	19	
			, {2784, -2, -3, 1}, {2783, -5, -2, 1}, {2783, -5, -1, 1}// 20	21	22	
			, {2783, -5, 0, 1}, {2782, -1, -3, 1}, {2786, -4, 1, 1}// 23	24	25	
			, {2781, -5, 1, 1}, {2786, -3, 1, 1}, {2786, -2, 1, 1}// 26	27	28	
			, {2785, -1, -1, 1}, {2785, -1, 0, 1}, {2779, -1, 1, 1}// 29	30	31	
			, {2778, -2, 3, 1}, {2778, -2, 2, 1}, {2778, -2, 1, 1}// 32	33	34	
			, {2778, -3, 1, 1}, {2778, -3, 2, 1}, {2778, -3, 3, 1}// 35	36	37	
			, {2783, -5, 2, 1}, {2778, -4, 3, 1}, {2783, -5, 1, 1}// 38	39	40	
			, {2784, -2, 0, 1}, {2784, -3, 0, 1}, {2784, -4, 0, 1}// 41	42	43	
			, {2785, -1, 1, 1}, {2780, -5, 0, 1}, {2778, -4, 1, 1}// 44	45	46	
			, {2778, -4, 2, 1}, {41587, 1, -2, 3}, {4109, -5, 5, 3}// 47	51	55	
			, {2884, -1, 5, 1}, {3896, 1, -3, 2}, {5058, -4, 3, 10}// 57	58	60	
			, {5056, 1, 2, 8}, {2879, 1, 2, 0}, {1208, -2, -2, 29}// 64	65	66	
			, {1208, -2, 1, 29}, {1208, -2, 0, 29}, {1208, -2, -1, 29}// 67	68	70	
			, {4133, -4, 0, 10}, {2863, 1, 3, 1}, {2863, 1, 1, 1}// 75	77	78	
			, {3905, -4, -4, 9}, {5056, -4, -1, 11}, {4109, -4, 6, 6}// 80	87	90	
			, {2879, -4, 0, 3}, {5455, -1, -2, 1}, {2868, -2, -4, 2}// 92	98	101	
			, {2783, -5, 3, 1}, {5351, -3, 5, 6}, {5351, 0, 5, 6}// 105	115	116	
			, {2868, -4, -4, 2}, {2781, -5, 4, 1}, {2662, -4, -3, 5}// 124	126	130	
			, {5905, -3, -1, 7}, {5058, -4, -2, 10}, {5899, -3, 0, 7}// 133	141	144	
			, {3644, -2, 2, 1}, {2879, -4, -1, 3}, {7135, 3, -4, 3}// 150	152	157	
			, {2786, -3, 4, 1}, {2662, -4, 1, 5}, {2786, -4, 4, 1}// 159	160	161	
			, {5057, -4, 2, 9}, {5454, -1, 1, 1}, {2785, -1, 2, 1}// 169	176	177	
			, {2786, -2, 4, 1}, {2779, -1, 4, 1}, {5057, -4, -3, 9}// 179	180	184	
			, {2785, -1, 3, 1}, {2524, 4, -1, 3}, {2782, -1, 0, 1}// 185	186	187	
					};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new ArchersCampAddonDeed();
			}
		}

		[ Constructable ]
		public ArchersCampAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 497, -2, 4, 1, 2418, -1, "", 1);// 6
			AddComplexComponent( (BaseAddon) this, 6947, 4, -4, 4, 2418, -1, "", 1);// 48
			AddComplexComponent( (BaseAddon) this, 6961, 2, -1, 2, 2418, -1, "", 1);// 49
			AddComplexComponent( (BaseAddon) this, 6962, 4, -3, 2, 2418, -1, "", 1);// 50
			AddComplexComponent( (BaseAddon) this, 6965, 3, -3, 2, 2418, -1, "", 1);// 52
			AddComplexComponent( (BaseAddon) this, 6961, 3, 0, 2, 2418, -1, "", 1);// 53
			AddComplexComponent( (BaseAddon) this, 6962, 5, -2, 2, 2418, -1, "", 1);// 54
			AddComplexComponent( (BaseAddon) this, 5042, -4, 0, 14, 2101, -1, "", 1);// 56
			AddComplexComponent( (BaseAddon) this, 1560, -2, -3, 23, 2418, -1, "", 1);// 59
			AddComplexComponent( (BaseAddon) this, 505, -4, -5, 1, 2418, -1, "", 1);// 61
			AddComplexComponent( (BaseAddon) this, 1559, -3, 0, 23, 2418, -1, "", 1);// 62
			AddComplexComponent( (BaseAddon) this, 496, 0, 4, 1, 2418, -1, "", 1);// 63
			AddComplexComponent( (BaseAddon) this, 6955, 4, -1, 2, 2418, -1, "", 1);// 69
			AddComplexComponent( (BaseAddon) this, 6959, 5, -1, 2, 2418, -1, "", 1);// 71
			AddComplexComponent( (BaseAddon) this, 1474, -2, 0, 27, 2418, -1, "", 1);// 72
			AddComplexComponent( (BaseAddon) this, 1565, -1, -3, 23, 2418, -1, "", 1);// 73
			AddComplexComponent( (BaseAddon) this, 1474, -2, 1, 27, 2418, -1, "", 1);// 74
			AddComplexComponent( (BaseAddon) this, 1474, -2, 2, 27, 2418, -1, "", 1);// 76
			AddComplexComponent( (BaseAddon) this, 1564, -1, 3, 23, 2418, -1, "", 1);// 79
			AddComplexComponent( (BaseAddon) this, 1571, -4, 2, 20, 2418, -1, "", 1);// 81
			AddComplexComponent( (BaseAddon) this, 1571, -4, 3, 20, 2418, -1, "", 1);// 82
			AddComplexComponent( (BaseAddon) this, 498, 0, 3, 1, 2418, -1, "", 1);// 83
			AddComplexComponent( (BaseAddon) this, 1572, -2, -4, 20, 2418, -1, "", 1);// 84
			AddComplexComponent( (BaseAddon) this, 41641, -3, -4, 2, 0, 2, "", 1);// 85
			AddComplexComponent( (BaseAddon) this, 1572, -3, -4, 20, 2418, -1, "", 1);// 86
			AddComplexComponent( (BaseAddon) this, 498, 0, 2, 1, 2418, -1, "", 1);// 88
			AddComplexComponent( (BaseAddon) this, 1578, -4, 4, 20, 2418, -1, "", 1);// 89
			AddComplexComponent( (BaseAddon) this, 497, -4, 4, 1, 2418, -1, "", 1);// 91
			AddComplexComponent( (BaseAddon) this, 497, -1, 4, 1, 2418, -1, "", 1);// 93
			AddComplexComponent( (BaseAddon) this, 1575, 0, 4, 20, 2418, -1, "", 1);// 94
			AddComplexComponent( (BaseAddon) this, 498, 0, 1, 1, 2418, -1, "", 1);// 95
			AddComplexComponent( (BaseAddon) this, 1576, -4, -4, 19, 2418, -1, "", 1);// 96
			AddComplexComponent( (BaseAddon) this, 497, -3, 4, 1, 2418, -1, "", 1);// 97
			AddComplexComponent( (BaseAddon) this, 498, 0, -2, 1, 2418, -1, "", 1);// 99
			AddComplexComponent( (BaseAddon) this, 1573, 0, 3, 20, 2418, -1, "", 1);// 100
			AddComplexComponent( (BaseAddon) this, 498, 0, -3, 1, 2418, -1, "", 1);// 102
			AddComplexComponent( (BaseAddon) this, 7163, -4, -1, 7, 0, -1, "", 200);// 103
			AddComplexComponent( (BaseAddon) this, 1574, -3, 4, 20, 2418, -1, "", 1);// 104
			AddComplexComponent( (BaseAddon) this, 1574, -2, 4, 20, 2418, -1, "", 1);// 106
			AddComplexComponent( (BaseAddon) this, 1571, -4, 0, 20, 2418, -1, "", 1);// 107
			AddComplexComponent( (BaseAddon) this, 1577, 0, -4, 20, 2418, -1, "", 1);// 108
			AddComplexComponent( (BaseAddon) this, 1574, -1, 4, 20, 2418, -1, "", 1);// 109
			AddComplexComponent( (BaseAddon) this, 2664, -4, 2, 5, 2418, -1, "", 1);// 110
			AddComplexComponent( (BaseAddon) this, 2664, -4, -2, 5, 2418, -1, "", 1);// 111
			AddComplexComponent( (BaseAddon) this, 498, 0, -4, 1, 2418, -1, "", 1);// 112
			AddComplexComponent( (BaseAddon) this, 1571, -4, -1, 20, 2418, -1, "", 1);// 113
			AddComplexComponent( (BaseAddon) this, 6949, 3, -4, 4, 2418, -1, "", 1);// 114
			AddComplexComponent( (BaseAddon) this, 503, -5, 3, 1, 2418, -1, "", 1);// 117
			AddComplexComponent( (BaseAddon) this, 504, -5, 2, 1, 2418, -1, "", 1);// 118
			AddComplexComponent( (BaseAddon) this, 1573, 0, 2, 20, 2418, -1, "", 1);// 119
			AddComplexComponent( (BaseAddon) this, 504, -5, 1, 1, 2418, -1, "", 1);// 120
			AddComplexComponent( (BaseAddon) this, 1474, -2, -1, 27, 2418, -1, "", 1);// 121
			AddComplexComponent( (BaseAddon) this, 1573, 0, 1, 20, 2418, -1, "", 1);// 122
			AddComplexComponent( (BaseAddon) this, 4012, 4, -1, 9, 0, 2, "", 1);// 123
			AddComplexComponent( (BaseAddon) this, 505, -2, -5, 1, 2418, -1, "", 1);// 125
			AddComplexComponent( (BaseAddon) this, 504, -5, 0, 1, 2418, -1, "", 1);// 127
			AddComplexComponent( (BaseAddon) this, 505, -3, -5, 1, 2418, -1, "", 1);// 128
			AddComplexComponent( (BaseAddon) this, 505, -1, -5, 1, 2418, -1, "", 1);// 129
			AddComplexComponent( (BaseAddon) this, 1572, -1, -4, 20, 2418, -1, "", 1);// 131
			AddComplexComponent( (BaseAddon) this, 6957, 4, -2, 2, 2418, -1, "", 1);// 132
			AddComplexComponent( (BaseAddon) this, 504, -5, -1, 1, 2418, -1, "", 1);// 134
			AddComplexComponent( (BaseAddon) this, 504, -5, -2, 1, 2418, -1, "", 1);// 135
			AddComplexComponent( (BaseAddon) this, 504, -5, -3, 1, 2418, -1, "", 1);// 136
			AddComplexComponent( (BaseAddon) this, 499, -5, -5, 0, 2418, -1, "", 1);// 137
			AddComplexComponent( (BaseAddon) this, 1562, -1, -2, 23, 2418, -1, "", 1);// 138
			AddComplexComponent( (BaseAddon) this, 1474, -2, -2, 27, 2418, -1, "", 1);// 139
			AddComplexComponent( (BaseAddon) this, 504, -5, -4, 1, 2418, -1, "", 1);// 140
			AddComplexComponent( (BaseAddon) this, 1562, -1, -1, 23, 2418, -1, "", 1);// 142
			AddComplexComponent( (BaseAddon) this, 7188, -2, 2, 4, 0, 2, "", 1);// 143
			AddComplexComponent( (BaseAddon) this, 3919, -2, -4, 9, 2101, -1, "", 1);// 145
			AddComplexComponent( (BaseAddon) this, 1559, -3, -1, 23, 2418, -1, "", 1);// 146
			AddComplexComponent( (BaseAddon) this, 6571, 4, -1, 13, 0, 1, "", 1);// 147
			AddComplexComponent( (BaseAddon) this, 1571, -4, -3, 20, 2418, -1, "", 1);// 148
			AddComplexComponent( (BaseAddon) this, 6958, 3, -1, 2, 2418, -1, "", 1);// 149
			AddComplexComponent( (BaseAddon) this, 500, -5, 4, 1, 2418, -1, "", 1);// 151
			AddComplexComponent( (BaseAddon) this, 1571, -4, -2, 20, 2418, -1, "", 1);// 153
			AddComplexComponent( (BaseAddon) this, 3895, 4, -1, 13, 0, -1, "Roasted Coney", 1);// 154
			AddComplexComponent( (BaseAddon) this, 1562, -1, 2, 23, 2418, -1, "", 1);// 155
			AddComplexComponent( (BaseAddon) this, 1562, -1, 1, 23, 2418, -1, "", 1);// 156
			AddComplexComponent( (BaseAddon) this, 1562, -1, 0, 23, 2418, -1, "", 1);// 158
			AddComplexComponent( (BaseAddon) this, 6944, 3, -5, 1, 2418, -1, "", 1);// 162
			AddComplexComponent( (BaseAddon) this, 6956, 3, -2, 1, 2418, -1, "", 1);// 163
			AddComplexComponent( (BaseAddon) this, 1573, 0, -2, 20, 2418, -1, "", 1);// 164
			AddComplexComponent( (BaseAddon) this, 6965, 2, -2, 2, 2418, -1, "", 1);// 165
			AddComplexComponent( (BaseAddon) this, 1559, -3, -2, 23, 2418, -1, "", 1);// 166
			AddComplexComponent( (BaseAddon) this, 1573, 0, -1, 20, 2418, -1, "", 1);// 167
			AddComplexComponent( (BaseAddon) this, 1559, -3, 2, 23, 2418, -1, "", 1);// 168
			AddComplexComponent( (BaseAddon) this, 1573, 0, 0, 20, 2418, -1, "", 1);// 170
			AddComplexComponent( (BaseAddon) this, 501, 0, -5, 1, 2418, -1, "", 1);// 171
			AddComplexComponent( (BaseAddon) this, 6959, 4, 0, 2, 2418, -1, "", 1);// 172
			AddComplexComponent( (BaseAddon) this, 1566, -3, -3, 23, 2418, -1, "", 1);// 173
			AddComplexComponent( (BaseAddon) this, 1571, -4, 1, 20, 2418, -1, "", 1);// 174
			AddComplexComponent( (BaseAddon) this, 6950, 3, -3, 4, 2418, -1, "", 1);// 175
			AddComplexComponent( (BaseAddon) this, 1573, 0, -3, 20, 2418, -1, "", 1);// 178
			AddComplexComponent( (BaseAddon) this, 1559, -3, 1, 23, 2418, -1, "", 1);// 181
			AddComplexComponent( (BaseAddon) this, 1567, -3, 3, 23, 2418, -1, "", 1);// 182
			AddComplexComponent( (BaseAddon) this, 1561, -2, 3, 23, 2418, -1, "", 1);// 183

		}

		public ArchersCampAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class ArchersCampAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new ArchersCampAddon();
			}
		}

		[Constructable]
		public ArchersCampAddonDeed()
		{
			Name = "ArchersCamp";
		}

		public ArchersCampAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}