
////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class FeastingTable3Addon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {2879, 0, -1, 0}, {2879, 0, 1, 0}, {2879, 1, 1, 0}// 1	2	3	
			, {2879, 1, 0, 0}, {2879, 1, -1, 0}, {10303, 1, -1, 7}// 4	5	6	
			, {2491, 0, 1, 7}, {2519, 1, 0, 6}, {2519, 1, 0, 7}// 8	11	12	
			, {2519, 1, 0, 8}, {2519, 1, 0, 9}, {9439, 1, 1, 8}// 13	14	15	
			, {11599, 0, -1, 7}, {2879, -1, -1, 0}, {2879, -1, 0, 0}// 16	17	18	
			, {2879, -1, 1, 0}, {2445, -1, 0, 6}, {2429, -1, -1, 7}// 19	20	21	
			, {2449, -1, -1, 6}// 22	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new FeastingTable3AddonDeed();
			}
		}

		[ Constructable ]
		public FeastingTable3Addon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 1955, 0, 0, 4, 2418, -1, "", 1);// 7
			AddComplexComponent( (BaseAddon) this, 6587, 0, 0, 11, 0, 1, "", 1);// 9
			AddComplexComponent( (BaseAddon) this, 6571, 0, 0, 14, 0, 1, "", 1);// 10

		}

		public FeastingTable3Addon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class FeastingTable3AddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new FeastingTable3Addon();
			}
		}

		[Constructable]
		public FeastingTable3AddonDeed()
		{
			Name = "FeastingTable3";
		}

		public FeastingTable3AddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}