
////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class MassiveBonePileAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {6926, -1, 2, 0}, {6925, 1, 2, 0}, {6940, 1, 2, 9}// 1	2	3	
			, {6883, 0, 2, 0}, {6881, 0, 2, 2}, {6874, -2, 0, 0}// 4	5	6	
			, {6875, -1, 0, 1}, {6876, 0, 0, 1}, {6877, 0, -1, 1}// 7	8	9	
			, {6927, 1, 1, 0}, {6878, 1, -1, 0}, {6879, 1, 0, 1}// 10	11	12	
			, {6922, 1, -1, 0}, {6935, 2, 0, 3}, {6938, 0, -1, 0}// 13	14	15	
			, {6883, 1, 0, 2}, {6882, 0, 1, 1}, {6928, -1, 1, 0}// 16	17	18	
			, {6937, 2, 1, 2}, {8707, 0, 0, 15}, {8700, 0, 0, 6}// 19	20	21	
			, {6872, 0, 1, 1}, {6873, -1, 1, 1}// 22	23	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new MassiveBonePileAddonDeed();
			}
		}

		[ Constructable ]
		public MassiveBonePileAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


		}

		public MassiveBonePileAddon( Serial serial ) : base( serial )
		{
		}


		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class MassiveBonePileAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new MassiveBonePileAddon();
			}
		}

		[Constructable]
		public MassiveBonePileAddonDeed()
		{
			Name = "MassiveBonePile";
		}

		public MassiveBonePileAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}