
////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class PicnicTable1Addon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {2913, -1, 0, 0}, {2938, 0, 0, 0}, {2934, 0, -1, 0}// 1	2	3	
			, {2933, 0, 1, 0}, {2911, 1, 1, 0}, {2911, -1, 1, 0}// 4	7	8	
			, {2429, 0, 0, 7}, {2428, 1, 1, 16}, {2503, 0, 1, 10}// 9	10	11	
			, {2912, 1, -1, 0}, {2912, -1, -1, 0}, {2913, 1, 0, 0}// 13	14	15	
			, {2469, 0, 0, 8}// 16	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new PicnicTable1AddonDeed();
			}
		}

		[ Constructable ]
		public PicnicTable1Addon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 7188, 0, -1, 4, 0, 2, "", 1);// 5
			AddComplexComponent( (BaseAddon) this, 44152, 0, 0, 6, 0, -1, "Pizza Pan", 1);// 6
			AddComplexComponent( (BaseAddon) this, 9433, 0, 1, 6, 0, -1, "Picnic Basket", 1);// 12

		}

		public PicnicTable1Addon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class PicnicTable1AddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new PicnicTable1Addon();
			}
		}

		[Constructable]
		public PicnicTable1AddonDeed()
		{
			Name = "PicnicTable1";
		}

		public PicnicTable1AddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}