
////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class SarcophagusFemaleOpenLidSouthAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {7286, 2, 0, 0}, {7285, 1, 0, 0}, {7284, 0, 0, 0}// 1	2	3	
			, {7283, -1, 0, 0}, {7282, -1, 1, 0}, {7281, 0, 1, 0}// 4	5	6	
			, {7280, 1, 1, 0}, {7279, 2, 1, 0}// 7	8	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new SarcophagusFemaleOpenLidSouthAddonDeed();
			}
		}

		[ Constructable ]
		public SarcophagusFemaleOpenLidSouthAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


		}

		public SarcophagusFemaleOpenLidSouthAddon( Serial serial ) : base( serial )
		{
		}


		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class SarcophagusFemaleOpenLidSouthAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new SarcophagusFemaleOpenLidSouthAddon();
			}
		}

		[Constructable]
		public SarcophagusFemaleOpenLidSouthAddonDeed()
		{
			Name = "SarcophagusFemaleOpenLidSouth";
		}

		public SarcophagusFemaleOpenLidSouthAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}