
////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class SarcophagusEmptyNoLidSouth2Addon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {7278, 1, 0, 0}, {7277, 0, 0, 0}, {7276, -1, 0, 0}// 1	2	3	
			, {7275, -1, 1, 0}, {7274, 0, 1, 0}, {7273, 1, 1, 0}// 4	5	6	
					};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new SarcophagusEmptyNoLidSouth2AddonDeed();
			}
		}

		[ Constructable ]
		public SarcophagusEmptyNoLidSouth2Addon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


		}

		public SarcophagusEmptyNoLidSouth2Addon( Serial serial ) : base( serial )
		{
		}


		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class SarcophagusEmptyNoLidSouth2AddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new SarcophagusEmptyNoLidSouth2Addon();
			}
		}

		[Constructable]
		public SarcophagusEmptyNoLidSouth2AddonDeed()
		{
			Name = "SarcophagusEmptyNoLidSouth2";
		}

		public SarcophagusEmptyNoLidSouth2AddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}