
////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class UndergroundDungeonEntranceAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {18322, 1, -3, 1}, {3312, 4, 2, 0}, {3312, 4, -3, 0}// 4	5	6	
			, {3312, -1, -2, 2}, {3312, -1, -3, 2}, {3307, 1, -3, 2}// 7	8	9	
			, {3307, 2, -3, 1}, {3307, -1, -3, 2}, {18322, -1, -1, 1}// 10	11	12	
			, {142, 0, -4, 0}, {128, 1, -4, 0}, {3268, 4, -3, 0}// 13	14	18	
			, {3268, 4, 0, 0}, {3260, 4, -1, 0}, {3260, 4, 2, 0}// 19	20	21	
			, {8706, 1, -4, 48}, {8706, 0, 3, 48}, {2327, 1, 3, 44}// 22	25	26	
			, {17220, -1, -4, 43}, {17220, -1, -2, 43}, {17220, -1, 1, 43}// 27	29	32	
			, {17220, -1, 3, 43}, {17223, 3, -2, 54}, {17223, 3, -3, 54}// 34	36	37	
			, {17223, 3, 1, 54}, {17223, 3, 3, 54}, {2328, -2, 2, 22}// 40	41	42	
			, {2327, 3, 1, 22}, {2327, 3, -3, 22}, {2327, 1, -4, 44}// 44	46	47	
			, {2328, 0, -4, 44}, {2327, 1, -2, 44}, {2328, 0, -2, 44}// 48	51	52	
			, {2327, 1, 0, 44}, {2327, 0, 3, 44}, {1312, 0, -1, 44}// 55	61	62	
			, {716, 4, 1, 0}, {716, 4, -4, 0}, {1312, 1, 3, 44}// 67	69	78	
			, {1312, 1, 2, 44}, {1312, 1, 1, 44}, {1312, 1, 0, 44}// 79	80	81	
			, {1312, 1, -1, 44}, {1312, 1, -2, 44}, {1312, 1, -3, 44}// 82	83	84	
			, {1312, 1, -4, 44}, {1312, 0, 3, 44}, {1312, 0, 2, 44}// 85	86	87	
			, {1312, 0, 1, 44}, {1312, 0, 0, 44}, {1312, 0, -2, 44}// 88	89	90	
			, {1312, 0, -3, 44}, {1312, 0, -4, 44}, {126, 1, -4, 22}// 91	92	93	
			, {122, 0, -4, 22}, {716, 2, -4, 22}, {716, 2, -3, 22}// 94	95	96	
			, {716, 2, -2, 22}, {716, 2, -1, 22}, {716, 2, 0, 22}// 97	98	99	
			, {716, 2, 1, 22}, {716, 2, 2, 22}, {716, 2, 3, 22}// 100	101	102	
			, {711, -1, -4, 22}, {711, -1, -3, 22}, {711, -1, -2, 22}// 103	104	105	
			, {711, -1, -1, 22}, {711, -1, 0, 22}, {711, -1, 1, 22}// 106	107	108	
			, {711, -1, 2, 22}, {711, -1, 3, 22}, {142, 3, -2, 0}// 109	110	113	
			, {142, -2, -2, 0}, {1313, 3, 3, 22}, {1312, 3, 2, 22}// 114	115	116	
			, {1312, 3, 1, 22}, {1312, 3, 0, 22}, {1312, 3, -2, 22}// 117	118	120	
			, {1312, 3, -3, 22}, {1313, 3, -4, 22}, {1313, 2, 3, 22}// 121	122	123	
			, {1313, 2, 2, 22}, {1313, 2, 1, 22}, {1313, 2, 0, 22}// 124	125	126	
			, {1313, 2, -1, 22}, {1313, 2, -2, 22}, {1313, 2, -3, 22}// 127	128	129	
			, {1313, 2, -4, 22}, {1313, 1, 3, 22}, {1313, 1, 2, 22}// 130	131	132	
			, {1313, 1, 1, 22}, {1313, 1, 0, 22}, {1313, 1, -1, 22}// 133	134	135	
			, {1313, 1, -2, 22}, {1313, 1, -3, 22}, {1313, 1, -4, 22}// 136	137	138	
			, {1313, 0, 3, 22}, {1313, 0, 2, 22}, {1313, 0, 1, 22}// 139	140	141	
			, {1313, 0, 0, 22}, {1313, 0, -1, 22}, {1313, 0, -2, 22}// 142	143	144	
			, {1313, 0, -3, 22}, {1313, 0, -4, 22}, {1313, -1, 3, 22}// 145	146	147	
			, {1313, -1, 2, 22}, {1313, -1, 1, 22}, {1313, -1, 0, 22}// 148	149	150	
			, {1313, -1, -1, 22}, {1313, -1, -2, 22}, {1313, -1, -3, 22}// 151	152	153	
			, {1313, -1, -4, 22}, {1313, -2, 3, 22}, {1313, -2, 2, 22}// 154	155	156	
			, {1313, -2, 1, 22}, {1313, -2, 0, 22}, {1313, -2, -1, 22}// 157	158	159	
			, {1313, -2, -2, 22}, {1313, -2, -3, 22}, {1313, -2, -4, 22}// 160	161	162	
			, {138, 2, 3, 0}, {2325, 2, 2, 2}, {2325, -1, 2, 2}// 167	169	170	
			, {134, -1, 3, 0}, {2325, 2, 1, 2}, {2325, 2, 0, 2}// 171	172	173	
			, {2325, 1, 2, 2}, {2325, 1, 1, 2}, {2325, 0, 1, 2}// 177	178	184	
			, {2325, -1, 1, 2}, {2325, -1, 0, 2}, {2325, 0, 3, 0}// 189	190	195	
			, {140, -2, 2, 1}, {140, 3, -4, 0}// 197	199	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new UndergroundDungeonEntranceAddonDeed();
			}
		}

		[ Constructable ]
		public UndergroundDungeonEntranceAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 2572, 3, 4, 16, 0, 5, "", 1);// 1
			AddComplexComponent( (BaseAddon) this, 2572, -2, 4, 16, 0, 5, "", 1);// 2
			AddComplexComponent( (BaseAddon) this, 17223, 3, 4, 54, 2101, -1, "", 1);// 3
			AddComplexComponent( (BaseAddon) this, 3788, -1, 0, 3, 0, -1, "The Corpse Of An Unlucky Adventurer", 1);// 15
			AddComplexComponent( (BaseAddon) this, 3685, 3, 0, 23, 0, 2, "", 1);// 16
			AddComplexComponent( (BaseAddon) this, 3688, 3, -1, 23, 0, 2, "", 1);// 17
			AddComplexComponent( (BaseAddon) this, 8706, 0, -4, 48, 2101, -1, "", 1);// 23
			AddComplexComponent( (BaseAddon) this, 8706, 1, 3, 48, 2101, -1, "", 1);// 24
			AddComplexComponent( (BaseAddon) this, 17220, -1, -3, 43, 2101, -1, "", 1);// 28
			AddComplexComponent( (BaseAddon) this, 17220, -1, -1, 43, 2101, -1, "", 1);// 30
			AddComplexComponent( (BaseAddon) this, 17220, -1, 0, 43, 2101, -1, "", 1);// 31
			AddComplexComponent( (BaseAddon) this, 17220, -1, 2, 43, 2101, -1, "", 1);// 33
			AddComplexComponent( (BaseAddon) this, 17223, 3, 2, 54, 2101, -1, "", 1);// 35
			AddComplexComponent( (BaseAddon) this, 17223, 3, -1, 54, 2101, -1, "", 1);// 38
			AddComplexComponent( (BaseAddon) this, 17223, 3, 0, 54, 2101, -1, "", 1);// 39
			AddComplexComponent( (BaseAddon) this, 2328, 3, 2, 22, 2101, -1, "", 1);// 43
			AddComplexComponent( (BaseAddon) this, 2327, 3, -2, 22, 2101, -1, "", 1);// 45
			AddComplexComponent( (BaseAddon) this, 2328, 1, -3, 44, 2101, -1, "", 1);// 49
			AddComplexComponent( (BaseAddon) this, 2327, 0, -3, 44, 2101, -1, "", 1);// 50
			AddComplexComponent( (BaseAddon) this, 2328, 1, -1, 44, 2101, -1, "", 1);// 53
			AddComplexComponent( (BaseAddon) this, 2327, 0, -1, 44, 2101, -1, "", 1);// 54
			AddComplexComponent( (BaseAddon) this, 2328, 0, 0, 44, 2101, -1, "", 1);// 56
			AddComplexComponent( (BaseAddon) this, 2328, 1, 1, 44, 2101, -1, "", 1);// 57
			AddComplexComponent( (BaseAddon) this, 2327, 0, 1, 44, 2101, -1, "", 1);// 58
			AddComplexComponent( (BaseAddon) this, 2327, 1, 2, 44, 2101, -1, "", 1);// 59
			AddComplexComponent( (BaseAddon) this, 2328, 0, 2, 44, 2101, -1, "", 1);// 60
			AddComplexComponent( (BaseAddon) this, 133, 3, -1, 0, 2101, 255, "", 1);// 63
			AddComplexComponent( (BaseAddon) this, 133, 3, 0, 0, 0, 255, "", 1);// 64
			AddComplexComponent( (BaseAddon) this, 133, -2, 0, 0, 2101, 255, "", 1);// 65
			AddComplexComponent( (BaseAddon) this, 133, -2, -1, 0, 0, 255, "", 1);// 66
			AddComplexComponent( (BaseAddon) this, 716, 4, -2, 0, 2101, -1, "", 1);// 68
			AddComplexComponent( (BaseAddon) this, 716, 4, 3, 0, 2101, -1, "", 1);// 70
			AddComplexComponent( (BaseAddon) this, 711, -3, 3, 0, 2101, -1, "", 1);// 71
			AddComplexComponent( (BaseAddon) this, 8705, -2, 3, 22, 2101, -1, "", 1);// 72
			AddComplexComponent( (BaseAddon) this, 8705, -2, -4, 22, 2101, -1, "", 1);// 73
			AddComplexComponent( (BaseAddon) this, 8705, 3, 3, 22, 2101, -1, "", 1);// 74
			AddComplexComponent( (BaseAddon) this, 8705, 3, -4, 22, 2101, -1, "", 1);// 75
			AddComplexComponent( (BaseAddon) this, 131, 0, 3, 22, 2101, 255, "", 1);// 76
			AddComplexComponent( (BaseAddon) this, 131, 1, 3, 22, 2101, 255, "", 1);// 77
			AddComplexComponent( (BaseAddon) this, 142, -2, 1, 0, 2101, -1, "", 1);// 111
			AddComplexComponent( (BaseAddon) this, 142, 3, 1, 0, 2101, -1, "", 1);// 112
			AddComplexComponent( (BaseAddon) this, 1312, 3, -1, 22, 2101, -1, "", 1);// 119
			AddComplexComponent( (BaseAddon) this, 137, 1, 3, 0, 2101, -1, "", 1);// 163
			AddComplexComponent( (BaseAddon) this, 137, 0, 3, 0, 2101, -1, "", 1);// 164
			AddComplexComponent( (BaseAddon) this, 140, 3, 3, 0, 2101, -1, "", 1);// 165
			AddComplexComponent( (BaseAddon) this, 140, -2, 3, 0, 2101, -1, "", 1);// 166
			AddComplexComponent( (BaseAddon) this, 140, 3, 2, 0, 2101, -1, "", 1);// 168
			AddComplexComponent( (BaseAddon) this, 2325, 2, -1, 0, 1, -1, "", 1);// 174
			AddComplexComponent( (BaseAddon) this, 2325, 2, -2, 0, 1, -1, "", 1);// 175
			AddComplexComponent( (BaseAddon) this, 2325, 2, -3, 0, 1, -1, "", 1);// 176
			AddComplexComponent( (BaseAddon) this, 2325, 1, 0, 2, 2101, -1, "", 1);// 179
			AddComplexComponent( (BaseAddon) this, 2325, 1, -1, 0, 1, -1, "", 1);// 180
			AddComplexComponent( (BaseAddon) this, 2325, 1, -2, 0, 1, -1, "", 1);// 181
			AddComplexComponent( (BaseAddon) this, 2325, 1, -3, 0, 1, -1, "", 1);// 182
			AddComplexComponent( (BaseAddon) this, 2325, 0, 2, 2, 2101, -1, "", 1);// 183
			AddComplexComponent( (BaseAddon) this, 2325, 0, 0, 2, 2101, -1, "", 1);// 185
			AddComplexComponent( (BaseAddon) this, 2325, 0, -1, 0, 1, -1, "", 1);// 186
			AddComplexComponent( (BaseAddon) this, 2325, 0, -2, 0, 1, -1, "", 1);// 187
			AddComplexComponent( (BaseAddon) this, 2325, 0, -3, 0, 1, -1, "", 1);// 188
			AddComplexComponent( (BaseAddon) this, 2325, -1, -1, 0, 1, -1, "", 1);// 191
			AddComplexComponent( (BaseAddon) this, 2325, -1, -2, 0, 1, -1, "", 1);// 192
			AddComplexComponent( (BaseAddon) this, 2325, -1, -3, 0, 1, -1, "", 1);// 193
			AddComplexComponent( (BaseAddon) this, 2325, 1, 3, 0, 2101, -1, "", 1);// 194
			AddComplexComponent( (BaseAddon) this, 2325, -1, 3, 0, 2101, -1, "", 1);// 196
			AddComplexComponent( (BaseAddon) this, 140, 3, -3, 0, 2101, -1, "", 1);// 198
			AddComplexComponent( (BaseAddon) this, 140, 2, -4, 0, 2101, -1, "", 1);// 200
			AddComplexComponent( (BaseAddon) this, 140, -1, -4, 0, 2101, -1, "", 1);// 201
			AddComplexComponent( (BaseAddon) this, 140, -2, -3, 0, 2101, -1, "", 1);// 202
			AddComplexComponent( (BaseAddon) this, 140, -2, -4, 0, 2101, -1, "", 1);// 203

		}

		public UndergroundDungeonEntranceAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class UndergroundDungeonEntranceAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new UndergroundDungeonEntranceAddon();
			}
		}

		[Constructable]
		public UndergroundDungeonEntranceAddonDeed()
		{
			Name = "UndergroundDungeonEntrance";
		}

		public UndergroundDungeonEntranceAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}