
////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class WallCarvingEastAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {41247, 0, 3, 0}, {4970, 1, 3, 4}, {41256, 1, -2, 5}// 1	2	3	
			, {4968, 1, -1, 0}, {4972, 1, 1, 1}, {4973, 1, -2, 1}// 4	5	6	
			, {490, 0, -2, 3}, {490, 0, -2, 0}, {490, 0, 2, 3}// 7	8	9	
			, {490, 0, 2, 0}, {4675, 0, 2, 5}, {4666, 0, 1, 0}// 10	11	12	
			, {4667, 0, 0, 0}, {4668, 0, -1, 0}, {4675, 0, -2, 5}// 13	14	15	
					};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new WallCarvingEastAddonDeed();
			}
		}

		[ Constructable ]
		public WallCarvingEastAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


		}

		public WallCarvingEastAddon( Serial serial ) : base( serial )
		{
		}


		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class WallCarvingEastAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new WallCarvingEastAddon();
			}
		}

		[Constructable]
		public WallCarvingEastAddonDeed()
		{
			Name = "WallCarvingEast";
		}

		public WallCarvingEastAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}