
////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class WineBarrelRackSAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {2451, 2, 0, 16}, {6467, 2, 0, 3}, {2879, 2, 0, 17}// 1	2	3	
			, {2877, -2, 0, 0}, {2877, 2, 0, 0}, {2879, -2, 0, 17}// 4	5	6	
			, {2879, 2, 0, 5}, {6467, -2, 0, 14}, {2879, -2, 0, 5}// 7	8	9	
			, {6467, 2, 0, 9}, {6467, -2, 0, 8}, {2450, -2, 0, 5}// 10	11	12	
			, {2879, 2, 0, 11}, {2861, 1, 0, 21}, {2861, 0, 0, 21}// 13	14	15	
			, {2861, -1, 0, 21}, {2861, 1, 0, 13}, {2861, 0, 0, 13}// 16	17	18	
			, {2861, -1, 0, 13}, {2861, 1, 0, 5}, {2861, 0, 0, 5}// 19	20	21	
			, {2861, -1, 0, 5}, {2879, -2, 0, 11}// 22	32	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new WineBarrelRackSAddonDeed();
			}
		}

		[ Constructable ]
		public WineBarrelRackSAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 40502, 1, 0, 18, 0, -1, "Ale Keg", 1);// 23
			AddComplexComponent( (BaseAddon) this, 40502, 1, 0, 10, 0, -1, "Ale Keg", 1);// 24
			AddComplexComponent( (BaseAddon) this, 40502, 0, 0, 18, 0, -1, "Ale Keg", 1);// 25
			AddComplexComponent( (BaseAddon) this, 40502, 0, 0, 10, 0, -1, "Ale Keg", 1);// 26
			AddComplexComponent( (BaseAddon) this, 40502, -1, 0, 18, 0, -1, "Ale Keg", 1);// 27
			AddComplexComponent( (BaseAddon) this, 40502, -1, 0, 10, 0, -1, "Ale Keg", 1);// 28
			AddComplexComponent( (BaseAddon) this, 40502, 1, 0, 2, 0, -1, "Ale Keg", 1);// 29
			AddComplexComponent( (BaseAddon) this, 40502, 0, 0, 2, 0, -1, "Ale Keg", 1);// 30
			AddComplexComponent( (BaseAddon) this, 40502, -1, 0, 2, 0, -1, "Ale Keg", 1);// 31

		}

		public WineBarrelRackSAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class WineBarrelRackSAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new WineBarrelRackSAddon();
			}
		}

		[Constructable]
		public WineBarrelRackSAddonDeed()
		{
			Name = "WineBarrelRackS";
		}

		public WineBarrelRackSAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}