
////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class SmallSteamBoatNorth_SpectralAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {41198, 2, 3, 10}, {40364, 1, 0, 13}, {8612, 1, 0, 3}// 1	2	3	
			, {8612, 1, 1, 3}, {8612, 1, 2, 3}, {2838, -1, 3, 16}// 4	5	13	
			, {2831, 0, 3, 16}, {4604, 0, 1, 15}, {40142, 1, 0, 12}// 16	20	24	
			, {4604, 0, -1, 14}, {3649, 0, 3, 23}, {3647, 0, 4, 27}// 29	30	31	
			, {3644, 0, 4, 24}, {37654, 0, -2, 0}// 32	33	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new SmallSteamBoatNorth_SpectralAddonDeed();
			}
		}

		[ Constructable ]
		public SmallSteamBoatNorth_SpectralAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 4245, -1, -2, 16, 0, -1, "Throttle", 1);// 6
			AddComplexComponent( (BaseAddon) this, 1898, 1, 4, 13, 1159, -1, "", 1);// 7
			AddComplexComponent( (BaseAddon) this, 16031, -1, -1, 11, 1159, -1, "", 1);// 8
			AddComplexComponent( (BaseAddon) this, 2835, 1, -3, 14, 1159, -1, "console", 1);// 9
			AddComplexComponent( (BaseAddon) this, 2832, -1, -3, 14, 1159, -1, "console", 1);// 10
			AddComplexComponent( (BaseAddon) this, 2839, 0, 2, 16, 2107, -1, "", 1);// 11
			AddComplexComponent( (BaseAddon) this, 2832, -1, 2, 16, 2107, -1, "", 1);// 12
			AddComplexComponent( (BaseAddon) this, 2834, -1, 4, 16, 1159, -1, "", 1);// 14
			AddComplexComponent( (BaseAddon) this, 2837, 0, 4, 16, 1159, -1, "", 1);// 15
			AddComplexComponent( (BaseAddon) this, 16044, -1, 3, 11, 2418, -1, "", 1);// 17
			AddComplexComponent( (BaseAddon) this, 16044, 1, 4, 19, 1159, -1, "", 1);// 18
			AddComplexComponent( (BaseAddon) this, 16044, -1, 2, 11, 2418, -1, "", 1);// 19
			AddComplexComponent( (BaseAddon) this, 194, 1, 0, 11, 1105, -1, "", 1);// 21
			AddComplexComponent( (BaseAddon) this, 40147, 1, 4, 20, 0, -1, "Moonstone Powered Engine", 1);// 22
			AddComplexComponent( (BaseAddon) this, 20392, 1, 3, 21, 0, -1, "Diagnostics", 1);// 23
			AddComplexComponent( (BaseAddon) this, 16044, 0, 0, 11, 1159, -1, "", 1);// 25
			AddComplexComponent( (BaseAddon) this, 16044, 1, 0, 11, 2418, -1, "", 1);// 26
			AddComplexComponent( (BaseAddon) this, 16044, 0, 1, 11, 1105, -1, "", 1);// 27
			AddComplexComponent( (BaseAddon) this, 40158, -1, -3, 15, 1159, -1, "Forward, Reverse Controls", 1);// 28
			AddComplexComponent( (BaseAddon) this, 17359, 0, -3, 9, 1159, -1, "", 1);// 34
			AddComplexComponent( (BaseAddon) this, 16042, 0, 4, 11, 2130, -1, "", 1);// 35
			AddComplexComponent( (BaseAddon) this, 16060, 0, 5, 10, 1159, -1, "", 1);// 36
			AddComplexComponent( (BaseAddon) this, 16054, -1, 4, 9, 1159, -1, "", 1);// 37
			AddComplexComponent( (BaseAddon) this, 16053, 1, 4, 11, 2418, -1, "", 1);// 38
			AddComplexComponent( (BaseAddon) this, 16044, 0, 3, 11, 2418, -1, "", 1);// 39
			AddComplexComponent( (BaseAddon) this, 16044, 0, 2, 11, 2418, -1, "", 1);// 40
			AddComplexComponent( (BaseAddon) this, 16044, -1, 0, 11, 1159, -1, "", 1);// 41
			AddComplexComponent( (BaseAddon) this, 16044, 0, -1, 11, 1159, -1, "", 1);// 42
			AddComplexComponent( (BaseAddon) this, 16044, 0, -2, 11, 1159, -1, "", 1);// 43
			AddComplexComponent( (BaseAddon) this, 16039, -1, 3, 11, 2418, -1, "", 1);// 44
			AddComplexComponent( (BaseAddon) this, 16037, -1, 2, 11, 1166, -1, "", 1);// 45
			AddComplexComponent( (BaseAddon) this, 16033, -1, 1, 11, 1159, -1, "", 1);// 46
			AddComplexComponent( (BaseAddon) this, 16032, 1, -1, 11, 1159, -1, "", 1);// 47
			AddComplexComponent( (BaseAddon) this, 16030, 1, -2, 11, 1159, -1, "", 1);// 48
			AddComplexComponent( (BaseAddon) this, 16029, -1, -2, 11, 1159, -1, "", 1);// 49
			AddComplexComponent( (BaseAddon) this, 16028, 1, -3, 11, 1159, -1, "", 1);// 50
			AddComplexComponent( (BaseAddon) this, 16027, -1, -3, 11, 1159, -1, "", 1);// 51
			AddComplexComponent( (BaseAddon) this, 2586, 0, -4, 14, 0, 1, "", 1);// 52
			AddComplexComponent( (BaseAddon) this, 16026, 0, -4, 11, 1159, -1, "", 1);// 53

		}

		public SmallSteamBoatNorth_SpectralAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class SmallSteamBoatNorth_SpectralAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new SmallSteamBoatNorth_SpectralAddon();
			}
		}

		[Constructable]
		public SmallSteamBoatNorth_SpectralAddonDeed()
		{
			Name = "SmallSteamBoatNorth_Spectral";
		}

		public SmallSteamBoatNorth_SpectralAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}