
////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class SmallSteamBoatNorth_FishermanVariantAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {7844, 2, -2, 9}, {3545, 0, 0, 15}, {3520, 0, 0, 13}// 2	3	4	
			, {3530, -1, 1, 15}, {12387, 0, 3, 19}, {12386, 0, 4, 19}// 5	12	13	
			, {41198, 2, 3, 10}, {40364, 1, 0, 13}, {8612, 1, 0, 3}// 14	15	16	
			, {8612, 1, 1, 3}, {8612, 1, 2, 3}, {4604, 0, 1, 14}// 17	18	33	
			, {40142, 1, 0, 12}, {37654, 0, -2, 0}// 37	42	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new SmallSteamBoatNorth_FishermanVariantAddonDeed();
			}
		}

		[ Constructable ]
		public SmallSteamBoatNorth_FishermanVariantAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 2510, -1, 1, 16, 0, -1, "a big damn fish", 1);// 1
			AddComplexComponent( (BaseAddon) this, 2501, 0, -2, 11, 0, -1, "Hidden Stash Of Wiskey", 1);// 6
			AddComplexComponent( (BaseAddon) this, 42924, -1, 0, 19, 0, -1, "a fish basket", 1);// 7
			AddComplexComponent( (BaseAddon) this, 42924, -1, -1, 18, 0, -1, "a fish basket", 1);// 8
			AddComplexComponent( (BaseAddon) this, 42924, -1, 0, 16, 0, -1, "a fish basket", 1);// 9
			AddComplexComponent( (BaseAddon) this, 42924, -1, -1, 15, 0, -1, "a fish basket", 1);// 10
			AddComplexComponent( (BaseAddon) this, 4583, 0, -1, 12, 0, -1, "a standing mat", 1);// 11
			AddComplexComponent( (BaseAddon) this, 4245, -1, -2, 16, 0, -1, "Throttle", 1);// 19
			AddComplexComponent( (BaseAddon) this, 1898, 1, 4, 13, 442, -1, "", 1);// 20
			AddComplexComponent( (BaseAddon) this, 16031, -1, -1, 11, 442, -1, "", 1);// 21
			AddComplexComponent( (BaseAddon) this, 2835, 1, -3, 14, 442, -1, "console", 1);// 22
			AddComplexComponent( (BaseAddon) this, 2832, -1, -3, 14, 442, -1, "console", 1);// 23
			AddComplexComponent( (BaseAddon) this, 2839, 0, 2, 16, 437, -1, "", 1);// 24
			AddComplexComponent( (BaseAddon) this, 2832, -1, 2, 16, 442, -1, "", 1);// 25
			AddComplexComponent( (BaseAddon) this, 2838, -1, 3, 16, 442, -1, "", 1);// 26
			AddComplexComponent( (BaseAddon) this, 2834, -1, 4, 16, 442, -1, "", 1);// 27
			AddComplexComponent( (BaseAddon) this, 2837, 0, 4, 16, 442, -1, "", 1);// 28
			AddComplexComponent( (BaseAddon) this, 2831, 0, 3, 16, 437, -1, "", 1);// 29
			AddComplexComponent( (BaseAddon) this, 16044, -1, 3, 11, 2418, -1, "", 1);// 30
			AddComplexComponent( (BaseAddon) this, 16044, 1, 4, 19, 442, -1, "", 1);// 31
			AddComplexComponent( (BaseAddon) this, 16044, -1, 2, 11, 2418, -1, "", 1);// 32
			AddComplexComponent( (BaseAddon) this, 194, 1, 0, 11, 1105, -1, "", 1);// 34
			AddComplexComponent( (BaseAddon) this, 40147, 1, 4, 20, 0, -1, "Moonstone Powered Engine", 1);// 35
			AddComplexComponent( (BaseAddon) this, 20392, 1, 3, 21, 0, -1, "Diagnostics", 1);// 36
			AddComplexComponent( (BaseAddon) this, 16044, 0, 0, 11, 442, -1, "", 1);// 38
			AddComplexComponent( (BaseAddon) this, 16044, 1, 0, 11, 2418, -1, "", 1);// 39
			AddComplexComponent( (BaseAddon) this, 16044, 0, 1, 11, 442, -1, "", 1);// 40
			AddComplexComponent( (BaseAddon) this, 40158, -1, -3, 15, 442, -1, "Forward, Reverse Controls", 1);// 41
			AddComplexComponent( (BaseAddon) this, 17359, 0, -3, 9, 442, -1, "", 1);// 43
			AddComplexComponent( (BaseAddon) this, 16042, 0, 4, 11, 437, -1, "", 1);// 44
			AddComplexComponent( (BaseAddon) this, 16060, 0, 5, 10, 442, -1, "", 1);// 45
			AddComplexComponent( (BaseAddon) this, 16054, -1, 4, 9, 442, -1, "", 1);// 46
			AddComplexComponent( (BaseAddon) this, 16053, 1, 4, 11, 2418, -1, "", 1);// 47
			AddComplexComponent( (BaseAddon) this, 16044, 0, 3, 11, 2418, -1, "", 1);// 48
			AddComplexComponent( (BaseAddon) this, 16044, 0, 2, 11, 2418, -1, "", 1);// 49
			AddComplexComponent( (BaseAddon) this, 16044, -1, 0, 11, 442, -1, "", 1);// 50
			AddComplexComponent( (BaseAddon) this, 16044, 0, -1, 11, 442, -1, "", 1);// 51
			AddComplexComponent( (BaseAddon) this, 16044, 0, -2, 11, 442, -1, "", 1);// 52
			AddComplexComponent( (BaseAddon) this, 16039, -1, 3, 11, 442, -1, "", 1);// 53
			AddComplexComponent( (BaseAddon) this, 16037, -1, 2, 11, 442, -1, "", 1);// 54
			AddComplexComponent( (BaseAddon) this, 16033, -1, 1, 11, 442, -1, "", 1);// 55
			AddComplexComponent( (BaseAddon) this, 16032, 1, -1, 11, 442, -1, "", 1);// 56
			AddComplexComponent( (BaseAddon) this, 16030, 1, -2, 11, 442, -1, "", 1);// 57
			AddComplexComponent( (BaseAddon) this, 16029, -1, -2, 11, 442, -1, "", 1);// 58
			AddComplexComponent( (BaseAddon) this, 16028, 1, -3, 11, 442, -1, "", 1);// 59
			AddComplexComponent( (BaseAddon) this, 16027, -1, -3, 11, 442, -1, "", 1);// 60
			AddComplexComponent( (BaseAddon) this, 2586, 0, -4, 14, 0, 1, "", 1);// 61
			AddComplexComponent( (BaseAddon) this, 16026, 0, -4, 11, 442, -1, "", 1);// 62

		}

		public SmallSteamBoatNorth_FishermanVariantAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class SmallSteamBoatNorth_FishermanVariantAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new SmallSteamBoatNorth_FishermanVariantAddon();
			}
		}

		[Constructable]
		public SmallSteamBoatNorth_FishermanVariantAddonDeed()
		{
			Name = "SmallSteamBoatNorth_FishermanVariant";
		}

		public SmallSteamBoatNorth_FishermanVariantAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}