
////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class SmallSteamBoatNorth_PartyTopperAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {1543, 0, 2, 29}, {1588, 0, 1, 29}, {1535, -1, 2, 26}// 7	8	9	
			, {1535, -1, 1, 26}, {1540, 1, 2, 29}, {1538, 1, 1, 29}// 10	11	12	
			, {1538, 2, 2, 26}, {1538, 2, 1, 26}, {1537, 1, 3, 26}// 13	14	15	
			, {1538, 1, 0, 29}, {1538, 1, -1, 29}, {1541, 1, -2, 29}// 16	17	18	
			, {1536, 1, -3, 26}, {1537, 0, 3, 26}, {1588, 0, 0, 29}// 19	20	21	
			, {1588, 0, -1, 29}, {1542, 0, -2, 29}, {1536, 0, -3, 26}// 22	23	24	
			, {1543, -1, 3, 26}, {1535, -1, 0, 26}, {1535, -1, -1, 26}// 25	26	27	
			, {1535, -1, -2, 26}, {1542, -1, -3, 26}, {1540, 2, 3, 26}// 28	29	30	
			, {1538, 2, 0, 26}, {1538, 2, -1, 26}, {1538, 2, -2, 26}// 31	32	33	
			, {1541, 2, -3, 26}, {2592, -2, 1, 2}, {2592, 1, 1, 2}// 34	35	36	
			, {2592, -2, -3, 2}, {2592, 1, -3, 2}// 37	38	
		};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new SmallSteamBoatNorth_PartyTopperAddonDeed();
			}
		}

		[ Constructable ]
		public SmallSteamBoatNorth_PartyTopperAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 43299, -2, -2, 0, 0, 1, "", 1);// 1
			AddComplexComponent( (BaseAddon) this, 43299, -2, 0, 1, 0, 1, "", 1);// 2
			AddComplexComponent( (BaseAddon) this, 43299, -2, 2, 2, 0, 1, "", 1);// 3
			AddComplexComponent( (BaseAddon) this, 43299, 2, -2, 4, 0, 1, "", 1);// 4
			AddComplexComponent( (BaseAddon) this, 43299, 2, 0, 4, 0, 1, "", 1);// 5
			AddComplexComponent( (BaseAddon) this, 43299, 2, 2, 4, 0, 1, "", 1);// 6

		}

		public SmallSteamBoatNorth_PartyTopperAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class SmallSteamBoatNorth_PartyTopperAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new SmallSteamBoatNorth_PartyTopperAddon();
			}
		}

		[Constructable]
		public SmallSteamBoatNorth_PartyTopperAddonDeed()
		{
			Name = "SmallSteamBoatNorth_PartyTopper";
		}

		public SmallSteamBoatNorth_PartyTopperAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}