
////////////////////////////////////////
//                                     //
//   Generated by CEO's YAAAG - Ver 2  //
// (Yet Another Arya Addon Generator)  //
//    Modified by Hammerhand for       //
//      SA & High Seas content         //
//                                     //
////////////////////////////////////////
using System;
using Server;
using Server.Items;

namespace Server.Items
{
	public class FireFruitTreeAddon : BaseAddon
	{
        private static int[,] m_AddOnSimpleComponents = new int[,] {
			  {42597, 1, -1, 0}, {42597, 1, -1, 0}, {42597, -1, 2, 0}// 4	5	6	
			, {42597, 2, 1, 0}, {42597, 1, 2, 0}, {42597, 2, 0, 0}// 7	8	9	
			, {42597, -1, 1, 0}, {3923, 0, 0, 22}, {3319, 0, 2, 1}// 10	12	24	
			, {3318, -1, 2, 1}, {3317, -2, 2, 0}, {3340, 0, 1, 0}// 25	26	29	
			, {3270, 0, 0, 0}, {3270, 2, -2, 0}, {3344, -2, -2, 0}// 33	39	40	
					};

 
            
		public override BaseAddonDeed Deed
		{
			get
			{
				return new FireFruitTreeAddonDeed();
			}
		}

		[ Constructable ]
		public FireFruitTreeAddon()
		{

            for (int i = 0; i < m_AddOnSimpleComponents.Length / 4; i++)
                AddComponent( new AddonComponent( m_AddOnSimpleComponents[i,0] ), m_AddOnSimpleComponents[i,1], m_AddOnSimpleComponents[i,2], m_AddOnSimpleComponents[i,3] );


			AddComplexComponent( (BaseAddon) this, 2512, 1, -1, 2, 1161, -1, "Fire Fruit", 1);// 1
			AddComplexComponent( (BaseAddon) this, 2512, 2, 2, 3, 1161, -1, "Fire Fruit", 1);// 2
			AddComplexComponent( (BaseAddon) this, 2512, -2, 1, 1, 1161, -1, "Fire Fruit", 1);// 3
			AddComplexComponent( (BaseAddon) this, 42595, 1, 1, 11, 0, -1, "Fire Fruit Tree", 1);// 11
			AddComplexComponent( (BaseAddon) this, 3555, 1, 2, 45, 0, 29, "", 1);// 13
			AddComplexComponent( (BaseAddon) this, 3555, 2, 1, 31, 0, 29, "Fire Fruit Tree", 1);// 14
			AddComplexComponent( (BaseAddon) this, 6571, 2, 0, 40, 0, 1, "Fire Fruit Tree", 1);// 15
			AddComplexComponent( (BaseAddon) this, 3555, 2, 1, 40, 0, 1, "", 1);// 16
			AddComplexComponent( (BaseAddon) this, 6571, 2, 2, 44, 0, 1, "", 1);// 17
			AddComplexComponent( (BaseAddon) this, 6571, 0, 2, 37, 0, 1, "Fire Fruit Tree", 1);// 18
			AddComplexComponent( (BaseAddon) this, 6571, 1, -1, 15, 0, 1, "", 1);// 19
			AddComplexComponent( (BaseAddon) this, 3555, 1, 0, 34, 0, 1, "", 1);// 20
			AddComplexComponent( (BaseAddon) this, 6571, 0, 0, 35, 0, 1, "Fire Fruit Tree", 1);// 21
			AddComplexComponent( (BaseAddon) this, 3555, 0, 1, 36, 0, 1, "", 1);// 22
			AddComplexComponent( (BaseAddon) this, 6571, -1, 1, 14, 0, 1, "Fire Fruit Tree", 1);// 23
			AddComplexComponent( (BaseAddon) this, 632, 1, 1, 0, 1037, -1, "", 1);// 27
			AddComplexComponent( (BaseAddon) this, 633, 1, 1, 0, 1037, -1, "", 1);// 28
			AddComplexComponent( (BaseAddon) this, 635, 1, 0, 0, 1037, -1, "", 1);// 30
			AddComplexComponent( (BaseAddon) this, 634, 1, 0, 0, 1037, -1, "", 1);// 31
			AddComplexComponent( (BaseAddon) this, 3299, 0, 0, 3, 1161, -1, "Fire Fruit Tree", 1);// 32
			AddComplexComponent( (BaseAddon) this, 633, -2, 0, 0, 1037, -1, "", 1);// 34
			AddComplexComponent( (BaseAddon) this, 632, 1, -1, 0, 1037, -1, "", 1);// 35
			AddComplexComponent( (BaseAddon) this, 632, 0, -1, 0, 1037, -1, "", 1);// 36
			AddComplexComponent( (BaseAddon) this, 635, 0, -1, 1, 1037, -1, "", 1);// 37
			AddComplexComponent( (BaseAddon) this, 634, -1, -1, 0, 1037, -1, "", 1);// 38

		}

		public FireFruitTreeAddon( Serial serial ) : base( serial )
		{
		}

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource)
        {
            AddComplexComponent(addon, item, xoffset, yoffset, zoffset, hue, lightsource, null, 1);
        }

        private static void AddComplexComponent(BaseAddon addon, int item, int xoffset, int yoffset, int zoffset, int hue, int lightsource, string name, int amount)
        {
            AddonComponent ac;
            ac = new AddonComponent(item);
            if (name != null && name.Length > 0)
                ac.Name = name;
            if (hue != 0)
                ac.Hue = hue;
            if (amount > 1)
            {
                ac.Stackable = true;
                ac.Amount = amount;
            }
            if (lightsource != -1)
                ac.Light = (LightType) lightsource;
            addon.AddComponent(ac, xoffset, yoffset, zoffset);
        }

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}

	public class FireFruitTreeAddonDeed : BaseAddonDeed
	{
		public override BaseAddon Addon
		{
			get
			{
				return new FireFruitTreeAddon();
			}
		}

		[Constructable]
		public FireFruitTreeAddonDeed()
		{
			Name = "FireFruitTree";
		}

		public FireFruitTreeAddonDeed( Serial serial ) : base( serial )
		{
		}

		public override void Serialize( GenericWriter writer )
		{
			base.Serialize( writer );
			writer.Write( 0 ); // Version
		}

		public override void	Deserialize( GenericReader reader )
		{
			base.Deserialize( reader );
			int version = reader.ReadInt();
		}
	}
}